"""内置课程包：分级句子 + 中文译文，首次启动时写入数据库。"""

from . import db

COURSES = [
    {
        "key": "greeting",
        "title": "零基础 · 日常问候",
        "level": "初级",
        "desc": "最基础的打招呼与自我介绍，从单词块开始练起。",
        "items": [
            ("Hello, how are you?", "你好，你好吗？"),
            ("Good morning, everyone.", "大家早上好。"),
            ("Nice to meet you.", "很高兴认识你。"),
            ("My name is Li Hua.", "我叫李华。"),
            ("I am from China.", "我来自中国。"),
            ("How is everything going?", "最近一切都好吗？"),
            ("I am fine, thank you.", "我很好，谢谢你。"),
            ("See you tomorrow.", "明天见。"),
            ("Have a nice day.", "祝你有美好的一天。"),
            ("Excuse me, where is the station?", "打扰一下，车站在哪里？"),
            ("Can you help me, please?", "你能帮帮我吗？"),
            ("Thank you very much.", "非常感谢。"),
            ("You are welcome.", "不客气。"),
            ("I am sorry for being late.", "很抱歉我迟到了。"),
            ("What is your name?", "你叫什么名字？"),
            ("I do not understand.", "我不明白。"),
            ("Could you say that again?", "你能再说一遍吗？"),
            ("Let us start now.", "我们现在开始吧。"),
            ("What a lovely day today!", "今天天气真好！"),
            ("Long time no see!", "好久不见！"),
            ("How was your weekend?", "你周末过得怎么样？"),
            ("It was wonderful, thank you.", "非常愉快，谢谢。"),
            ("Where are you from?", "你来自哪里？"),
            ("I am from the south of China.", "我来自中国南方。"),
            ("How old is your little sister?", "你妹妹多大了？"),
            ("She is five years old.", "她五岁了。"),
            ("What does your father do?", "你爸爸做什么工作？"),
            ("He is a teacher at a middle school.", "他是一名中学老师。"),
            ("Do you like Chinese food?", "你喜欢中餐吗？"),
            ("Yes, I love dumplings very much.", "是的，我特别喜欢饺子。"),
            ("Would you like some more tea?", "再来点茶吗？"),
            ("No, thank you. I have had enough.", "不用了，谢谢，我喝够了。"),
            ("I am afraid I must go now.", "恐怕我现在得走了。"),
            ("It is getting late.", "天不早了。"),
            ("Take care of yourself.", "照顾好自己。"),
            ("Say hello to your family for me.", "替我向你的家人问好。"),
            ("I really enjoyed this evening.", "我今晚过得非常开心。"),
            ("Thank you for your help.", "谢谢你的帮助。"),
            ("It is very kind of you.", "你真是太好了。"),
            ("I am sorry to trouble you.", "很抱歉打扰你。"),
            ("Never mind. It does not matter.", "没关系，不要紧。"),
            ("Please forgive me for being late again.", "请原谅我又迟到了。"),
            ("What do you usually do after work?", "你下班后通常做什么？"),
            ("I usually take a walk in the park.", "我通常去公园散步。"),
            ("How do you like this city?", "你觉得这个城市怎么样？"),
            ("It is beautiful and the people are friendly.", "城市很美，人们很友好。"),
            ("Is this your first visit here?", "这是你第一次来这里吗？"),
            ("Yes, everything is new to me.", "是的，一切对我来说都很新鲜。"),
            ("Wish you a pleasant journey.", "祝你旅途愉快。"),
            ("See you next time.", "下次见。"),
        ],
    },
    {
        "key": "primary",
        "title": "小学 K12 · 校园与生活",
        "level": "初级",
        "desc": "贴近小学生活的短句，练熟最常用的表达。",
        "items": [
            ("I get up at seven every day.", "我每天七点起床。"),
            ("This is my new school bag.", "这是我的新书包。"),
            ("We have four classes today.", "我们今天有四节课。"),
            ("My favorite subject is English.", "我最喜欢的科目是英语。"),
            ("Can I borrow your pencil?", "我能借一下你的铅笔吗？"),
            ("The cat is sleeping on the sofa.", "猫正在沙发上睡觉。"),
            ("There are many trees in our school.", "我们学校里有很多树。"),
            ("I like to read books after school.", "我喜欢放学后读书。"),
            ("My mother is cooking dinner now.", "我妈妈正在做晚饭。"),
            ("It is raining outside.", "外面正在下雨。"),
            ("We play football on the playground.", "我们在操场上踢足球。"),
            ("I go to bed at nine o'clock.", "我九点钟上床睡觉。"),
            ("My father drives me to school.", "我爸爸开车送我去学校。"),
            ("Do you want some apples?", "你想要一些苹果吗？"),
            ("The dog is running after a ball.", "那只狗正在追一个球。"),
            ("I am taller than my brother.", "我比我哥哥高。"),
            ("Today is Monday and it is sunny.", "今天是星期一，天气晴朗。"),
            ("Let us go to the park together.", "我们一起去公园吧。"),
            ("Our teacher tells us an interesting story.", "老师给我们讲了一个有趣的故事。"),
            ("I do my homework before dinner.", "我晚饭前写作业。"),
            ("My little sister likes drawing pictures.", "我妹妹喜欢画画。"),
            ("There is a football match this Friday.", "这周五有一场足球赛。"),
            ("We clean the classroom every day.", "我们每天打扫教室。"),
            ("My favorite animal is the panda.", "我最喜欢的动物是熊猫。"),
            ("Grandpa waters the flowers in the morning.", "爷爷早上浇花。"),
            ("I go to the library twice a week.", "我每周去两次图书馆。"),
            ("Winter vacation starts next month.", "下个月放寒假。"),
            ("My mother bought me a new dictionary.", "妈妈给我买了本新字典。"),
            ("Please line up at the school gate.", "请在校门口排队。"),
            ("We planted some trees in March.", "我们三月种了一些树。"),
            ("The maths problem is not easy.", "这道数学题不容易。"),
            ("I made a snowman with my friends.", "我和朋友们堆了个雪人。"),
            ("Do not eat too much candy.", "不要吃太多糖果。"),
            ("My uncle lives in a small town.", "我叔叔住在一个小镇上。"),
            ("She can play the piano very well.", "她钢琴弹得很好。"),
            ("The summer holiday is coming soon.", "暑假快到了。"),
            ("I brush my teeth three times a day.", "我一天刷三次牙。"),
            ("Welcome to our English corner.", "欢迎来到我们的英语角。"),
            ("My best friend sits next to me.", "我最好的朋友坐在我旁边。"),
            ("We sing songs on the bus.", "我们在公交车上唱歌。"),
            ("Dad reads newspapers after work.", "爸爸下班后看报。"),
            ("The spring festival is in January or February.", "春节在一月或二月。"),
            ("I want to be a scientist in the future.", "我将来想当科学家。"),
            ("Please pass me the salt.", "请把盐递给我。"),
            ("Our school has a big playground.", "我们学校有个大操场。"),
            ("The birds are singing in the tree.", "鸟儿在树上唱歌。"),
            ("Remember to water the plants.", "记得给植物浇水。"),
            ("I got a full mark in the English test.", "我英语考试得了满分。"),
            ("Let us take turns to tell jokes.", "我们轮流讲笑话吧。"),
            ("My family often goes swimming in summer.", "夏天我们家常去游泳。"),
        ],
    },
    {
        "key": "junior",
        "title": "初中 K12 · 日常对话",
        "level": "初级",
        "desc": "初中阶段高频句型，覆盖时态与常用从句。",
        "items": [
            ("I have been learning English for three years.", "我学英语已经三年了。"),
            ("She is going to visit her grandparents.", "她打算去看望她的祖父母。"),
            ("Would you like to join us for lunch?", "你愿意和我们一起吃午饭吗？"),
            ("It takes me twenty minutes to get home.", "我回家要花二十分钟。"),
            ("I was doing my homework at that time.", "那时我正在做作业。"),
            ("He is good at playing basketball.", "他擅长打篮球。"),
            ("Please turn off the lights before you leave.", "离开前请关灯。"),
            ("I think this book is very interesting.", "我觉得这本书很有趣。"),
            ("We should protect the environment.", "我们应该保护环境。"),
            ("She asked me where I lived.", "她问我住在哪里。"),
            ("If it rains tomorrow, we will stay at home.", "如果明天下雨，我们就待在家里。"),
            ("My dream is to become a doctor.", "我的梦想是成为一名医生。"),
            ("The movie was so moving that I cried.", "这部电影太感人了，我哭了。"),
            ("I used to be afraid of the dark.", "我过去怕黑。"),
            ("Remember to bring your umbrella.", "记得带上你的雨伞。"),
            ("He runs faster than anyone in his class.", "他跑得比班上任何人都快。"),
            ("Neither of them knows the answer.", "他们两个都不知道答案。"),
            ("Let me tell you something important.", "让我告诉你一件重要的事。"),
            ("How much does this T-shirt cost?", "这件T恤多少钱？"),
            ("It is on sale for fifty yuan.", "特价五十元。"),
            ("May I try it on?", "我可以试穿吗？"),
            ("The fitting room is over there.", "试衣间在那边。"),
            ("I would like a bowl of beef noodles.", "我想要一碗牛肉面。"),
            ("What would you like to drink?", "你想喝点什么？"),
            ("Could we have the bill, please?", "可以结账了吗？"),
            ("Let us split the bill.", "我们AA吧。"),
            ("Excuse me, is there a bank near here?", "打扰一下，附近有银行吗？"),
            ("Go along this street and turn left at the second crossing.", "沿这条街走，在第二个路口左转。"),
            ("Is it far from here?", "离这儿远吗？"),
            ("It is about ten minutes' walk.", "步行大约十分钟。"),
            ("What is wrong with you?", "你怎么了？"),
            ("I have a headache and a runny nose.", "我头疼还流鼻涕。"),
            ("You should drink more water and have a good rest.", "你应该多喝水好好休息。"),
            ("Have you taken your temperature?", "你量体温了吗？"),
            ("What are your hobbies?", "你有什么爱好？"),
            ("I am interested in collecting stamps.", "我对集邮感兴趣。"),
            ("Swimming is my favorite sport.", "游泳是我最喜欢的运动。"),
            ("I practice the violin every evening.", "我每天晚上练小提琴。"),
            ("What are you going to be when you grow up?", "你长大后想做什么？"),
            ("I hope to travel around the world.", "我希望环游世界。"),
            ("Where did you go last weekend?", "你上周末去哪儿了？"),
            ("We visited the Great Wall.", "我们去参观了长城。"),
            ("How did you get there?", "你们怎么去的？"),
            ("We went there by high-speed train.", "我们坐高铁去的。"),
            ("What is the weather like in your hometown?", "你家乡的天气怎么样？"),
            ("It is warm in spring and cool in autumn.", "春天温暖秋天凉爽。"),
            ("Do not forget to turn in your homework.", "别忘了交作业。"),
            ("You must hand it in before Friday.", "你必须在周五之前交。"),
            ("Why not join our chess club?", "为什么不加入我们的象棋社呢？"),
            ("That sounds like a good idea.", "听起来是个好主意。"),
        ],
    },
    {
        "key": "senior",
        "title": "高中 K12 · 常考句型",
        "level": "中级",
        "desc": "高考常考的固定搭配与复杂句型。",
        "items": [
            ("It is no use crying over spilt milk.", "覆水难收，后悔无用。"),
            ("Only in this way can we solve the problem.", "只有这样我们才能解决这个问题。"),
            ("There is no doubt that he is honest.", "毫无疑问他是诚实的。"),
            ("The harder you work, the luckier you will be.", "你越努力，就会越幸运。"),
            ("It was not until midnight that he came back.", "直到半夜他才回来。"),
            ("I would rather stay at home than go out.", "我宁愿待在家里也不愿出去。"),
            ("Not only did he apologize, but he also offered help.", "他不仅道了歉，还主动提供了帮助。"),
            ("It is high time that we took action.", "我们是时候采取行动了。"),
            ("The reason why he failed is that he was careless.", "他失败的原因是他粗心。"),
            ("She devoted all her life to teaching.", "她把一生都奉献给了教学。"),
            ("What impresses me most is his courage.", "让我印象最深的是他的勇气。"),
            ("Compared with last year, the price has risen.", "与去年相比，价格上涨了。"),
            ("He had no choice but to wait patiently.", "他别无选择，只能耐心等待。"),
            ("It is said that the meeting has been put off.", "据说会议被推迟了。"),
            ("Never have I seen such a beautiful sunset.", "我从未见过如此美丽的日落。"),
            ("We must take every chance to practice English.", "我们必须抓住一切机会练习英语。"),
            ("His advice turned out to be very helpful.", "他的建议结果非常有用。"),
            ("As far as I am concerned, health comes first.", "在我看来，健康第一。"),
            ("Hardly had he arrived when the phone rang.", "他刚到电话就响了。"),
            ("Not until I lost it did I realize its value.", "直到失去它我才知道它的价值。"),
            ("Were I you, I would seize the opportunity.", "我要是你，就会抓住这个机会。"),
            ("Had it not been for your help, I would have failed.", "若不是你帮忙，我就失败了。"),
            ("So excited was she that she could not sleep.", "她兴奋得睡不着觉。"),
            ("It was in the library that I met my old friend.", "就是在图书馆我遇到了老朋友。"),
            ("What surprises me is that he speaks five languages.", "让我惊讶的是他会说五种语言。"),
            ("The moment I saw the photo, memories came back.", "我一看到照片，回忆就涌上来了。"),
            ("Seen from the hill, the town looks small.", "从山上看，这座小镇显得很小。"),
            ("Given more time, we could do it better.", "多给点时间，我们能做得更好。"),
            ("There stands an old temple at the foot of the hill.", "山脚下有座古庙。"),
            ("It remains to be seen whether the plan works.", "这个计划是否可行还有待观察。"),
            ("He is the last person to tell a lie.", "他是最不可能撒谎的人。"),
            ("This is the very book I am looking for.", "这正是我在找的书。"),
            ("Whatever happens, do not lose heart.", "无论发生什么，都不要灰心。"),
            ("As is known to all, practice makes perfect.", "众所周知，熟能生巧。"),
            ("The harder the question is, the more valuable the answer is.", "问题越难，答案越有价值。"),
            ("I have no idea when they will be back.", "我不知道他们什么时候回来。"),
            ("It suddenly occurred to me that I had left my keys inside.", "我突然想起把钥匙落在里面了。"),
            ("What a pity it is that you missed the lecture!", "你错过了讲座，多遗憾啊！"),
            ("She spoke in such a low voice that nobody heard her.", "她说话声音太小，没人听见。"),
            ("Only when you lose something do you understand its worth.", "只有失去时才懂得它的价值。"),
            ("The meeting being over, we went back to work.", "会议结束后，我们回去工作。"),
            ("To be honest, I did not expect so much.", "说实话，我没抱那么大期望。"),
            ("Judging from his accent, he must be from the north.", "从口音判断，他一定是北方人。"),
            ("There is no point in arguing with him.", "和他争论没有意义。"),
            ("It was not long before we became good friends.", "不久我们就成了好朋友。"),
            ("This is because we lack experience.", "这是因为我们缺乏经验。"),
            ("Everything depends on whether you keep trying.", "一切取决于你是否坚持。"),
            ("I would appreciate it if you gave me some advice.", "如果你能给我些建议，我会很感激。"),
            ("The population of this city is larger than that of mine.", "这个城市的人口比我的家乡多。"),
            ("Rather than complain, you should act now.", "与其抱怨，不如现在就行动。"),
        ],
    },
    {
        "key": "cet46",
        "title": "四六级 · 高频句式",
        "level": "中级",
        "desc": "四六级写作与翻译中的万能句式。",
        "items": [
            ("With the development of technology, our life has changed.", "随着科技的发展，我们的生活改变了。"),
            ("There is a growing concern about air pollution.", "人们越来越关注空气污染。"),
            ("It is universally acknowledged that education matters.", "众所周知，教育很重要。"),
            ("A number of factors could account for the problem.", "许多因素可以解释这个问题。"),
            ("We should attach great importance to mental health.", "我们应该高度重视心理健康。"),
            ("On the one hand, it saves time; on the other hand, it costs money.", "一方面它省时间，另一方面它花钱。"),
            ("Taking all these factors into consideration, we may draw a conclusion.", "考虑到所有这些因素，我们可以得出结论。"),
            ("Nothing is more important than keeping a balance.", "没有什么比保持平衡更重要。"),
            ("It is high time that the government took measures.", "政府是时候采取措施了。"),
            ("Despite the difficulties, they never gave up.", "尽管有困难，他们从未放弃。"),
            ("The advantages far outweigh the disadvantages.", "优点远远大于缺点。"),
            ("Only by working together can we make a difference.", "只有通力合作，我们才能有所作为。"),
            ("There is no denying that the Internet brings convenience.", "不可否认，互联网带来了便利。"),
            ("People hold different views on this issue.", "人们对这个问题持不同看法。"),
            ("As a result, more students choose to study abroad.", "因此，更多的学生选择出国留学。"),
            ("In conclusion, every coin has two sides.", "总之，凡事都有两面性。"),
            ("It is of great significance to develop good habits.", "养成好习惯意义重大。"),
            ("We cannot emphasize the importance of reading too much.", "我们再怎么强调阅读的重要性也不为过。"),
            ("Measures should be taken to address this issue.", "应采取措施解决这个问题。"),
            ("The rapid growth of the economy brings both opportunities and challenges.", "经济的快速增长带来机遇与挑战。"),
            ("A sound body is more valuable than wealth.", "健康的身体比财富更宝贵。"),
            ("Reading broadens our horizons and enriches our mind.", "阅读开阔视野丰富心灵。"),
            ("It is essential to strike a balance between work and rest.", "劳逸结合至关重要。"),
            ("The phenomenon deserves our careful attention.", "这种现象值得我们认真关注。"),
            ("One possible explanation is that social pressure keeps increasing.", "一种可能的解释是社会压力不断增加。"),
            ("Statistics show that car ownership has doubled in five years.", "数据显示汽车保有量五年翻了一番。"),
            ("We should never lose hope in the face of difficulties.", "面对困难我们绝不能失去希望。"),
            ("Cooperation plays an increasingly important role in modern society.", "合作在现代社会扮演越来越重要的角色。"),
            ("It goes without saying that practice leads to success.", "不言而喻，实践通向成功。"),
            ("The government has invested heavily in basic education.", "政府在基础教育上投入巨大。"),
            ("What we need most is confidence and patience.", "我们最需要的是信心和耐心。"),
            ("Society benefits greatly from volunteers' devotion.", "社会因志愿者的奉献而受益匪浅。"),
            ("New energy vehicles are gaining popularity among young people.", "新能源汽车越来越受年轻人欢迎。"),
            ("Failure is the mother of success, as the saying goes.", "俗话说，失败是成功之母。"),
            ("There is a general debate on campus today about this topic.", "如今校园里对这一话题存在普遍争论。"),
            ("The key to solving the problem lies in mutual understanding.", "解决问题的关键在于相互理解。"),
            ("Modern science and technology have transformed our way of life.", "现代科技改变了我们的生活方式。"),
            ("We should view the matter from different angles.", "我们应该从不同角度看问题。"),
            ("This phenomenon reflects a deep social change.", "这种现象反映了深刻的社会变迁。"),
            ("As college students, we have the duty to serve society.", "作为大学生，我们有责任服务社会。"),
            ("The Internet makes distant communication possible and cheap.", "互联网让远距离交流变得可能而廉价。"),
            ("A positive attitude is half the battle.", "积极的态度是成功的一半。"),
            ("It is high time that we paid attention to food safety.", "我们是时候关注食品安全了。"),
            ("Hard work is the foundation of every great achievement.", "努力是一切伟大成就的基础。"),
            ("The elderly deserve more care from the young.", "老年人理应得到年轻人更多的关怀。"),
            ("Choosing a suitable career matters to everyone.", "选择合适的职业对每个人都重要。"),
            ("More and more people realize the value of lifelong learning.", "越来越多的人意识到终身学习的价值。"),
            ("Diligence can make up for the lack of talent.", "勤能补拙。"),
            ("Every individual should take responsibility for the environment.", "每个人都应为环境负责。"),
            ("In a word, persistence guarantees success.", "总之，坚持保证成功。"),
        ],
    },
    {
        "key": "ielts",
        "title": "雅思托福 · 学术表达",
        "level": "高级",
        "desc": "写作与口语高分句型，适合冲刺 7 分以上。",
        "items": [
            ("The graph illustrates the changes in population over two decades.", "该图表展示了二十年间人口的变化。"),
            ("It is arguable that technology isolates people from each other.", "科技使人们彼此隔绝，这一点值得商榷。"),
            ("A substantial proportion of income is spent on housing.", "收入的相当大一部分花在住房上。"),
            ("From my perspective, the benefits outweigh the drawbacks.", "在我看来，利大于弊。"),
            ("The data suggest a steady decline in unemployment.", "数据表明失业率稳步下降。"),
            ("This phenomenon can be attributed to several factors.", "这一现象可归因于若干因素。"),
            ("Governments should allocate more resources to public transport.", "政府应向公共交通投入更多资源。"),
            ("While some people argue otherwise, the evidence is compelling.", "虽然有人持相反观点，但证据很有说服力。"),
            ("The disparity between urban and rural areas remains striking.", "城乡之间的差距依然显著。"),
            ("To what extent do you agree with this statement?", "你在多大程度上同意这一说法？"),
            ("An increasing number of graduates pursue further study.", "越来越多的毕业生选择继续深造。"),
            ("The policy has had a profound impact on society.", "这项政策对社会产生了深远影响。"),
            ("Conversely, excessive reliance on cars causes congestion.", "相反，过度依赖汽车会造成拥堵。"),
            ("It is worth noting that the trend reversed after 2010.", "值得注意的是，这一趋势在 2010 年后逆转。"),
            ("Further research is needed to confirm the findings.", "需要进一步研究来证实这些发现。"),
            ("Overall, the advantages of remote work are evident.", "总体而言，远程办公的优势是明显的。"),
            ("Such measures may alleviate, though not eliminate, the problem.", "这些措施或许能缓解但不能根除这个问题。"),
            ("In light of these considerations, a balanced approach is advisable.", "鉴于这些考量，采取平衡的做法是明智的。"),
            ("The chart compares energy consumption in four countries.", "图表比较了四个国家的能源消耗。"),
            ("The figures peaked in 2008 before falling sharply.", "数据在2008年达到峰值后急剧下降。"),
            ("Over the period, the trend showed a slight fluctuation.", "在此期间，趋势呈现小幅波动。"),
            ("There was a twofold increase in the number of tourists.", "游客数量翻了一番。"),
            ("This essay will examine both sides of the argument.", "本文将探讨该论点的两面。"),
            ("Access to higher education remains unequal across regions.", "各地区的高等教育机会依然不平等。"),
            ("The survey covers a sample of one thousand respondents.", "该调查覆盖一千名受访者样本。"),
            ("A growing body of evidence supports this claim.", "越来越多的证据支持这一主张。"),
            ("Urbanisation has accelerated the demand for housing.", "城市化加速了住房需求。"),
            ("The correlation, however, does not imply causation.", "然而相关性并不意味着因果关系。"),
            ("Remote learning, if properly designed, can match classroom outcomes.", "远程学习若设计得当可媲美课堂效果。"),
            ("The drawbacks of the policy are not negligible.", "政策的弊端不容忽视。"),
            ("Elderly care will place a heavy burden on public funds.", "养老将给公共资金带来沉重负担。"),
            ("Investment in infrastructure yields long-term returns.", "基础设施投资带来长期回报。"),
            ("Admittedly, automation may displace certain jobs.", "诚然，自动化可能取代部分工作。"),
            ("The solution lies in comprehensive education reform.", "解决之道在于全面的教育改革。"),
            ("The conclusion is consistent with previous studies.", "该结论与以往研究一致。"),
            ("Digital literacy has become a basic requirement in the workplace.", "数字素养已成为职场基本要求。"),
            ("Consumers increasingly prefer environmentally friendly products.", "消费者日益青睐环保产品。"),
            ("The gap between rich and poor has widened over the decade.", "十年间贫富差距扩大了。"),
            ("Governments are under pressure to reduce carbon emissions.", "政府面临减排压力。"),
            ("Cross-cultural communication skills are in great demand.", "跨文化沟通技巧需求很大。"),
            ("The issue is far more complex than it appears.", "这个问题远比表面复杂。"),
            ("A case in point is the rise of shared bicycles.", "一个典型的例子是共享单车的兴起。"),
            ("Whether the benefits justify the cost remains debatable.", "收益是否物有所值仍有争议。"),
            ("The statistics may be subject to sampling errors.", "统计数据可能存在抽样误差。"),
            ("Renewable energy accounts for a growing share of the market.", "可再生能源市场份额不断扩大。"),
            ("This approach, however, is not without its critics.", "然而，这一做法并非没有批评者。"),
            ("Lifelong learning will define the future labour market.", "终身学习将定义未来劳动力市场。"),
            ("The findings have important implications for policymakers.", "这些发现对政策制定者有重要启示。"),
            ("Bilingual education fosters cognitive flexibility.", "双语教育培养认知灵活性。"),
            ("It would be premature to draw a final conclusion now.", "现在下最终结论为时尚早。"),
        ],
    },
    {
        "key": "series",
        "title": "美剧口语 · 高频台词",
        "level": "中级",
        "desc": "老友记、生活大爆炸等剧集里的地道口语。",
        "items": [
            ("How you doing?", "你好啊？（老友记经典打招呼）"),
            ("I will be there for you.", "我会在你身边支持你。"),
            ("Could this be any more obvious?", "这还能更明显一点吗？"),
            ("We were on a break!", "我们当时处于分手状态！"),
            ("Bazinga!", "骗到你了！（谢尔顿口头禅）"),
            ("I am not great at the advice, can I interest you in a sarcastic comment?", "我不太会给建议，要不要来句讽刺？"),
            ("It is not you, it is me.", "不是你的问题，是我的问题。"),
            ("Let us just cut to the chase.", "我们就直奔主题吧。"),
            ("That is what she said.", "她就是这么说的。（双关梗）"),
            ("I have no idea what you are talking about.", "我完全不知道你在说什么。"),
            ("You had me at hello.", "你一开口我就心动了。"),
            ("Frankly, my dear, I do not give a damn.", "坦白说，亲爱的，我一点都不在乎。"),
            ("May the force be with you.", "愿原力与你同在。"),
            ("I will make him an offer he cannot refuse.", "我会给他一个无法拒绝的条件。"),
            ("Keep your friends close and your enemies closer.", "亲近你的朋友，更要亲近你的敌人。"),
            ("Life is like a box of chocolates.", "生活就像一盒巧克力。"),
            ("Get busy living, or get busy dying.", "要么忙于活着，要么忙于死去。"),
            ("Winter is coming.", "凛冬将至。"),
            ("We were on the same page.", "我们想到一块儿去了。"),
            ("That is a whole other story.", "那完全是另一回事。"),
            ("You are so dead.", "你死定了。"),
            ("I have got your back.", "我罩着你。"),
            ("It is a win-win situation.", "这是双赢的局面。"),
            ("You know what? Forget it.", "你知道吗？算了吧。"),
            ("I could not agree more.", "我再同意不过了。"),
            ("This is so not fair.", "这太不公平了。"),
            ("Are you out of your mind?", "你疯了吗？"),
            ("Just let it go.", "就随它去吧。"),
            ("You read my mind.", "你太懂我了。"),
            ("Cut it out!", "别闹了！"),
            ("I am all ears.", "我洗耳恭听。"),
            ("It is now or never.", "机不可失，时不再来。"),
            ("Do not get me wrong.", "别误会我。"),
            ("That hits the spot.", "这太解馋了。"),
            ("My lips are sealed.", "我守口如瓶。"),
            ("You are pulling my leg.", "你在逗我吧。"),
            ("I am in a rush right now.", "我现在赶时间。"),
            ("It is not rocket science.", "这又不是什么难事。"),
            ("Better late than never.", "迟到总比不到好。"),
            ("What is done is done.", "事已至此。"),
            ("I did not see that coming.", "我没料到会这样。"),
            ("Keep it between us.", "就我们俩知道。"),
            ("It is worth a shot.", "值得一试。"),
            ("You owe me one.", "你欠我一个人情。"),
            ("Let us call it a day.", "今天就到这儿吧。"),
            ("I am on top of it.", "我盯着的呢。"),
            ("That is the last straw.", "是可忍孰不可忍。"),
            ("Suit yourself.", "随你的便。"),
            ("You made my day.", "你让我一天都开心。"),
            ("Trust me, it works like magic.", "相信我，好使得很。"),
        ],
    },
    {
        "key": "workplace",
        "title": "职场英语 · 邮件与会议",
        "level": "中级",
        "desc": "写邮件、开会、汇报时最常用的一句话。",
        "items": [
            ("I am writing to confirm our meeting tomorrow.", "我写这封邮件是为了确认我们明天的会议。"),
            ("Please find the attached report for your review.", "请查收附件中的报告并审阅。"),
            ("Could we schedule a call for next Monday?", "我们能把电话会议安排在下周一吗？"),
            ("I look forward to hearing from you soon.", "期待尽快收到你的回复。"),
            ("Let me walk you through the key figures.", "让我带你过一遍关键数据。"),
            ("Could you clarify what you mean by that?", "你能说明一下你的意思吗？"),
            ("I will follow up with the client this afternoon.", "我今天下午会跟进客户。"),
            ("The deadline has been extended by one week.", "截止日期延长了一周。"),
            ("Thanks for your prompt reply.", "感谢你的及时回复。"),
            ("I would appreciate it if you could review the draft.", "如果你能审阅一下草稿，我将不胜感激。"),
            ("Let us take a step back and look at the big picture.", "我们退一步，看看全局。"),
            ("Our team is behind schedule on this project.", "我们团队在这个项目上进度落后。"),
            ("Do you have any concerns about the proposal?", "你对这个方案有什么顾虑吗？"),
            ("I will take care of it right away.", "我马上处理这件事。"),
            ("Please keep me posted on any updates.", "有任何进展请随时告知我。"),
            ("The feedback from users has been very positive.", "用户反馈非常积极。"),
            ("Let us wrap up the meeting with a quick summary.", "我们用一个简短的总结结束会议。"),
            ("Feel free to reach out if you have questions.", "如果有问题，随时联系我。"),
            ("Sorry for the late reply.", "回复晚了，抱歉。"),
            ("Could you resend the attachment?", "能再发一次附件吗？"),
            ("I have cc'd the manager on this email.", "我把这封邮件抄送了经理。"),
            ("Let us set up a quick call to align.", "我们约个短电话对齐一下。"),
            ("I will check my calendar and get back to you.", "我查下日历再回复你。"),
            ("The report is due by end of day.", "报告今天下班前要交。"),
            ("Please prioritize the urgent tickets first.", "请优先处理紧急工单。"),
            ("We are aligned on the deliverables.", "我们在交付物上达成一致了。"),
            ("The fix has been deployed to production.", "修复已部署上线。"),
            ("Let me double-check and confirm with you.", "我再核实一下和你确认。"),
            ("Any update on the issue?", "这个问题有进展吗？"),
            ("Could you approve the request today?", "你今天能批准这个申请吗？"),
            ("The client raised a new requirement.", "客户提了一个新需求。"),
            ("We may need to adjust the timeline.", "我们可能需要调整时间表。"),
            ("It is out of scope for this sprint.", "这超出了本次迭代范围。"),
            ("I will take minutes for the meeting.", "我来做会议纪要。"),
            ("Does anyone have anything to add?", "有人要补充吗？"),
            ("Let us park this topic for now.", "这个话题我们先搁置。"),
            ("The numbers speak for themselves.", "数据说明一切。"),
            ("Good catch!", "发现得好！"),
            ("Please review my pull request when you can.", "有空请审阅我的合并请求。"),
            ("The demo went smoothly.", "演示很顺利。"),
            ("I am on sick leave tomorrow.", "我明天请病假。"),
            ("Let us move the meeting to Thursday.", "我们把会议挪到周四吧。"),
            ("Could you share the link in the chat?", "你能在聊天里分享链接吗？"),
            ("The budget has been approved.", "预算已批准。"),
            ("We appreciate your patience.", "感谢您的耐心等待。"),
            ("Please sign the contract by Friday.", "请在周五前签合同。"),
            ("It works as expected.", "功能符合预期。"),
            ("The issue has been resolved.", "问题已解决。"),
            ("I will be out of office next week.", "我下周不在办公室。"),
            ("Have a great holiday!", "假期愉快！"),
        ],
    },
    {
        "key": "travel",
        "title": "旅行英语 · 出行必备",
        "level": "初级",
        "desc": "机场、酒店、问路、点餐场景高频句。",
        "items": [
            ("Where can I check in for my flight?", "我在哪里可以办理登机手续？"),
            ("I would like a window seat, please.", "我想要一个靠窗的座位。"),
            ("How much is a ticket to the city center?", "到市中心的票多少钱？"),
            ("Could you show me the way to the museum?", "你能告诉我去博物馆怎么走吗？"),
            ("I have a reservation under the name Wang.", "我有一个王姓的预订。"),
            ("Is breakfast included in the price?", "价格里含早餐吗？"),
            ("Could I have the menu, please?", "请给我菜单好吗？"),
            ("I am allergic to nuts.", "我对坚果过敏。"),
            ("Can I pay by credit card?", "我可以用信用卡付款吗？"),
            ("Where is the nearest subway station?", "最近的地铁站在哪里？"),
            ("How long does it take to get there?", "到那里需要多长时间？"),
            ("I would like to book a room for two nights.", "我想订两晚的房间。"),
            ("Could you take a photo for us?", "你能帮我们拍张照吗？"),
            ("I lost my luggage at the airport.", "我在机场丢了行李。"),
            ("This dish is delicious.", "这道菜很好吃。"),
            ("Please take me to this address.", "请带我去这个地址。"),
            ("Is there a pharmacy nearby?", "附近有药店吗？"),
            ("I need to exchange some money.", "我需要兑换一些钱。"),
            ("What time does the flight board?", "航班几点登机？"),
            ("My flight has been delayed for two hours.", "我的航班延误两小时。"),
            ("Where can I get a boarding pass?", "在哪里取登机牌？"),
            ("How many bags can I check in?", "我能托运几件行李？"),
            ("Is this the gate for flight CA123?", "这是CA123航班的登机口吗？"),
            ("I would like to change my booking.", "我想改签。"),
            ("Can I get a refund for this ticket?", "这张票能退吗？"),
            ("Do you have anything to declare?", "您有需要申报的物品吗？"),
            ("Where is the currency exchange?", "货币兑换处在哪里？"),
            ("Could you keep this safe for me?", "能帮我保管一下吗？"),
            ("I would like a room with a sea view.", "我想要一间海景房。"),
            ("What time is check-out?", "几点退房？"),
            ("The air conditioner does not work.", "空调坏了。"),
            ("Could you send someone to fix it?", "能派人来修一下吗？"),
            ("Is there a free shuttle to the airport?", "有去机场的免费班车吗？"),
            ("Could I get a map of the city?", "能给我一张城市地图吗？"),
            ("What places are worth visiting?", "哪些地方值得一看？"),
            ("Is it safe to walk around at night?", "晚上在外面走安全吗？"),
            ("What is the local specialty?", "当地特色菜是什么？"),
            ("I would like it not too spicy.", "请做得不要太辣。"),
            ("Could we sit by the window?", "我们能坐窗边吗？"),
            ("The bill seems to be wrong.", "账单好像不对。"),
            ("Do you offer tax refund service?", "你们提供退税服务吗？"),
            ("Where can I buy a local SIM card?", "在哪里能买当地电话卡？"),
            ("How do I get to the beach from here?", "从这里怎么去海滩？"),
            ("Is the museum open on Monday?", "博物馆周一开门吗？"),
            ("How much is the entrance fee?", "门票多少钱？"),
            ("Are there any discounts for students?", "学生有优惠吗？"),
            ("I missed the last train.", "我错过了末班车。"),
            ("Could you call a taxi for me?", "能帮我叫辆出租车吗？"),
            ("I need a doctor who speaks English.", "我需要一位会说英语的医生。"),
            ("Where is the lost and found?", "失物招领处在哪里？"),
        ],
    },
]


def seed():
    """把内置课程写入数据库。

    新课程：整门写入；已存在但句数不足（内置内容扩充过）：增量补齐新句，
    不动旧句（保护用户已有的练习记录与 SRS 卡片）。
    词汇课程另做 note 刷新：旧词条升级加音标（seq 对齐，只改 note 字段）。
    """
    from . import phonics_data
    from .vocab_primary import VOCAB_COURSES
    from .sentences_xqh import GROUPS as XQH_SENTENCES

    conn = db.connect()
    exist = {r["builtin_key"] for r in conn.execute("SELECT builtin_key FROM courses").fetchall()}
    conn.close()
    for c in list(COURSES) + list(VOCAB_COURSES) + list(XQH_SENTENCES):
        if c["key"] in exist:
            row = db.get_course_by_key(c["key"])
            have = db.count_sentences(row["id"])
            if have < len(c["items"]):
                db.add_sentences(row["id"], c["items"][have:])
            continue
        cid = db.add_course(c["title"], c["desc"], c["level"], "builtin", c["key"])
        db.add_sentences(cid, c["items"])
    phonics_data.seed()
    refresh_vocab_notes()
    fix_legacy_text()


# 旧数据里出现的「字体缺失」字符 → 统一替换为可用字形，避免升级后仍显示方块
_CHAR_FIXES = {
    "隻": "只",   # 繁体「隻」不在简体子集中
}


def fix_legacy_text():
    """修正旧数据里的缺字形/繁体字符（增量升级时对已存在句子生效）。"""
    conn = db.connect()
    try:
        rows = conn.execute("SELECT id, en, zh FROM sentences").fetchall()
        for r in rows:
            en, zh = r["en"] or "", r["zh"] or ""
            new_en, new_zh = en, zh
            for bad, good in _CHAR_FIXES.items():
                if bad in new_en:
                    new_en = new_en.replace(bad, good)
                if bad in new_zh:
                    new_zh = new_zh.replace(bad, good)
            if new_en != en or new_zh != zh:
                conn.execute("UPDATE sentences SET en=?, zh=? WHERE id=?",
                             (new_en, new_zh, r["id"]))
        conn.commit()
    finally:
        conn.close()


def refresh_vocab_notes():
    """词汇课程 note 升级：给旧词条补音标（按 en 精确匹配，不动其他字段）。"""
    from .vocab_primary import VOCAB_COURSES
    conn = db.connect()
    for c in VOCAB_COURSES:
        row = conn.execute(
            "SELECT id FROM courses WHERE builtin_key=?", (c["key"],)).fetchone()
        if not row:
            continue
        cid = row["id"]
        for item in c["items"]:
            en, zh, note = (list(item) + [""])[:3]
            conn.execute(
                "UPDATE sentences SET note=? WHERE course_id=? AND en=? AND note NOT LIKE '音标：%'",
                (note, cid, en.strip()))
    conn.commit()
    conn.close()
