"""内置课程包：分级句子 + 中文译文，首次启动时写入数据库。"""

from . import db

COURSES = [
    {
        "key": "greeting",
        "title": "零基础 · 日常问候",
        "level": "初级",
        "desc": "最基础的打招呼与自我介绍，从单词块开始练起。",
        "items": [
            ("Hello, how are you?", "你好，你好吗？"),
            ("Good morning, everyone.", "大家早上好。"),
            ("Nice to meet you.", "很高兴认识你。"),
            ("My name is Li Hua.", "我叫李华。"),
            ("I am from China.", "我来自中国。"),
            ("How is everything going?", "最近一切都好吗？"),
            ("I am fine, thank you.", "我很好，谢谢你。"),
            ("See you tomorrow.", "明天见。"),
            ("Have a nice day.", "祝你有美好的一天。"),
            ("Excuse me, where is the station?", "打扰一下，车站在哪里？"),
            ("Can you help me, please?", "你能帮帮我吗？"),
            ("Thank you very much.", "非常感谢。"),
            ("You are welcome.", "不客气。"),
            ("I am sorry for being late.", "很抱歉我迟到了。"),
            ("What is your name?", "你叫什么名字？"),
            ("I do not understand.", "我不明白。"),
            ("Could you say that again?", "你能再说一遍吗？"),
            ("Let us start now.", "我们现在开始吧。"),
        ],
    },
    {
        "key": "primary",
        "title": "小学 K12 · 校园与生活",
        "level": "初级",
        "desc": "贴近小学生活的短句，练熟最常用的表达。",
        "items": [
            ("I get up at seven every day.", "我每天七点起床。"),
            ("This is my new school bag.", "这是我的新书包。"),
            ("We have four classes today.", "我们今天有四节课。"),
            ("My favorite subject is English.", "我最喜欢的科目是英语。"),
            ("Can I borrow your pencil?", "我能借一下你的铅笔吗？"),
            ("The cat is sleeping on the sofa.", "猫正在沙发上睡觉。"),
            ("There are many trees in our school.", "我们学校里有很多树。"),
            ("I like to read books after school.", "我喜欢放学后读书。"),
            ("My mother is cooking dinner now.", "我妈妈正在做晚饭。"),
            ("It is raining outside.", "外面正在下雨。"),
            ("We play football on the playground.", "我们在操场上踢足球。"),
            ("I go to bed at nine o'clock.", "我九点钟上床睡觉。"),
            ("My father drives me to school.", "我爸爸开车送我去学校。"),
            ("Do you want some apples?", "你想要一些苹果吗？"),
            ("The dog is running after a ball.", "那只狗正在追一个球。"),
            ("I am taller than my brother.", "我比我哥哥高。"),
            ("Today is Monday and it is sunny.", "今天是星期一，天气晴朗。"),
            ("Let us go to the park together.", "我们一起去公园吧。"),
        ],
    },
    {
        "key": "junior",
        "title": "初中 K12 · 日常对话",
        "level": "初级",
        "desc": "初中阶段高频句型，覆盖时态与常用从句。",
        "items": [
            ("I have been learning English for three years.", "我学英语已经三年了。"),
            ("She is going to visit her grandparents.", "她打算去看望她的祖父母。"),
            ("Would you like to join us for lunch?", "你愿意和我们一起吃午饭吗？"),
            ("It takes me twenty minutes to get home.", "我回家要花二十分钟。"),
            ("I was doing my homework at that time.", "那时我正在做作业。"),
            ("He is good at playing basketball.", "他擅长打篮球。"),
            ("Please turn off the lights before you leave.", "离开前请关灯。"),
            ("I think this book is very interesting.", "我觉得这本书很有趣。"),
            ("We should protect the environment.", "我们应该保护环境。"),
            ("She asked me where I lived.", "她问我住在哪里。"),
            ("If it rains tomorrow, we will stay at home.", "如果明天下雨，我们就待在家里。"),
            ("My dream is to become a doctor.", "我的梦想是成为一名医生。"),
            ("The movie was so moving that I cried.", "这部电影太感人了，我哭了。"),
            ("I used to be afraid of the dark.", "我过去怕黑。"),
            ("Remember to bring your umbrella.", "记得带上你的雨伞。"),
            ("He runs faster than anyone in his class.", "他跑得比班上任何人都快。"),
            ("Neither of them knows the answer.", "他们两个都不知道答案。"),
            ("Let me tell you something important.", "让我告诉你一件重要的事。"),
        ],
    },
    {
        "key": "senior",
        "title": "高中 K12 · 常考句型",
        "level": "中级",
        "desc": "高考常考的固定搭配与复杂句型。",
        "items": [
            ("It is no use crying over spilt milk.", "覆水难收，后悔无用。"),
            ("Only in this way can we solve the problem.", "只有这样我们才能解决这个问题。"),
            ("There is no doubt that he is honest.", "毫无疑问他是诚实的。"),
            ("The harder you work, the luckier you will be.", "你越努力，就会越幸运。"),
            ("It was not until midnight that he came back.", "直到半夜他才回来。"),
            ("I would rather stay at home than go out.", "我宁愿待在家里也不愿出去。"),
            ("Not only did he apologize, but he also offered help.", "他不仅道了歉，还主动提供了帮助。"),
            ("It is high time that we took action.", "我们是时候采取行动了。"),
            ("The reason why he failed is that he was careless.", "他失败的原因是他粗心。"),
            ("She devoted all her life to teaching.", "她把一生都奉献给了教学。"),
            ("What impresses me most is his courage.", "让我印象最深的是他的勇气。"),
            ("Compared with last year, the price has risen.", "与去年相比，价格上涨了。"),
            ("He had no choice but to wait patiently.", "他别无选择，只能耐心等待。"),
            ("It is said that the meeting has been put off.", "据说会议被推迟了。"),
            ("Never have I seen such a beautiful sunset.", "我从未见过如此美丽的日落。"),
            ("We must take every chance to practice English.", "我们必须抓住一切机会练习英语。"),
            ("His advice turned out to be very helpful.", "他的建议结果非常有用。"),
            ("As far as I am concerned, health comes first.", "在我看来，健康第一。"),
        ],
    },
    {
        "key": "cet46",
        "title": "四六级 · 高频句式",
        "level": "中级",
        "desc": "四六级写作与翻译中的万能句式。",
        "items": [
            ("With the development of technology, our life has changed.", "随着科技的发展，我们的生活改变了。"),
            ("There is a growing concern about air pollution.", "人们越来越关注空气污染。"),
            ("It is universally acknowledged that education matters.", "众所周知，教育很重要。"),
            ("A number of factors could account for the problem.", "许多因素可以解释这个问题。"),
            ("We should attach great importance to mental health.", "我们应该高度重视心理健康。"),
            ("On the one hand, it saves time; on the other hand, it costs money.", "一方面它省时间，另一方面它花钱。"),
            ("Taking all these factors into consideration, we may draw a conclusion.", "考虑到所有这些因素，我们可以得出结论。"),
            ("Nothing is more important than keeping a balance.", "没有什么比保持平衡更重要。"),
            ("It is high time that the government took measures.", "政府是时候采取措施了。"),
            ("Despite the difficulties, they never gave up.", "尽管有困难，他们从未放弃。"),
            ("The advantages far outweigh the disadvantages.", "优点远远大于缺点。"),
            ("Only by working together can we make a difference.", "只有通力合作，我们才能有所作为。"),
            ("There is no denying that the Internet brings convenience.", "不可否认，互联网带来了便利。"),
            ("People hold different views on this issue.", "人们对这个问题持不同看法。"),
            ("As a result, more students choose to study abroad.", "因此，更多的学生选择出国留学。"),
            ("In conclusion, every coin has two sides.", "总之，凡事都有两面性。"),
            ("It is of great significance to develop good habits.", "养成好习惯意义重大。"),
            ("We cannot emphasize the importance of reading too much.", "我们再怎么强调阅读的重要性也不为过。"),
        ],
    },
    {
        "key": "ielts",
        "title": "雅思托福 · 学术表达",
        "level": "高级",
        "desc": "写作与口语高分句型，适合冲刺 7 分以上。",
        "items": [
            ("The graph illustrates the changes in population over two decades.", "该图表展示了二十年间人口的变化。"),
            ("It is arguable that technology isolates people from each other.", "科技使人们彼此隔绝，这一点值得商榷。"),
            ("A substantial proportion of income is spent on housing.", "收入的相当大一部分花在住房上。"),
            ("From my perspective, the benefits outweigh the drawbacks.", "在我看来，利大于弊。"),
            ("The data suggest a steady decline in unemployment.", "数据表明失业率稳步下降。"),
            ("This phenomenon can be attributed to several factors.", "这一现象可归因于若干因素。"),
            ("Governments should allocate more resources to public transport.", "政府应向公共交通投入更多资源。"),
            ("While some people argue otherwise, the evidence is compelling.", "虽然有人持相反观点，但证据很有说服力。"),
            ("The disparity between urban and rural areas remains striking.", "城乡之间的差距依然显著。"),
            ("To what extent do you agree with this statement?", "你在多大程度上同意这一说法？"),
            ("An increasing number of graduates pursue further study.", "越来越多的毕业生选择继续深造。"),
            ("The policy has had a profound impact on society.", "这项政策对社会产生了深远影响。"),
            ("Conversely, excessive reliance on cars causes congestion.", "相反，过度依赖汽车会造成拥堵。"),
            ("It is worth noting that the trend reversed after 2010.", "值得注意的是，这一趋势在 2010 年后逆转。"),
            ("Further research is needed to confirm the findings.", "需要进一步研究来证实这些发现。"),
            ("Overall, the advantages of remote work are evident.", "总体而言，远程办公的优势是明显的。"),
            ("Such measures may alleviate, though not eliminate, the problem.", "这些措施或许能缓解但不能根除这个问题。"),
            ("In light of these considerations, a balanced approach is advisable.", "鉴于这些考量，采取平衡的做法是明智的。"),
        ],
    },
    {
        "key": "series",
        "title": "美剧口语 · 高频台词",
        "level": "中级",
        "desc": "老友记、生活大爆炸等剧集里的地道口语。",
        "items": [
            ("How you doing?", "你好啊？（老友记经典打招呼）"),
            ("I will be there for you.", "我会在你身边支持你。"),
            ("Could this be any more obvious?", "这还能更明显一点吗？"),
            ("We were on a break!", "我们当时处于分手状态！"),
            ("Bazinga!", "骗到你了！（谢尔顿口头禅）"),
            ("I am not great at the advice, can I interest you in a sarcastic comment?", "我不太会给建议，要不要来句讽刺？"),
            ("It is not you, it is me.", "不是你的问题，是我的问题。"),
            ("Let us just cut to the chase.", "我们就直奔主题吧。"),
            ("That is what she said.", "她就是这么说的。（双关梗）"),
            ("I have no idea what you are talking about.", "我完全不知道你在说什么。"),
            ("You had me at hello.", "你一开口我就心动了。"),
            ("Frankly, my dear, I do not give a damn.", "坦白说，亲爱的，我一点都不在乎。"),
            ("May the force be with you.", "愿原力与你同在。"),
            ("I will make him an offer he cannot refuse.", "我会给他一个无法拒绝的条件。"),
            ("Keep your friends close and your enemies closer.", "亲近你的朋友，更要亲近你的敌人。"),
            ("Life is like a box of chocolates.", "生活就像一盒巧克力。"),
            ("Get busy living, or get busy dying.", "要么忙于活着，要么忙于死去。"),
            ("Winter is coming.", "凛冬将至。"),
        ],
    },
    {
        "key": "workplace",
        "title": "职场英语 · 邮件与会议",
        "level": "中级",
        "desc": "写邮件、开会、汇报时最常用的一句话。",
        "items": [
            ("I am writing to confirm our meeting tomorrow.", "我写这封邮件是为了确认我们明天的会议。"),
            ("Please find the attached report for your review.", "请查收附件中的报告并审阅。"),
            ("Could we schedule a call for next Monday?", "我们能把电话会议安排在下周一吗？"),
            ("I look forward to hearing from you soon.", "期待尽快收到你的回复。"),
            ("Let me walk you through the key figures.", "让我带你过一遍关键数据。"),
            ("Could you clarify what you mean by that?", "你能说明一下你的意思吗？"),
            ("I will follow up with the client this afternoon.", "我今天下午会跟进客户。"),
            ("The deadline has been extended by one week.", "截止日期延长了一周。"),
            ("Thanks for your prompt reply.", "感谢你的及时回复。"),
            ("I would appreciate it if you could review the draft.", "如果你能审阅一下草稿，我将不胜感激。"),
            ("Let us take a step back and look at the big picture.", "我们退一步，看看全局。"),
            ("Our team is behind schedule on this project.", "我们团队在这个项目上进度落后。"),
            ("Do you have any concerns about the proposal?", "你对这个方案有什么顾虑吗？"),
            ("I will take care of it right away.", "我马上处理这件事。"),
            ("Please keep me posted on any updates.", "有任何进展请随时告知我。"),
            ("The feedback from users has been very positive.", "用户反馈非常积极。"),
            ("Let us wrap up the meeting with a quick summary.", "我们用一个简短的总结结束会议。"),
            ("Feel free to reach out if you have questions.", "如果有问题，随时联系我。"),
        ],
    },
    {
        "key": "travel",
        "title": "旅行英语 · 出行必备",
        "level": "初级",
        "desc": "机场、酒店、问路、点餐场景高频句。",
        "items": [
            ("Where can I check in for my flight?", "我在哪里可以办理登机手续？"),
            ("I would like a window seat, please.", "我想要一个靠窗的座位。"),
            ("How much is a ticket to the city center?", "到市中心的票多少钱？"),
            ("Could you show me the way to the museum?", "你能告诉我去博物馆怎么走吗？"),
            ("I have a reservation under the name Wang.", "我有一个王姓的预订。"),
            ("Is breakfast included in the price?", "价格里含早餐吗？"),
            ("Could I have the menu, please?", "请给我菜单好吗？"),
            ("I am allergic to nuts.", "我对坚果过敏。"),
            ("Can I pay by credit card?", "我可以用信用卡付款吗？"),
            ("Where is the nearest subway station?", "最近的地铁站在哪里？"),
            ("How long does it take to get there?", "到那里需要多长时间？"),
            ("I would like to book a room for two nights.", "我想订两晚的房间。"),
            ("Could you take a photo for us?", "你能帮我们拍张照吗？"),
            ("I lost my luggage at the airport.", "我在机场丢了行李。"),
            ("This dish is delicious.", "这道菜很好吃。"),
            ("Please take me to this address.", "请带我去这个地址。"),
            ("Is there a pharmacy nearby?", "附近有药店吗？"),
            ("I need to exchange some money.", "我需要兑换一些钱。"),
        ],
    },
]


def seed():
    """把内置课程写入数据库（已存在则跳过）。"""
    from . import phonics_data

    conn = db.connect()
    exist = {r["builtin_key"] for r in conn.execute("SELECT builtin_key FROM courses").fetchall()}
    conn.close()
    for c in COURSES:
        if c["key"] in exist:
            continue
        cid = db.add_course(c["title"], c["desc"], c["level"], "builtin", c["key"])
        db.add_sentences(cid, c["items"])
    phonics_data.seed()
