# -*- coding: utf-8 -*-
"""外研版《新启航英语》(2024) 一年级 句子课程（可跟读）。

按教材单元主题编写，取材自该教材/同阶段常见的课堂句型与简单对话，
采用一年级可接受的短句（多为 3~7 词），适合「跟读 / 打字 / 选词」练习。
每句格式 (en, zh)。公开源未提供逐单元课文原文，故句式为同主题常见表达。

单元结构：
  上册 Unit1 Hello!  Unit2 Numbers  Unit3 Colours
       Unit4 School things  Unit5 My classroom
  下册 Unit1 Feelings  Unit2 Family  Unit3 Pets
       Unit4 At the farm  Unit5 My room
"""

GROUPS = [
    # ======================= 一年级上册 =======================
    {
        "key": "xqh1a_s1",
        "title": "新启航一上句 · Unit 1 Hello!",
        "level": "入门",
        "desc": "打招呼、自我介绍、道别与礼貌用语。",
        "items": [
            ("Hello!", "你好！"),
            ("Hi, I am Amy.", "嗨，我是埃米。"),
            ("Hello, I am Tom.", "你好，我是汤姆。"),
            ("My name is Lingling.", "我叫玲玲。"),
            ("What is your name?", "你叫什么名字？"),
            ("I am a boy.", "我是个男孩。"),
            ("I am a girl.", "我是个女孩。"),
            ("Nice to meet you.", "很高兴认识你。"),
            ("Nice to meet you, too.", "我也很高兴认识你。"),
            ("How are you?", "你好吗？"),
            ("I am fine, thank you.", "我很好，谢谢你。"),
            ("Good morning!", "早上好！"),
            ("Good afternoon!", "下午好！"),
            ("Goodbye!", "再见！"),
            ("See you tomorrow.", "明天见。"),
            ("This is my friend.", "这是我的朋友。"),
            ("You are my friend.", "你是我的朋友。"),
            ("Yes, I am.", "是的，我是。"),
            ("No, I am not.", "不，我不是。"),
            ("Let us be friends.", "我们做朋友吧。"),
        ],
    },
    {
        "key": "xqh1a_s2",
        "title": "新启航一上句 · Unit 2 Numbers",
        "level": "入门",
        "desc": "数字 1~10 与「有多少」的问句。",
        "items": [
            ("One, two, three!", "一、二、三！"),
            ("I can count to ten.", "我能数到十。"),
            ("Count from one to five.", "从一数到五。"),
            ("How many books?", "有多少本书？"),
            ("I have three books.", "我有三本书。"),
            ("Two little cats.", "两只小猫。"),
            ("Four birds in the sky.", "天上有四只鸟。"),
            ("Five fingers on my hand.", "我手上有五根手指。"),
            ("Six pencils in my bag.", "我书包里有六支铅笔。"),
            ("Seven stars are shining.", "七颗星星在闪。"),
            ("Eight ducks in the water.", "水里有八只鸭子。"),
            ("Nine red apples.", "九个红苹果。"),
            ("Ten children in the class.", "班里有十个孩子。"),
            ("Let us count together.", "我们一起数。"),
            ("What number is it?", "这是数字几？"),
            ("It is number five.", "这是数字五。"),
            ("How old are you?", "你几岁了？"),
            ("I am six years old.", "我六岁了。"),
            ("Give me five!", "击个掌！"),
            ("Numbers are fun.", "数字真有趣。"),
        ],
    },
    {
        "key": "xqh1a_s3",
        "title": "新启航一上句 · Unit 3 Colours",
        "level": "入门",
        "desc": "颜色词汇与「它是什么颜色」的问句。",
        "items": [
            ("What colour is it?", "它是什么颜色？"),
            ("It is red.", "它是红色的。"),
            ("The apple is red.", "苹果是红色的。"),
            ("The sun is yellow.", "太阳是黄色的。"),
            ("The sky is blue.", "天空是蓝色的。"),
            ("The leaves are green.", "叶子是绿色的。"),
            ("I like blue.", "我喜欢蓝色。"),
            ("My favourite colour is pink.", "我最喜欢的颜色是粉色。"),
            ("Look at the rainbow.", "看那道彩虹。"),
            ("It is colourful.", "它五颜六色。"),
            ("A black cat and a white dog.", "一只黑猫和一只白狗。"),
            ("Orange is my favourite.", "橙色是我最喜欢的。"),
            ("The flower is purple.", "这朵花是紫色的。"),
            ("Draw a green tree.", "画一棵绿色的树。"),
            ("Colour the ball red.", "把球涂成红色。"),
            ("Is it yellow?", "它是黄色的吗？"),
            ("Yes, it is.", "是的，它是。"),
            ("No, it is brown.", "不，它是棕色的。"),
            ("Colours are beautiful.", "颜色真美丽。"),
            ("I like this picture.", "我喜欢这幅画。"),
        ],
    },
    {
        "key": "xqh1a_s4",
        "title": "新启航一上句 · Unit 4 School things",
        "level": "入门",
        "desc": "文具词汇与「这是我的…」句型。",
        "items": [
            ("This is my pencil.", "这是我的铅笔。"),
            ("That is your book.", "那是你的书。"),
            ("I have a new pen.", "我有一支新钢笔。"),
            ("Where is my ruler?", "我的尺子在哪里？"),
            ("It is in the bag.", "它在书包里。" ),
            ("Open your book, please.", "请打开你的书。"),
            ("Close your bag, please.", "请合上你的书包。"),
            ("Put the pen on the desk.", "把钢笔放在书桌上。"),
            ("A box of crayons.", "一盒蜡笔。"),
            ("I have a red rubber.", "我有一块红橡皮。"),
            ("Whose pencil is this?", "这是谁的铅笔？"),
            ("It is my pencil case.", "这是我的文具盒。"),
            ("Show me your book.", "给我看看你的书。"),
            ("Give me a ruler, please.", "请给我一把尺子。"),
            ("Is this your pen?", "这是你的钢笔吗？"),
            ("Yes, it is mine.", "是的，它是我的。"),
            ("No, it is not mine.", "不，它不是我的。"),
            ("I have a new schoolbag.", "我有一个新书包。"),
            ("My bag is heavy.", "我的书包很重。"),
            ("Take care of your things.", "要爱惜你的东西。"),
        ],
    },
    {
        "key": "xqh1a_s5",
        "title": "新启航一上句 · Unit 5 My classroom",
        "level": "入门",
        "desc": "教室物品与课堂指令（起立、坐下、看黑板等）。",
        "items": [
            ("This is my classroom.", "这是我的教室。"),
            ("Open the door, please.", "请开门。"),
            ("Close the window, please.", "请关窗。"),
            ("Look at the blackboard.", "看黑板。"),
            ("Listen to me, please.", "请听我说。"),
            ("Read after me.", "跟我读。"),
            ("Sit down, please.", "请坐下。"),
            ("Stand up, please.", "请起立。"),
            ("Be quiet, please.", "请安静。"),
            ("Write your name here.", "在这里写上你的名字。"),
            ("Clean the blackboard.", "擦黑板。"),
            ("Turn on the light.", "开灯。"),
            ("Put up your hand.", "举手。"),
            ("Look at the picture.", "看这幅图。"),
            ("What is on the wall?", "墙上有什么？"),
            ("There are pictures on the wall.", "墙上有画。"),
            ("Hello, everyone!", "大家好！"),
            ("Good job, everyone!", "大家做得好！"),
            ("Let us start our class.", "我们开始上课吧。"),
            ("Class is over.", "下课了。"),
        ],
    },

    # ======================= 一年级下册 =======================
    {
        "key": "xqh1b_s1",
        "title": "新启航一下句 · Unit 1 Feelings",
        "level": "入门",
        "desc": "表达情绪感受：高兴、伤心、饿、渴、冷、热。",
        "items": [
            ("How do you feel today?", "你今天感觉怎么样？"),
            ("I am happy.", "我很高兴。"),
            ("I am very happy today.", "我今天非常高兴。"),
            ("She is sad.", "她很难过。"),
            ("Do not be sad.", "别难过。"),
            ("I am hungry now.", "我现在饿了。"),
            ("I am thirsty.", "我口渴了。"),
            ("It is cold today.", "今天很冷。"),
            ("The soup is hot.", "汤很烫。"),
            ("I am tired.", "我累了。"),
            ("Are you happy?", "你高兴吗？"),
            ("Yes, I am very happy.", "是的，我非常高兴。"),
            ("I love my family.", "我爱我的家人。"),
            ("That is great!", "太棒了！"),
            ("I am sorry.", "对不起。"),
            ("You are welcome.", "不客气。"),
            ("I feel good today.", "我今天感觉很好。"),
            ("The baby is smiling.", "宝宝在笑。"),
            ("Do not cry, please.", "请别哭。"),
            ("Let us laugh together.", "我们一起笑吧。"),
        ],
    },
    {
        "key": "xqh1b_s2",
        "title": "新启航一下句 · Unit 2 Family",
        "level": "入门",
        "desc": "家庭成员与介绍家人的句子。",
        "items": [
            ("This is my family.", "这是我的家庭。"),
            ("This is my mum.", "这是我妈妈。"),
            ("This is my dad.", "这是我爸爸。"),
            ("My mum is a teacher.", "我妈妈是一名老师。"),
            ("My dad is tall.", "我爸爸很高。"),
            ("I have a sister.", "我有一个姐妹。"),
            ("I have a brother.", "我有一个兄弟。"),
            ("This is my grandma.", "这是我奶奶。"),
            ("This is my grandpa.", "这是我爷爷。"),
            ("Grandma tells me stories.", "奶奶给我讲故事。"),
            ("Grandpa is very kind.", "爷爷很和蔼。"),
            ("The baby is sleeping.", "宝宝在睡觉。"),
            ("He is my brother.", "他是我哥哥。"),
            ("She is my sister.", "她是我妹妹。"),
            ("We are a happy family.", "我们是幸福的一家。"),
            ("I love my mum and dad.", "我爱我的爸爸妈妈。"),
            ("How many people are in your family?", "你家有几口人？"),
            ("There are four people.", "有四口人。"),
            ("I go home at five.", "我五点回家。"),
            ("Happy birthday!", "生日快乐！"),
        ],
    },
    {
        "key": "xqh1b_s3",
        "title": "新启航一下句 · Unit 3 Pets",
        "level": "入门",
        "desc": "宠物动物与描述宠物的句子。",
        "items": [
            ("I have a pet.", "我有一只宠物。"),
            ("I have a little cat.", "我有一只小猫。"),
            ("The cat says meow.", "猫喵喵叫。"),
            ("The dog says woof.", "狗汪汪叫。"),
            ("My dog can run fast.", "我的狗跑得快。"),
            ("The rabbit can jump.", "兔子会跳。"),
            ("Fish can swim.", "鱼会游泳。"),
            ("A bird can fly.", "鸟会飞。"),
            ("Look at the little mouse.", "看那只小老鼠。"),
            ("The cat is very cute.", "这只猫很可爱。"),
            ("It has big eyes.", "它有大大的眼睛。"),
            ("It has a long tail.", "它有一条长尾巴。"),
            ("Do you like pets?", "你喜欢宠物吗？"),
            ("Yes, I love animals.", "是的，我喜欢动物。"),
            ("I feed my cat every day.", "我每天喂我的猫。"),
            ("My pet is my friend.", "我的宠物是我的朋友。"),
            ("The dog is sleeping.", "狗在睡觉。"),
            ("The duck can swim.", "鸭子会游泳。"),
            ("What is your pet?", "你的宠物是什么？"),
            ("I want a pet, too.", "我也想要一只宠物。"),
        ],
    },
    {
        "key": "xqh1b_s4",
        "title": "新启航一下句 · Unit 4 At the farm",
        "level": "入门",
        "desc": "农场动物、农作物与农场活动。",
        "items": [
            ("We visit a farm today.", "我们今天去参观农场。"),
            ("The farm is very big.", "这个农场很大。"),
            ("Look at the cows.", "看那些奶牛。"),
            ("The cow gives us milk.", "奶牛给我们牛奶。"),
            ("The pig is pink.", "猪是粉色的。"),
            ("Sheep are white.", "绵羊是白色的。"),
            ("A horse can run fast.", "马跑得很快。"),
            ("A hen lays eggs.", "母鸡下蛋。"),
            ("I see many animals.", "我看见很多动物。"),
            ("How many ducks are there?", "有多少只鸭子？"),
            ("There are ten ducks.", "有十只鸭子。"),
            ("The chicken is small.", "这只鸡很小。"),
            ("I eat an egg for breakfast.", "我早餐吃一个鸡蛋。"),
            ("We eat rice and corn.", "我们吃米饭和玉米。"),
            ("The apples are red.", "苹果是红色的。"),
            ("Bananas are yellow.", "香蕉是黄色的。"),
            ("I like this farm.", "我喜欢这个农场。"),
            ("The farm dog is friendly.", "农场的狗很友好。"),
            ("What sound does the cow make?", "奶牛叫什么声音？"),
            ("Animals are our friends.", "动物是我们的朋友。"),
        ],
    },
    {
        "key": "xqh1b_s5",
        "title": "新启航一下句 · Unit 5 My room",
        "level": "入门",
        "desc": "房间里的事物 + 方位介词 + 睡前用语。",
        "items": [
            ("This is my room.", "这是我的房间。"),
            ("My room is small but nice.", "我的房间不大但很漂亮。"),
            ("The bed is soft.", "床很软。"),
            ("My toys are in the box.", "我的玩具在盒子里。"),
            ("The clock is on the wall.", "钟在墙上。"),
            ("The ball is under the bed.", "球在床下。"),
            ("The cat is behind the door.", "猫在门后。"),
            ("The lamp is near the window.", "台灯在窗户附近。"),
            ("Books are in the bookcase.", "书在书柜里。"),
            ("Where is my toy?", "我的玩具在哪里？"),
            ("It is on the table.", "它在桌子上。"),
            ("I can not find my pen.", "我找不到我的钢笔了。"),
            ("Let us tidy the room.", "我们整理房间吧。"),
            ("Tidy your room, please.", "请整理你的房间。"),
            ("My room is clean now.", "我的房间现在很干净。"),
            ("I sleep at nine.", "我九点睡觉。"),
            ("I wake up at seven.", "我七点醒来。"),
            ("Goodnight, Mum!", "晚安，妈妈！"),
            ("Goodnight, Dad!", "晚安，爸爸！"),
            ("Sweet dreams!", "做个好梦！"),
        ],
    },
]

SENTENCE_COUNT = sum(len(g["items"]) for g in GROUPS)
