# -*- coding: utf-8 -*-
"""小学词汇·第 4 批：出行与交通 / 天气与季节 / 动词与日常用语。"""

GROUPS = [
    {
        "key": "transport",
        "title": "词汇 · 出行与交通",
        "desc": "交通工具、方向与出行方式词汇。",
        "items": [
            ("car", "/kɑː/", "n. 小汽车", "Dad drives a car.", "爸爸开小汽车。", "by car"),
            ("bus", "/bʌs/", "n. 公交车", "The bus is coming.", "公交车来了。", "by bus"),
            ("bike", "/baɪk/", "n. 自行车", "I ride my bike to school.", "我骑车上学。", "by bike"),
            ("train", "/treɪn/", "n. 火车", "The train leaves at eight.", "火车八点出发。", "catch a train"),
            ("plane", "/pleɪn/", "n. 飞机", "The plane flies high.", "飞机飞得很高。", "by plane / by air"),
            ("ship", "/ʃɪp/", "n. 轮船", "The ship sails today.", "轮船今天起航。", "大船"),
            ("boat", "/bəʊt/", "n. 小船", "We row a boat on the lake.", "我们在湖上划船。", "小船"),
            ("taxi", "/ˈtæksi/", "n. 出租车", "Take a taxi, it's late.", "晚了，打车吧。", "by taxi"),
            ("subway", "/ˈsʌbweɪ/", "n. 地铁", "The subway is fast.", "地铁很快。", "英式 underground"),
            ("walk", "/wɔːk/", "v. 步行", "I walk to school.", "我走路去学校。", "on foot 同义"),
            ("run", "/rʌn/", "v. 跑", "He runs faster than me.", "他跑得比我快。", "run-ran-run"),
            ("jump", "/dʒʌmp/", "v. 跳", "The rabbit can jump high.", "兔子跳得高。", "jump into"),
            ("ride", "/raɪd/", "v. 骑", "Can you ride a bike?", "你会骑车吗？", "ride-rode-ridden"),
            ("fly", "/flaɪ/", "v. 飞", "Birds fly south in winter.", "鸟冬天飞往南方。", "fly-flew-flown"),
            ("drive", "/draɪv/", "v. 开车", "Drive slowly near school.", "学校附近开慢点。", "drive-drove-driven"),
            ("go", "/ɡəʊ/", "v. 去", "Let's go home.", "我们回家吧。", "go-went-gone"),
            ("come", "/kʌm/", "v. 来", "Come here, please.", "请过来。", "come-came-come"),
            ("travel", "/ˈtrævl/", "v. 旅行", "We travel by train.", "我们坐火车旅行。", "名词不可数"),
            ("ticket", "/ˈtɪkɪt/", "n. 票", "Two tickets, please.", "请来两张票。", "a ticket for"),
            ("driver", "/ˈdraɪvə/", "n. 司机", "The driver is kind.", "司机很友善。", "drive+r"),
            ("passenger", "/ˈpæsɪndʒə/", "n. 乘客", "Passengers wait here.", "乘客在这里等。", "g 读 /dʒ/"),
            ("left", "/left/", "adj. 左边的", "Turn left at the shop.", "在商店左转。", "on the left"),
            ("right", "/raɪt/", "adj. 右边的", "The bank is on your right.", "银行在你右边。", "双义：正确"),
            ("straight", "/streɪt/", "adv. 直地", "Go straight on.", "直走。", "gh 不发音"),
            ("turn", "/tɜːn/", "v. 转向", "Turn right after the bridge.", "过桥后右转。", "turn left/right"),
            ("near", "/nɪə/", "adj. 近的", "The park is near my home.", "公园在我家附近。", "nearby 附近"),
            ("far", "/fɑː/", "adj. 远的", "Is it far from here?", "离这里远吗？", "far from"),
            ("map", "/mæp/", "n. 地图", "Read the map first.", "先看地图。", "on the map"),
            ("way", "/weɪ/", "n. 路线；方法", "This is the way to school.", "这是去学校的路。", "by the way 顺便"),
            ("stop", "/stɒp/", "v. 停止", "The car stops at the light.", "车在红灯停下。", "stop doing/to do"),
            ("wait", "/weɪt/", "v. 等待", "Wait for me!", "等等我！", "wait for sb"),
            ("arrive", "/əˈraɪv/", "v. 到达", "We arrive in Beijing today.", "我们今天到北京。", "in 大地 at 小地"),
            ("leave", "/liːv/", "v. 离开", "The bus leaves soon.", "车很快就开。", "leave for 出发去"),
            ("carry", "/ˈkæri/", "v. 携带", "I carry a heavy bag.", "我背着个重包。", "复数 carries"),
            ("speed", "/spiːd/", "n. 速度", "The train has high speed.", "火车高速运行。", "high-speed rail"),
        ],
    },
    {
        "key": "weather",
        "title": "词汇 · 天气与季节",
        "desc": "天气现象与四季词汇，学会描述天气。",
        "items": [
            ("weather", "/ˈweðə/", "n. 天气", "The weather is nice today.", "今天天气很好。", "不可数；th 读 /ð/"),
            ("sun", "/sʌn/", "n. 太阳", "The sun is bright.", "太阳很明亮。", "in the sun"),
            ("sunny", "/ˈsʌni/", "adj. 晴朗的", "It is sunny today.", "今天晴天。", "sun→sunny 双写 n"),
            ("rain", "/reɪn/", "n. 雨", "The rain is heavy.", "雨很大。", "rain cats and dogs"),
            ("rainy", "/ˈreɪni/", "adj. 下雨的", "A rainy day again!", "又下雨了！", "rain→rainy"),
            ("cloud", "/klaʊd/", "n. 云", "Look at the white clouds.", "看那些白云。", "复数 clouds"),
            ("cloudy", "/ˈklaʊdi/", "adj. 多云的", "It is cloudy outside.", "外面多云。", "cloud→cloudy"),
            ("wind", "/wɪnd/", "n. 风", "The wind blows hard.", "风很大。", "in the wind"),
            ("windy", "/ˈwɪndi/", "adj. 有风的", "A windy day is good for kites.", "有风的日子适合放风筝。", "wind→windy"),
            ("snow", "/snəʊ/", "n. 雪", "The snow is white and soft.", "雪又白又软。", "也作动词"),
            ("snowy", "/ˈsnəʊi/", "adj. 下雪的", "A snowy winter!", "一个多雪的冬天！", "snow→snowy"),
            ("hot", "/hɒt/", "adj. 热的", "Summer is hot here.", "这里夏天很热。", "与 cold 反义"),
            ("cold", "/kəʊld/", "adj. 冷的", "It is cold in December.", "十二月很冷。", "have a cold 感冒"),
            ("warm", "/wɔːm/", "adj. 温暖的", "Spring is warm.", "春天温暖。", "keep warm"),
            ("cool", "/kuːl/", "adj. 凉爽的", "Autumn is cool.", "秋天凉爽。", "双义：酷"),
            ("ice", "/aɪs/", "n. 冰", "The ice is cold.", "冰很冷。", "ice cream"),
            ("sky", "/skaɪ/", "n. 天空", "The sky is clear tonight.", "今晚天空晴朗。", "in the sky"),
            ("spring", "/sprɪŋ/", "n. 春天", "Flowers come out in spring.", "春天开花。", "in spring"),
            ("summer", "/ˈsʌmə/", "n. 夏天", "We swim in summer.", "我们夏天游泳。", "双 m"),
            ("autumn", "/ˈɔːtəm/", "n. 秋天", "Leaves fall in autumn.", "秋天落叶。", "n 不发音"),
            ("winter", "/ˈwɪntə/", "n. 冬天", "It snows in winter.", "冬天下雪。", "in winter"),
            ("season", "/ˈsiːzn/", "n. 季节", "Spring is my favorite season.", "春天是我最喜欢的季节。", "four seasons"),
            ("storm", "/stɔːm/", "n. 暴风雨", "The storm is coming.", "暴风雨来了。", "thunderstorm 雷雨"),
            ("rainbow", "/ˈreɪnbəʊ/", "n. 彩虹", "A rainbow after rain!", "雨后有彩虹！", "合成词"),
            ("blow", "/bləʊ/", "v. 吹", "The wind blows the leaves.", "风吹动树叶。", "blow-blew-blown"),
        ],
    },
    {
        "key": "verbs",
        "title": "词汇 · 动词与日常用语",
        "desc": "小学核心动词与高频日常表达，句子的发动机。",
        "items": [
            ("be", "/biː/", "v. 是", "I am a pupil.", "我是小学生。", "am/is/are 随人称"),
            ("have", "/hæv/", "v. 有", "I have two books.", "我有两本书。", "he/she 用 has"),
            ("do", "/duː/", "v. 做", "What do you do on Sunday?", "你周日做什么？", "助动词构成问句"),
            ("can", "/kæn/", "aux. 能", "I can swim.", "我会游泳。", "can+动词原形"),
            ("will", "/wɪl/", "aux. 将要", "It will rain tomorrow.", "明天要下雨。", "表将来"),
            ("want", "/wɒnt/", "v. 想要", "I want an ice cream.", "我想要冰淇淋。", "want to do"),
            ("need", "/niːd/", "v. 需要", "We need more time.", "我们需要更多时间。", "need to do"),
            ("make", "/meɪk/", "v. 制作", "Let's make a cake.", "我们做蛋糕吧。", "make-made-made"),
            ("take", "/teɪk/", "v. 拿，带走", "Take this book home.", "把这本书带回家。", "与 bring 相反"),
            ("give", "/ɡɪv/", "v. 给", "Give me the ball, please.", "请把球给我。", "give sb sth"),
            ("get", "/ɡet/", "v. 得到", "I get a letter.", "我收到一封信。", "get up 起床"),
            ("put", "/pʊt/", "v. 放", "Put the toys away.", "把玩具收好。", "过去式同形"),
            ("find", "/faɪnd/", "v. 找到", "I can't find my pen.", "我找不到钢笔。", "find out 查明"),
            ("know", "/nəʊ/", "v. 知道", "I know the answer.", "我知道答案。", "k 不发音"),
            ("think", "/θɪŋk/", "v. 想，认为", "I think you are right.", "我认为你是对的。", "th 咬舌"),
            ("say", "/seɪ/", "v. 说", "Say it again, please.", "请再说一遍。", "say-said"),
            ("speak", "/spiːk/", "v. 说（语言）", "We speak Chinese.", "我们说中文。", "speak to sb"),
            ("tell", "/tel/", "v. 告诉", "Tell me a story.", "给我讲个故事。", "tell sb sth"),
            ("ask", "/ɑːsk/", "v. 问", "Ask the teacher.", "问老师。", "ask sb a question"),
            ("look", "/lʊk/", "v. 看", "Look at the blackboard.", "看黑板。", "look at 过程"),
            ("see", "/siː/", "v. 看见", "I see a bird.", "我看见一只鸟。", "see you 再见"),
            ("watch", "/wɒtʃ/", "v. 观看", "We watch TV at night.", "我们晚上看电视。", "watch TV"),
            ("hear", "/hɪə/", "v. 听见", "I can hear music.", "我能听到音乐。", "hear 结果"),
            ("listen", "/ˈlɪsn/", "v. 听", "Listen to me, please.", "请听我说。", "必须加 to"),
            ("play", "/pleɪ/", "v. 玩，打（球）", "We play football.", "我们踢足球。", "球类不加 the"),
            ("work", "/wɜːk/", "v. 工作", "Dad works in a bank.", "爸爸在银行工作。", "or 读 /ɜː/"),
            ("open", "/ˈəʊpn/", "v. 打开", "Open your books.", "打开书。", "反义 close"),
            ("close", "/kləʊz/", "v. 关闭", "Close the window.", "关窗。", "s 读 /z/"),
            ("buy", "/baɪ/", "v. 买", "I buy fruit every week.", "我每周买水果。", "buy-bought"),
            ("sell", "/sel/", "v. 卖", "The shop sells bread.", "这家店卖面包。", "sell-sold"),
            ("send", "/send/", "v. 发送", "Send me a message.", "给我发消息。", "send-sent"),
            ("bring", "/brɪŋ/", "v. 带来", "Bring your book tomorrow.", "明天带书来。", "与 take 相反"),
            ("wash", "/wɒʃ/", "v. 洗", "Wash your hands.", "洗手。", "a 读 /ɒ/"),
            ("cook", "/kʊk/", "v. 做饭", "Who cooks dinner tonight?", "今晚谁做饭？", "双义：厨师"),
            ("sing", "/sɪŋ/", "v. 唱歌", "She sings well.", "她唱歌好听。", "sing-sang-sung"),
            ("dance", "/dɑːns/", "v. 跳舞", "They dance to music.", "他们随音乐起舞。", "dance to"),
            ("swim", "/swɪm/", "v. 游泳", "Fish can swim.", "鱼会游泳。", "swim-swam-swum"),
            ("climb", "/klaɪm/", "v. 爬", "Climb the mountain carefully.", "小心爬山。", "b 不发音"),
            ("thank", "/θæŋk/", "v. 感谢", "Thank you very much.", "非常感谢。", "thanks 口语"),
            ("please", "/pliːz/", "int. 请", "Please sit down.", "请坐。", "位置灵活"),
            ("sorry", "/ˈsɒri/", "adj. 抱歉的", "I'm sorry I'm late.", "对不起我迟到了。", "be sorry for"),
            ("excuse", "/ɪkˈskjuːz/", "int. 打扰一下", "Excuse me, where's the toilet?", "请问厕所在哪？", "Excuse me 打扰前"),
            ("hello", "/həˈləʊ/", "int. 你好", "Hello, everyone!", "大家好！", "hi 更随意"),
            ("goodbye", "/ˌɡʊdˈbaɪ/", "int. 再见", "Goodbye, class!", "同学们再见！", "bye 口语"),
            ("yes", "/jes/", "int. 是的", "Yes, I can.", "是的，我会。", "of course 当然"),
            ("no", "/nəʊ/", "int. 不", "No, thank you.", "不用了，谢谢。", "No problem"),
            ("great", "/ɡreɪt/", "adj. 太好了", "That's a great idea!", "这个主意太棒了！", "great idea"),
            ("OK", "/ˌəʊˈkeɪ/", "int. 好的", "OK, let's go!", "好的，走吧！", "okay 全拼"),
            ("again", "/əˈɡen/", "adv. 再一次", "Try again!", "再试一次！", "重音在后"),
            ("now", "/naʊ/", "adv. 现在", "It's time to go now.", "现在该走了。", "right now"),
            ("here", "/hɪə/", "adv. 这里", "Come here.", "过来。", "here/there"),
            ("there", "/ðeə/", "adv. 那里", "The book is over there.", "书在那边。", "there be 有"),
            ("very", "/ˈveri/", "adv. 很", "This is very good.", "这非常好。", "只修饰形副"),
            ("too", "/tuː/", "adv. 也；太", "Me too!", "我也是！", "too…to… 太而不能"),
            ("and", "/ænd/", "conj. 和", "Tom and Jerry are friends.", "汤姆和杰瑞是朋友。", "连接并列"),
            ("but", "/bʌt/", "conj. 但是", "He is small but strong.", "他个子小但强壮。", "表转折"),
            ("or", "/ɔː/", "conj. 或者", "Tea or coffee?", "茶还是咖啡？", "表选择"),
            ("because", "/bɪˈkɒz/", "conj. 因为", "I smile because I am happy.", "我笑因为我开心。", "与 so 不同用"),
            ("if", "/ɪf/", "conj. 如果", "If it rains, we stay home.", "如果下雨，我们就待在家。", "主将从现"),
            ("not", "/nɒt/", "adv. 不", "This is not my bag.", "这不是我的书包。", "n't 是缩写"),
            ("all", "/ɔːl/", "det. 全部", "All the best!", "一切顺利！", "all of us"),
            ("some", "/sʌm/", "det. 一些", "I have some questions.", "我有一些问题。", "any 否定疑问"),
            ("many", "/ˈmeni/", "det. 许多", "How many apples?", "多少苹果？", "many+可数"),
            ("more", "/mɔː/", "det. 更多", "I want more ice cream.", "我想要更多冰淇淋。", "more than"),
        ],
    },
]
