# -*- coding: utf-8 -*-
"""小学词汇·第 1 批：数字与时间 / 颜色与形状 / 家人与朋友。

词条格式：(单词, 词性+词义, 例句, 例句中文, 讲解)
由 vocab_primary 合并进课程库，以"单词模式"练习。
"""

GROUPS = [
    {
        "key": "num_time",
        "title": "词汇 · 数字与时间",
        "desc": "数字 1-100、星期、月份与时间表达，小学数学英语双启蒙。",
        "items": [
            ("one", "num. 一", "I have one brother.", "我有一个哥哥。", "one 前可用 a：a one-way road 单行道；one of + 复数：one of my friends"),
            ("two", "num. 二", "Two apples, please.", "请给我两个苹果。", "two 后接复数名词：two books 两本书"),
            ("three", "num. 三", "The book has three pictures.", "这本书有三张图画。", "复数规则：three boys；three 以 th 开头，咬舌音 /θ/"),
            ("four", "num. 四", "There are four seasons.", "一年有四个季节。", "four 与 for、homophone 同音；fourteen 四十别写成 fourty，正确是 forty"),
            ("five", "num. 五", "Give me five!", "击个掌！", "fifth 第五；five 的 ve 变 f 再加 th"),
            ("six", "num. 六", "School starts at six.", "学校六点开始。", "sixteen 16 与 sixty 60 重音不同：SIXteen vs SIXty"),
            ("seven", "num. 七", "I get up at seven.", "我七点起床。", "seventh 第七；seventeen 17 与 seventy 70 重音区别"),
            ("eight", "num. 八", "It is eight o'clock.", "现在是八点钟。", "eight 的 gh 不发音；eighth 第八少发一个 t"),
            ("nine", "num. 九", "Nine cats are sleeping.", "九只猫在睡觉。", "ninth 第九去 e：nine→ninth"),
            ("ten", "num. 十", "I can count to ten.", "我能数到十。", "tenth 第十；ten十位 dozens 无关，dozen 是一打12"),
            ("eleven", "num. 十一", "There are eleven players.", "有十一名队员。", "11-19 都以 -teen 结尾且重音在词尾"),
            ("twelve", "num. 十二", "A year has twelve months.", "一年有十二个月。", "twelfth 第十二 ve→f；a dozen = 12"),
            ("thirteen", "num. 十三", "Thirteen is unlucky for some.", "十三对有些人来说不吉利。", "thir- 不是 three-：13 thir teen / 30 thir ty"),
            ("fourteen", "num. 十四", "She is fourteen years old.", "她十四岁。", "fourteen 14 / forty 40：40 少一个 u"),
            ("fifteen", "num. 十五", "The bus is fifteen minutes late.", "公交车晚了十五分钟。", "fif- 不是 five-：15 fifteen / 50 fifty"),
            ("twenty", "num. 二十", "My grandma is seventy, not twenty!", "我奶奶七十岁，不是二十岁！", "20 21 是 twenty-one；重音在 TWENty"),
            ("thirty", "num. 三十", "Thirty days has September.", "九月有三十天。", "thirty 30 与 thirteen 13 重音位置不同"),
            ("forty", "num. 四十", "Forty students are here.", "四十名学生都到了。", "40 没有 u：forty，不是 fourty"),
            ("fifty", "num. 五十", "The book has fifty pages.", "这本书有五十页。", "50 fifty / 15 fifteen；fifteen 重音在 teen"),
            ("hundred", "num. 百", "The school has five hundred pupils.", "学校有五百名学生。", "hundred 不加 s：five hundred（不是 hundreds）"),
            ("first", "num. 第一", "Today is the first day of school.", "今天是开学第一天。", "序数词前加 the：the first；first floor 英式=一层"),
            ("second", "num. 第二", "This is my second try.", "这是我的第二次尝试。", "second 也是秒：one second 一秒"),
            ("third", "num. 第三", "He came third in the race.", "他赛跑了第三名。", "three→third 不规则"),
            ("Monday", "n. 星期一", "We start school on Monday.", "我们星期一开学。", "星期首字母大写；on Monday 在星期一"),
            ("Tuesday", "n. 星期二", "I have music on Tuesday.", "我星期二有音乐课。", "Tue 读 /tjuː/；on Tuesdays 每周二"),
            ("Wednesday", "n. 星期三", "Wednesday is my busy day.", "星期三是我忙的一天。", "发音 /ˈwenzdeɪ/，首字母 W 不发音！"),
            ("Thursday", "n. 星期四", "The test is on Thursday.", "考试在星期四。", "th 咬舌音；Thursday 紧跟 Friday 前"),
            ("Friday", "n. 星期五", "We play games on Friday.", "我们星期五做游戏。", "on Friday afternoon 在周五下午"),
            ("Saturday", "n. 星期六", "No school on Saturday.", "星期六不上学。", "weekend 周末=Saturday+Sunday"),
            ("Sunday", "n. 星期日", "I visit grandma on Sunday.", "我周日去看奶奶。", "on Sundays 每个周日"),
            ("week", "n. 星期，周", "A week has seven days.", "一周有七天。", "this/last/next week 直接用，不加介词"),
            ("month", "n. 月份", "June is my favorite month.", "六月是我最喜欢的月份。", "th 读 /θ/；monthly 每月的"),
            ("year", "n. 年", "Happy New Year!", "新年快乐！", "this year 今年（不加介词）；year 变复数 years"),
            ("morning", "n. 早晨", "Good morning, class!", "同学们早上好！", "in the morning 固定搭配"),
            ("afternoon", "n. 下午", "See you in the afternoon.", "下午见。", "this afternoon 直接用不加 in"),
            ("evening", "n. 傍晚", "We watch TV in the evening.", "我们晚上看电视。", "in the evening；night 对应 at night"),
            ("day", "n. 天，日子", "What a nice day!", "多好的一天！", "every day 每天（分开写）；everyday 是形容词日常的"),
            ("night", "n. 夜晚", "Good night, Mum.", "晚安，妈妈。", "at night 在夜里；good night 是告别用语"),
            ("today", "adv. 今天", "Today is Monday.", "今天是星期一。", "today 前不加介词，直接说 today"),
            ("tomorrow", "adv. 明天", "Tomorrow is my birthday.", "明天是我生日。", "tomorrow 前同样不加介词"),
            ("yesterday", "adv. 昨天", "It rained yesterday.", "昨天下雨了。", "yesterday 常搭配过去时"),
            ("time", "n. 时间", "What time is it?", "现在几点了？", "It's time to + 动词；time 不可数时指时间"),
            ("o'clock", "adv. …点钟", "It is seven o'clock.", "现在七点整。", "只用于整点：seven o'clock，不用于几点几分"),
            ("half", "n. 一半", "It is half past six.", "现在六点半。", "half past + 小时 = 几点半"),
            ("birthday", "n. 生日", "Happy birthday to you!", "祝你生日快乐！", "birthday cake 生日蛋糕；on my birthday 在我生日那天"),
            ("hour", "n. 小时", "We play for one hour.", "我们玩一个小时。", "h 不发音：/ˈaʊə/；an hour 不是 a hour！"),
            ("minute", "n. 分钟", "Wait a minute, please.", "请等一分钟。", "just a minute 稍等一下"),
        ],
    },
    {
        "key": "color_shape",
        "title": "词汇 · 颜色与形状",
        "desc": "颜色、形状与外观描述词汇，美术与美术课英语。",
        "items": [
            ("red", "adj. 红色的", "The apple is red.", "这个苹果是红色的。", "in red 穿红衣服：The girl in red"),
            ("blue", "adj. 蓝色的", "The sky is blue today.", "今天天空是蓝色的。", "blue 也表示忧伤：feel blue"),
            ("yellow", "adj. 黄色的", "The sun looks yellow.", "太阳看起来是黄色的。", "yellow light 黄灯"),
            ("green", "adj. 绿色的", "The leaves are green in summer.", "夏天树叶是绿色的。", "green tea 绿茶；Greens 姓氏一家人"),
            ("black", "adj. 黑色的", "I have a black pen.", "我有一支黑色的钢笔。", "black tea 红茶（不是黑茶）"),
            ("white", "adj. 白色的", "The snow is white.", "雪是白色的。", "White House 白宫；white 不需要变位"),
            ("brown", "adj. 棕色的", "The bear is brown.", "这只熊是棕色的。", "brown bread 黑面包"),
            ("pink", "adj. 粉色的", "Her dress is pink.", "她的裙子是粉色的。", "pink in the face 脸红"),
            ("purple", "adj. 紫色的", "I like purple flowers.", "我喜欢紫色的花。", "purple 与 people 押韵记忆"),
            ("orange", "adj. 橙色的", "The juice is orange.", "这果汁是橙色的。", "orange 既指橙色又指橙子"),
            ("grey", "adj. 灰色的", "The cat is grey and white.", "这只猫是灰白相间的。", "美式拼写 gray"),
            ("colour", "n. 颜色", "What colour is your bag?", "你的书包是什么颜色的？", "美式拼写 color；What colour…? 问颜色"),
            ("light", "adj. 浅色的", "This is light blue.", "这是浅蓝色。", "light blue 浅蓝 / dark blue 深蓝"),
            ("dark", "adj. 深色的，黑暗的", "It gets dark at night.", "夜里天变黑。", "get dark 天变黑；dark green 深绿"),
            ("circle", "n. 圆形", "Draw a circle, please.", "请画一个圆。", "circle 读音 /ˈsɜːkl/；a circle 一个圆"),
            ("square", "n. 正方形", "A square has four sides.", "正方形有四条边。", "square 也是广场：Tian'anmen Square"),
            ("triangle", "n. 三角形", "A triangle has three sides.", "三角形有三条边。", "tri- 表示三：triangle, tricycle"),
            ("star", "n. 星形，星星", "The flag has five stars.", "这面旗有五颗星。", "star 形状与天上的星星同词"),
            ("heart", "n. 心形，心脏", "She drew a red heart.", "她画了一个红心。", "by heart 用心记住：learn by heart"),
            ("shape", "n. 形状", "What shape is the ball?", "球是什么形状的？", "a round shape 圆形；shapes 形状总称"),
            ("same", "adj. 相同的", "We are in the same class.", "我们在同一个班。", "the same 必须加 the；same as 与…一样"),
            ("different", "adj. 不同的", "We have different ideas.", "我们有不同的想法。", "be different from 与…不同"),
            ("new", "adj. 新的", "This is my new schoolbag.", "这是我的新书包。", "new news 新闻（不可数）"),
            ("old", "adj. 旧的，老的", "My bike is old but fast.", "我的自行车旧但快。", "old 既指旧物也指年长"),
            ("long", "adj. 长的", "The river is very long.", "这条河很长。", "how long 问长度或时长"),
            ("short", "adj. 短的，矮的", "The pencil is short now.", "这支铅笔现在很短了。", "short 既指短也指矮"),
            ("big", "adj. 大的", "The elephant is big.", "大象很大。", "big 与 little 反义；large 更书面"),
            ("small", "adj. 小的", "A small mouse ran by.", "一只小老鼠跑过。", "small 与 big 反义；little 更口语"),
            ("tall", "adj. 高的", "My father is tall.", "我爸爸个子高。", "问身高用 how tall"),
            ("beautiful", "adj. 美丽的", "What a beautiful garden!", "多美的花园啊！", "more beautiful 双音节以上加 more"),
            ("pretty", "adj. 漂亮的", "The flower is pretty.", "这朵花很漂亮。", "pretty 也作副词：pretty good 相当好"),
            ("clean", "adj. 干净的", "Keep the room clean.", "保持房间干净。", "clean 既可作形容词也可作动词打扫"),
            ("dirty", "adj. 脏的", "My hands are dirty.", "我的手脏了。", "wash dirty hands 洗脏手"),
            ("round", "adj. 圆的", "The ball is round.", "球是圆的。", "all year round 一年到头"),
        ],
    },
    {
        "key": "family",
        "title": "词汇 · 家人与朋友",
        "desc": "家庭成员、称呼与人际交往词汇。",
        "items": [
            ("family", "n. 家庭", "My family is big.", "我的家庭很大。", "family 作整体用单数动词；family tree 家谱"),
            ("father", "n. 爸爸", "My father is a doctor.", "我爸爸是医生。", "dad 是口语；Father's Day 父亲节"),
            ("mother", "n. 妈妈", "Mother cooks well.", "妈妈做饭好吃。", "mum/mom 是口语；Mother's Day 母亲节"),
            ("parent", "n. 父母", "My parents love me.", "我的父母爱我。", "parents 一定是复数才指双亲"),
            ("grandfather", "n. 爷爷；外公", "Grandfather tells stories.", "爷爷讲故事。", "grand- 表示隔代"),
            ("grandmother", "n. 奶奶；外婆", "Grandmother makes cakes.", "奶奶做蛋糕。", "grandma 是口语简称"),
            ("grandparent", "n. 祖父母", "We visit our grandparents.", "我们去看望祖父母。", "grandparents 指爷爷奶奶外公外婆统称"),
            ("brother", "n. 兄弟", "My brother is younger.", "我弟弟年纪更小。", "elder brother 哥哥 / younger brother 弟弟"),
            ("sister", "n. 姐妹", "My sister is six.", "我妹妹六岁。", "sister 可指姐姐或妹妹"),
            ("uncle", "n. 叔叔；舅舅", "Uncle Wang lives nearby.", "王叔叔住在附近。", "uncle 前加称呼时大写"),
            ("aunt", "n. 姑姑；阿姨", "Aunt Li is a nurse.", "李阿姨是护士。", "aunt 读 /ɑːnt/"),
            ("cousin", "n. 堂/表兄弟姐妹", "My cousin is my best friend.", "我表哥是我最好的朋友。", "cousin 不分男女，通称表亲"),
            ("friend", "n. 朋友", "She is my good friend.", "她是我的好朋友。", "make friends 交朋友（用复数）"),
            ("boy", "n. 男孩", "The boy runs fast.", "这个男孩跑得快。", "boys 复数直接加 s"),
            ("girl", "n. 女孩", "The girl sings well.", "这个女孩唱歌好听。", "girlfriend 与 boyfriend 要区分语境"),
            ("baby", "n. 婴儿", "The baby is sleeping.", "婴儿在睡觉。", "复数 babies（y 变 ies）"),
            ("child", "n. 孩子", "The child is playing.", "孩子在玩。", "复数特殊：children"),
            ("children", "n. 孩子们", "Children like games.", "孩子们喜欢游戏。", "child 的复数，不加 s！"),
            ("people", "n. 人们", "Many people are here.", "很多人在这里。", "people 本身是复数概念"),
            ("man", "n. 男人", "That man is my teacher.", "那个男人是我的老师。", "复数 men（a 变 e）"),
            ("woman", "n. 女人", "The woman is kind.", "这位女士很善良。", "复数 women /ˈwɪmɪn/"),
            ("name", "n. 名字", "My name is Li Hua.", "我的名字叫李华。", "first name 名 / last name 姓"),
            ("Mr", "n. 先生", "This is Mr Brown.", "这是布朗先生。", "Mr+姓：Mr Smith；英式不加点"),
            ("Mrs", "n. 夫人", "Mrs Green teaches us.", "格林夫人教我们。", "Mrs 用于已婚女性"),
            ("love", "v. 爱", "I love my family.", "我爱我的家人。", "love doing 喜欢做；love you 口语常省主语"),
            ("help", "v. 帮助", "Can you help me?", "你能帮我吗？", "help sb do sth 帮某人做事"),
            ("visit", "v. 拜访", "We visit grandma on Sunday.", "我们周日去看奶奶。", "visit + 地点/人直接接宾语"),
            ("call", "v. 叫，打电话", "Call me at six.", "六点给我打电话。", "call sb names 不是叫名字，是骂人！"),
            ("meet", "v. 见面", "Nice to meet you.", "很高兴认识你。", "meet 首次见面；meet up 约见"),
            ("welcome", "int. 欢迎", "Welcome to our school!", "欢迎来我们学校！", "welcome to + 地点；You're welcome 不客气"),
            ("together", "adv. 一起", "Let's play together.", "我们一起玩吧。", "together 不可拆：go together 同行"),
            ("neighbour", "n. 邻居", "Our neighbour has a dog.", "我们的邻居养了只狗。", "美式拼写 neighbor"),
            ("classmate", "n. 同学", "He is my classmate.", "他是我的同学。", "classmate = class+mate"),
            ("twin", "n. 双胞胎", "They are twins.", "他们是双胞胎。", "twins 复数常用于双胞胎二人"),
            ("family tree", "n. 家谱", "I drew my family tree.", "我画了家谱。", "tree 这里比喻分支关系"),
            ("home", "n. 家", "I go home at four.", "我四点回家。", "go home 不加 to！at home 在家"),
            ("live", "v. 居住", "I live in Beijing.", "我住在北京。", "live in + 城市；live with sb 与某人同住"),
            ("share", "v. 分享", "We share an umbrella.", "我们合用一把伞。", "share sth with sb 与某人分享"),
            ("care", "v. 关心", "Mum cares for us.", "妈妈照顾我们。", "care about 在乎；take care 保重"),
            ("like", "v. 喜欢", "I like my school.", "我喜欢我的学校。", "like doing/to do 都可以；would like 想要"),
        ],
    },
]
