# -*- coding: utf-8 -*-
"""小学词汇·第 2 批：学校与学习 / 身体与健康 / 动物。"""

GROUPS = [
    {
        "key": "school",
        "title": "词汇 · 学校与学习",
        "desc": "文具、学科、课堂与校园场所，小学生最高频词汇。",
        "items": [
            ("school", "/skuːl/", "n. 学校", "I go to school by bus.", "我坐公交上学。", "go to school 不加 the"),
            ("class", "/klɑːs/", "n. 班级，课", "We are in Class Two.", "我们在二班。", "have a class 上课"),
            ("classroom", "/ˈklɑːsruːm/", "n. 教室", "Our classroom is clean.", "我们的教室很干净。", "合成词"),
            ("teacher", "/ˈtiːtʃə/", "n. 老师", "My teacher is very kind.", "我的老师很和蔼。", "teach+er"),
            ("student", "/ˈstjuːdnt/", "n. 学生", "She is a good student.", "她是个好学生。", "pupil 更英式"),
            ("desk", "/desk/", "n. 书桌", "Put your book on the desk.", "把书放到桌上。", "书桌与 table 餐桌"),
            ("chair", "/tʃeə/", "n. 椅子", "This chair is broken.", "这把椅子坏了。", "sit on a chair"),
            ("blackboard", "/ˈblækbɔːd/", "n. 黑板", "Look at the blackboard.", "看黑板。", "别忘了 the"),
            ("book", "/bʊk/", "n. 书", "This book is interesting.", "这本书很有趣。", "oo 短音 /ʊ/"),
            ("pen", "/pen/", "n. 钢笔", "May I borrow your pen?", "能借你的钢笔吗？", "pen friend 笔友"),
            ("pencil", "/ˈpensl/", "n. 铅笔", "I draw with a pencil.", "我用铅笔画图。", "pencil case 笔袋"),
            ("ruler", "/ˈruːlə/", "n. 尺子", "Draw a line with your ruler.", "用尺子画条线。", "rule+er"),
            ("eraser", "/ɪˈreɪzə/", "n. 橡皮", "My eraser is missing.", "我的橡皮不见了。", "重音在 rai-"),
            ("bag", "/bæɡ/", "n. 包，书包", "My bag is heavy.", "我的书包很重。", "a 短音 /æ/"),
            ("homework", "/ˈhəʊmwɜːk/", "n. 作业", "I do my homework after dinner.", "我晚饭后写作业。", "不可数"),
            ("lesson", "/ˈlesn/", "n. 功课，一节课", "Today's lesson is fun.", "今天的课很有趣。", "son 读 /sn/"),
            ("subject", "/ˈsʌbdʒɪkt/", "n. 科目", "Maths is my favorite subject.", "数学是我最喜欢的科目。", "bj 连读"),
            ("English", "/ˈɪŋɡlɪʃ/", "n. 英语", "We speak English in class.", "课上我们说英语。", "首字母大写"),
            ("Chinese", "/ˌtʃaɪˈniːz/", "n. 语文；中文", "I like Chinese best.", "我最喜欢语文。", "重音在后"),
            ("maths", "/mæθs/", "n. 数学", "I am good at maths.", "我数学很好。", "美式 math"),
            ("science", "/ˈsaɪəns/", "n. 科学", "We do experiments in science.", "科学课我们做实验。", "cie 读 /aɪəns/"),
            ("music", "/ˈmjuːzɪk/", "n. 音乐", "Music makes me happy.", "音乐让我快乐。", "listen to music"),
            ("art", "/ɑːt/", "n. 美术", "We paint in art class.", "美术课我们画画。", "不可数"),
            ("computer", "/kəmˈpjuːtə/", "n. 电脑", "The computer is on the desk.", "电脑在桌上。", "重音在 pu-"),
            ("library", "/ˈlaɪbrəri/", "n. 图书馆", "We read in the library.", "我们在图书馆看书。", "复数 libraries"),
            ("playground", "/ˈpleɪɡraʊnd/", "n. 操场", "The children are on the playground.", "孩子们在操场上。", "用 on"),
            ("read", "/riːd/", "v. 读", "I read a book every night.", "我每晚读一本书。", "过去式同形读 /red/"),
            ("write", "/raɪt/", "v. 写", "Write your name here.", "在这里写你的名字。", "w 不发音"),
            ("draw", "/drɔː/", "v. 画", "Can you draw a cat?", "你会画猫吗？", "draw 线条画"),
            ("learn", "/lɜːn/", "v. 学习", "We learn English at school.", "我们在学校学英语。", "learn from"),
            ("spell", "/spel/", "v. 拼写", "How do you spell 'banana'?", "banana 怎么拼？", "spell out"),
            ("study", "/ˈstʌdi/", "v. 学习", "I study hard for the test.", "我为考试努力学习。", "复数 studies"),
            ("answer", "/ˈɑːnsə/", "n. 答案", "The answer is right.", "答案是对的。", "w 不发音"),
            ("question", "/ˈkwestʃən/", "n. 问题", "Ask questions if you don't know.", "不懂就提问。", "ask a question"),
            ("test", "/test/", "n. 测验", "We have a test today.", "我们今天有测验。", "have a test"),
            ("exam", "/ɪɡˈzæm/", "n. 考试", "The final exam is in June.", "期末考试在六月。", "重音在后"),
            ("pupil", "/ˈpjuːpl/", "n. 小学生", "The pupils line up.", "小学生们排队。", "pu 读 /pjuː/"),
            ("flag", "/flæɡ/", "n. 旗子", "We raise the flag on Monday.", "我们周一升旗。", "national flag"),
            ("duty", "/ˈdjuːti/", "n. 值日", "It's my duty today.", "今天我值日。", "on duty"),
            ("bell", "/bel/", "n. 铃", "The bell is ringing.", "铃在响。", "ring the bell"),
            ("exercise", "/ˈeksəsaɪz/", "n. 练习，运动", "Eye exercises are good for you.", "眼保健操对你有好处。", "重音在 ex-"),
            ("word", "/wɜːd/", "n. 单词", "Learn five new words a day.", "一天学五个新单词。", "or 读 /ɜː/"),
            ("sentence", "/ˈsentəns/", "n. 句子", "Make a sentence with this word.", "用这个词造个句子。", "make sentences"),
            ("letter", "/ˈletə/", "n. 字母；信", "A comes before B in letters.", "字母表里 A 在 B 前。", "双义"),
            ("page", "/peɪdʒ/", "n. 页", "Open your book to page ten.", "打开书第十页。", "g 读 /dʒ/"),
        ],
    },
    {
        "key": "body_health",
        "title": "词汇 · 身体与健康",
        "desc": "身体部位、健康与就医词汇，学会描述自己。",
        "items": [
            ("head", "/hed/", "n. 头", "Shake your head.", "摇摇头。", "headache 头疼"),
            ("face", "/feɪs/", "n. 脸", "Wash your face, please.", "请洗脸。", "face to face"),
            ("eye", "/aɪ/", "n. 眼睛", "Her eyes are big.", "她的眼睛很大。", "单复数同音"),
            ("ear", "/ɪə/", "n. 耳朵", "I hear with my ears.", "我用耳朵听。", "与 year 押韵"),
            ("nose", "/nəʊz/", "n. 鼻子", "The clown has a red nose.", "小丑有个红鼻子。", "与 rose 押韵"),
            ("mouth", "/maʊθ/", "n. 嘴", "Open your mouth.", "张开嘴。", "与 month 区分"),
            ("hair", "/heə/", "n. 头发", "She has long hair.", "她留长发。", "不可数"),
            ("arm", "/ɑːm/", "n. 手臂", "Raise your arm.", "举起手臂。", "arm in arm"),
            ("hand", "/hænd/", "n. 手", "Give me your hand.", "把你的手给我。", "hand in hand"),
            ("finger", "/ˈfɪŋɡə/", "n. 手指", "I have ten fingers.", "我有十根手指。", "thumb 大拇指"),
            ("leg", "/leɡ/", "n. 腿", "My legs are tired.", "我的腿累了。", "e 短音"),
            ("foot", "/fʊt/", "n. 脚", "My left foot hurts.", "我左脚疼。", "复数 feet"),
            ("feet", "/fiːt/", "n. 双脚", "Wash your feet before bed.", "睡前洗脚。", "foot 的复数"),
            ("knee", "/niː/", "n. 膝盖", "I hurt my knee.", "我伤了膝盖。", "k 不发音"),
            ("tooth", "/tuːθ/", "n. 牙齿", "Brush your tooth carefully.", "仔细刷牙。", "复数 teeth"),
            ("teeth", "/tiːθ/", "n. 牙齿（复数）", "The baby has no teeth yet.", "宝宝还没长牙。", "oo→ee"),
            ("body", "/ˈbɒdi/", "n. 身体", "Exercise is good for the body.", "锻炼对身体好。", "复数 bodies"),
            ("healthy", "/ˈhelθi/", "adj. 健康的", "Vegetables are healthy.", "蔬菜有益健康。", "stay healthy"),
            ("ill", "/ɪl/", "adj. 生病的", "He is ill today.", "他今天生病了。", "be ill"),
            ("sick", "/sɪk/", "adj. 恶心的，生病的", "I feel sick.", "我感到恶心。", "feel sick"),
            ("hurt", "/hɜːt/", "v. 疼；受伤", "Does it hurt?", "疼吗？", "过去式同形"),
            ("doctor", "/ˈdɒktə/", "n. 医生", "The doctor helps people.", "医生帮助人。", "see a doctor"),
            ("nurse", "/nɜːs/", "n. 护士", "The nurse is gentle.", "护士很温柔。", "ur 读 /ɜː/"),
            ("hospital", "/ˈhɒspɪtl/", "n. 医院", "Grandpa is in hospital.", "爷爷住院了。", "in hospital"),
            ("medicine", "/ˈmedsn/", "n. 药", "Take the medicine three times a day.", "一天吃三次药。", "take medicine"),
            ("cold", "/kəʊld/", "n. 感冒", "I have a cold.", "我感冒了。", "catch a cold"),
            ("fever", "/ˈfiːvə/", "n. 发烧", "The boy has a fever.", "这个男孩发烧了。", "have a fever"),
            ("headache", "/ˈhedeɪk/", "n. 头疼", "I have a headache.", "我头疼。", "head+ache"),
            ("toothache", "/ˈtuːθeɪk/", "n. 牙疼", "Too much candy gives you toothache.", "糖吃多了牙疼。", "tooth+ache"),
            ("fine", "/faɪn/", "adj. 很好的", "I'm fine, thank you.", "我很好，谢谢。", "问候回复"),
            ("better", "/ˈbetə/", "adj. 更好的", "I feel better now.", "我现在好多了。", "well 的比较级"),
            ("rest", "/rest/", "n. 休息", "You need a good rest.", "你需要好好休息。", "have a rest"),
            ("sleep", "/sliːp/", "v. 睡觉", "Children need ten hours' sleep.", "孩子需要十小时睡眠。", "ee 长音"),
            ("wash", "/wɒʃ/", "v. 洗", "Wash your hands before eating.", "饭前洗手。", "a 读 /ɒ/"),
            ("brush", "/brʌʃ/", "v. 刷", "Brush your teeth twice a day.", "一天刷两次牙。", "sh 读 /ʃ/"),
            ("tired", "/ˈtaɪəd/", "adj. 累的", "I am tired after running.", "跑步后我累了。", "be tired of"),
            ("strong", "/strɒŋ/", "adj. 强壮的", "Milk makes you strong.", "牛奶让你强壮。", "ng 读 /ŋ/"),
            ("clean", "/kliːn/", "v. 打扫", "We clean the classroom after school.", "放学后我们打扫教室。", "clean up"),
            ("smile", "/smaɪl/", "v. 微笑", "The teacher smiles at us.", "老师朝我们微笑。", "smile at sb"),
        ],
    },
    {
        "key": "animal",
        "title": "词汇 · 动物",
        "desc": "常见动物名称与特征描述，动物园主题词汇。",
        "items": [
            ("animal", "/ˈænɪml/", "n. 动物", "Pandas are my favorite animals.", "熊猫是我最喜欢的动物。", "重音在前"),
            ("cat", "/kæt/", "n. 猫", "The cat is on the sofa.", "猫在沙发上。", "copy cat 模仿者"),
            ("dog", "/dɒɡ/", "n. 狗", "My dog can fetch.", "我的狗会捡东西。", "lucky dog 幸运儿"),
            ("bird", "/bɜːd/", "n. 鸟", "Birds fly in the sky.", "鸟在天上飞。", "early bird 早起的人"),
            ("fish", "/fɪʃ/", "n. 鱼", "Fish swim in water.", "鱼在水里游。", "单复数同形"),
            ("rabbit", "/ˈræbɪt/", "n. 兔子", "The rabbit has long ears.", "兔子有长耳朵。", "双写 b"),
            ("duck", "/dʌk/", "n. 鸭子", "Ducks swim in the pond.", "鸭子在池塘游泳。", "双义：躲闪"),
            ("chicken", "/ˈtʃɪkɪn/", "n. 小鸡；鸡肉", "We had chicken for lunch.", "我们午饭吃鸡肉。", "鸡肉不可数"),
            ("hen", "/hen/", "n. 母鸡", "The hen lays eggs.", "母鸡下蛋。", "只指母鸡"),
            ("pig", "/pɪɡ/", "n. 猪", "Pigs are pink.", "猪是粉色的。", "i 短音"),
            ("cow", "/kaʊ/", "n. 奶牛", "Cows give us milk.", "奶牛给我们牛奶。", "ow 读 /aʊ/"),
            ("sheep", "/ʃiːp/", "n. 绵羊", "The sheep eat grass.", "绵羊吃草。", "单复数同形"),
            ("horse", "/hɔːs/", "n. 马", "I can ride a horse.", "我会骑马。", "ride a horse"),
            ("monkey", "/ˈmʌŋki/", "n. 猴子", "Monkeys love bananas.", "猴子爱香蕉。", "复数 monkeys"),
            ("tiger", "/ˈtaɪɡə/", "n. 老虎", "The tiger has stripes.", "老虎有条纹。", "重音在前"),
            ("lion", "/ˈlaɪən/", "n. 狮子", "The lion is the king.", "狮子是百兽之王。", "重音在前"),
            ("elephant", "/ˈelɪfənt/", "n. 大象", "An elephant is very big.", "大象非常大。", "用 an"),
            ("bear", "/beə/", "n. 熊", "The bear sleeps in winter.", "熊冬天冬眠。", "双义：忍受"),
            ("panda", "/ˈpændə/", "n. 熊猫", "Pandas live in China.", "熊猫生活在中国。", "giant panda"),
            ("zebra", "/ˈzebrə/", "n. 斑马", "Zebras have black and white stripes.", "斑马有黑白条纹。", "zebra crossing 斑马线"),
            ("giraffe", "/dʒəˈrɑːf/", "n. 长颈鹿", "The giraffe has a long neck.", "长颈鹿脖子长。", "g 读 /dʒ/"),
            ("snake", "/sneɪk/", "n. 蛇", "A snake has no legs.", "蛇没有腿。", "sn- 连读"),
            ("mouse", "/maʊs/", "n. 老鼠", "The mouse is afraid of cats.", "老鼠怕猫。", "复数 mice"),
            ("frog", "/frɒɡ/", "n. 青蛙", "Frogs can jump far.", "青蛙跳得远。", "o 短音"),
            ("bee", "/biː/", "n. 蜜蜂", "Bees make honey.", "蜜蜂酿蜜。", "as busy as a bee"),
            ("butterfly", "/ˈbʌtəflaɪ/", "n. 蝴蝶", "The butterfly has pretty wings.", "蝴蝶有漂亮的翅膀。", "复数 butterflies"),
            ("egg", "/eɡ/", "n. 蛋", "The hen lays an egg.", "母鸡下了一个蛋。", "用 an"),
            ("tail", "/teɪl/", "n. 尾巴", "The dog wags its tail.", "狗摇尾巴。", "ai 双元音"),
            ("wing", "/wɪŋ/", "n. 翅膀", "Birds have two wings.", "鸟有两只翅膀。", "ng 读 /ŋ/"),
            ("zoo", "/zuː/", "n. 动物园", "We see lions at the zoo.", "我们在动物园看狮子。", "at the zoo"),
            ("farm", "/fɑːm/", "n. 农场", "There are many animals on the farm.", "农场有很多动物。", "on the farm"),
            ("forest", "/ˈfɒrɪst/", "n. 森林", "Bears live in the forest.", "熊住在森林里。", "重音在前"),
            ("feed", "/fiːd/", "v. 喂", "Don't feed the animals.", "不要投喂动物。", "feed on"),
            ("pet", "/pet/", "n. 宠物", "My pet is a rabbit.", "我的宠物是兔子。", "keep a pet"),
            ("cage", "/keɪdʒ/", "n. 笼子", "The bird is in a cage.", "鸟在笼子里。", "g 读 /dʒ/"),
            ("hunt", "/hʌnt/", "v. 捕猎", "Lions hunt at night.", "狮子夜间捕猎。", "hunt for"),
            ("wild", "/waɪld/", "adj. 野生的", "Wild animals need care.", "野生动物需要保护。", "wild animal"),
            ("fast", "/fɑːst/", "adj. 快的", "The cheetah runs fast.", "猎豹跑得快。", "形副同形"),
            ("slow", "/sləʊ/", "adj. 慢的", "The turtle is slow.", "乌龟很慢。", "slow down 减速"),
            ("cute", "/kjuːt/", "adj. 可爱的", "What a cute puppy!", "多可爱的小狗！", "cu 读 /kjuː/"),
            ("dangerous", "/ˈdeɪndʒərəs/", "adj. 危险的", "Some snakes are dangerous.", "有些蛇很危险。", "g 读 /dʒ/"),
            ("safe", "/seɪf/", "adj. 安全的", "The cage keeps us safe.", "笼子保证我们安全。", "safe and sound"),
        ],
    },
]
