# -*- coding: utf-8 -*-
"""外研版《新启航英语》(2024) 一年级上册 / 下册 词汇课。

按教材官方单元结构分课（上册 5 单元、下册 5 单元），每单元一课。
词汇以教材已公布的必背词为主，并补充同主题适合一年级的常见词与简单句型，
每词格式同其它词汇课：(word, ipa, zh, ex, ex_zh, tip)。

单元结构（外研社教师用书目录）：
  上册  Unit1 Hello!            Unit2 Numbers        Unit3 Colours
        Unit4 School things     Unit5 My classroom
  下册  Unit1 Feelings          Unit2 Family         Unit3 Pets
        Unit4 At the farm       Unit5 My room
"""

GROUPS = [
    # ======================= 一年级上册 =======================
    {
        "key": "xqh1a_u1",
        "title": "新启航一上 · Unit 1 Hello!",
        "desc": "问候与自我介绍：hello / name / 数字 1~3 等入门词。",
        "items": [
            ("hello", "/həˈləʊ/", "int. 你好", "Hello! I am Amy.", "你好！我是埃米。", "见面打招呼最常用"),
            ("hi", "/haɪ/", "int. 嗨；你好", "Hi! Nice to see you.", "嗨！见到你很高兴。", "比 hello 更随意"),
            ("name", "/neɪm/", "n. 名字", "My name is Tom.", "我叫汤姆。", "What's your name? 你叫什么名字？"),
            ("I", "/aɪ/", "pron. 我", "I am a pupil.", "我是一名小学生。", "be 动词用 am"),
            ("am", "/æm/", "v. 是（be 动词）", "I am happy.", "我很开心。", "只和 I 连用"),
            ("you", "/juː/", "pron. 你；你们", "Are you Lingling?", "你是玲玲吗？", "你是 you，我是 I"),
            ("my", "/maɪ/", "pron. 我的", "This is my book.", "这是我的书。", "后面跟名词"),
            ("your", "/jɔː/", "pron. 你的", "What's your name?", "你叫什么名字？", "your + 名词"),
            ("goodbye", "/ˌɡʊdˈbaɪ/", "int. 再见", "Goodbye, Miss Li!", "再见，李老师！", "＝ bye"),
            ("bye", "/baɪ/", "int. 再见", "Bye! See you tomorrow.", "再见！明天见。", "口语常用"),
            ("morning", "/ˈmɔːnɪŋ/", "n. 早晨；上午", "Good morning!", "早上好！", "上午见面用"),
            ("afternoon", "/ˌɑːftəˈnuːn/", "n. 下午", "Good afternoon, class!", "同学们下午好！", "下午见面用"),
            ("one", "/wʌn/", "num. 一", "I have one apple.", "我有一个苹果。", "数字 1"),
            ("two", "/tuː/", "num. 二", "Two cats are here.", "这里有两只猫。", "数字 2"),
            ("three", "/θriː/", "num. 三", "Three birds fly.", "三只鸟在飞。", "数字 3"),
            ("please", "/pliːz/", "int. 请", "Sit down, please.", "请坐下。", "礼貌用语"),
            ("thank", "/θæŋk/", "v. 感谢", "Thank you!", "谢谢你！", "thank you 谢谢"),
            ("yes", "/jes/", "adv. 是；对", "Yes, I am.", "是的，我是。", "肯定回答"),
            ("no", "/nəʊ/", "adv. 不；不是", "No, I'm not.", "不，我不是。", "否定回答"),
            ("boy", "/bɔɪ/", "n. 男孩", "He is a boy.", "他是个男孩。", "女孩是 girl"),
            ("girl", "/ɡɜːl/", "n. 女孩", "She is a girl.", "她是个女孩。", "男孩是 boy"),
            ("friend", "/frend/", "n. 朋友", "You are my friend.", "你是我的朋友。", "好朋友 good friend"),
        ],
    },
    {
        "key": "xqh1a_u2",
        "title": "新启航一上 · Unit 2 Numbers",
        "desc": "数字 1~10 与数数表达。",
        "items": [
            ("four", "/fɔː/", "num. 四", "I see four ducks.", "我看见四只鸭子。", "数字 4"),
            ("five", "/faɪv/", "num. 五", "Five fingers on my hand.", "我手上有五根手指。", "数字 5"),
            ("six", "/sɪks/", "num. 六", "Six pencils in the box.", "盒子里有六支铅笔。", "数字 6"),
            ("seven", "/ˈsevn/", "num. 七", "Seven days a week.", "一周七天。", "数字 7"),
            ("eight", "/eɪt/", "num. 八", "Eight little stars.", "八颗小星星。", "数字 8"),
            ("nine", "/naɪn/", "num. 九", "Nine red apples.", "九个红苹果。", "数字 9"),
            ("ten", "/ten/", "num. 十", "Count to ten.", "数到十。", "数字 10"),
            ("number", "/ˈnʌmbə/", "n. 数字", "What number is it?", "这是数字几？", "电话号码 phone number"),
            ("count", "/kaʊnt/", "v. 数；计数", "Let's count together.", "我们一起数。", "count 1 to 10"),
            ("how", "/haʊ/", "adv. 怎样；多少", "How many books?", "有多少本书？", "How many 问数量"),
            ("many", "/ˈmeni/", "adj. 许多的", "How many cats?", "有多少只猫？", "后接可数名词复数"),
            ("little", "/ˈlɪtl/", "adj. 小的", "A little dog runs.", "一只小狗在跑。", "反义 big"),
            ("big", "/bɪɡ/", "adj. 大的", "A big ball.", "一个大球。", "反义 little"),
            ("all", "/ɔːl/", "adj. 所有的", "All the children sing.", "所有孩子都在唱。", "all of us 我们所有人"),
            ("together", "/təˈɡeðə/", "adv. 一起", "We play together.", "我们一起玩。", "together with 和…一起"),
            ("again", "/əˈɡen/", "adv. 再一次", "Say it again, please.", "请再说一遍。", "再来一次"),
            ("star", "/stɑː/", "n. 星星", "I can see a star.", "我能看见一颗星星。", "五星 five stars"),
            ("hand", "/hænd/", "n. 手", "Show me your hand.", "给我看看你的手。", "两只手 two hands"),
            ("finger", "/ˈfɪŋɡə/", "n. 手指", "Count your fingers.", "数数你的手指。", "ten fingers"),
            ("ball", "/bɔːl/", "n. 球", "Throw the ball to me.", "把球扔给我。", "play ball 玩球"),
        ],
    },
    {
        "key": "xqh1a_u3",
        "title": "新启航一上 · Unit 3 Colours",
        "desc": "常见颜色词与描述颜色的句子。",
        "items": [
            ("colour", "/ˈkʌlə/", "n. 颜色", "What colour is it?", "它是什么颜色？", "美式拼写 color"),
            ("red", "/red/", "adj. 红色的", "A red apple.", "一个红苹果。", "红色"),
            ("yellow", "/ˈjeləʊ/", "adj. 黄色的", "The sun is yellow.", "太阳是黄色的。", "黄色"),
            ("blue", "/bluː/", "adj. 蓝色的", "The sky is blue.", "天空是蓝色的。", "蓝色"),
            ("green", "/ɡriːn/", "adj. 绿色的", "Green leaves in spring.", "春天绿叶子。", "绿色"),
            ("orange", "/ˈɒrɪndʒ/", "adj. 橙色的；n. 橙子", "An orange ball.", "一个橙色的球。", "既可指颜色也可指水果"),
            ("black", "/blæk/", "adj. 黑色的", "A black cat.", "一只黑猫。", "黑色"),
            ("white", "/waɪt/", "adj. 白色的", "White snow.", "白雪。", "白色"),
            ("pink", "/pɪŋk/", "adj. 粉色的", "A pink flower.", "一朵粉色的花。", "粉色"),
            ("purple", "/ˈpɜːpl/", "adj. 紫色的", "Purple grapes.", "紫色的葡萄。", "紫色"),
            ("brown", "/braʊn/", "adj. 棕色的", "A brown bear.", "一只棕熊。", "棕色"),
            ("colourful", "/ˈkʌləfl/", "adj. 色彩鲜艳的", "A colourful picture.", "一幅色彩鲜艳的画。", "由 colour 加后缀 -ful"),
            ("look", "/lʊk/", "v. 看", "Look at the rainbow!", "看那道彩虹！", "look at 看…"),
            ("like", "/laɪk/", "v. 喜欢", "I like blue.", "我喜欢蓝色。", "like + 名词"),
            ("picture", "/ˈpɪktʃə/", "n. 图画", "Draw a picture.", "画一幅画。", "＝ drawing"),
            ("flower", "/ˈflaʊə/", "n. 花", "A red flower.", "一朵红花。", "复数 flowers"),
            ("tree", "/triː/", "n. 树", "The tree is green.", "这棵树是绿色的。", "trees 复数"),
            ("sky", "/skaɪ/", "n. 天空", "The sky is blue.", "天空是蓝色的。", "in the sky 在天空中"),
            ("rainbow", "/ˈreɪnbəʊ/", "n. 彩虹", "A colourful rainbow.", "一道美丽的彩虹。", "rain + bow 合成"),
            ("paint", "/peɪnt/", "v. 涂色；绘画", "Let's paint the sun.", "我们来画太阳吧。", "paint a picture 画画"),
        ],
    },
    {
        "key": "xqh1a_u4",
        "title": "新启航一上 · Unit 4 School things",
        "desc": "文具类词汇与「这是我的…」句型。",
        "items": [
            ("pencil", "/ˈpensl/", "n. 铅笔", "This is my pencil.", "这是我的铅笔。", "a pencil 一支铅笔"),
            ("pen", "/pen/", "n. 钢笔", "I have a new pen.", "我有一支新钢笔。", "钢笔比铅笔少用"),
            ("book", "/bʊk/", "n. 书", "Open your book.", "打开你的书。", "books 复数"),
            ("bag", "/bæɡ/", "n. 书包；袋子", "My bag is heavy.", "我的书包很重。", "schoolbag 书包"),
            ("ruler", "/ˈruːlə/", "n. 尺子", "A long ruler.", "一把长尺子。", "draw with a ruler"),
            ("rubber", "/ˈrʌbə/", "n. 橡皮", "Where is my rubber?", "我的橡皮在哪儿？", "美式 eraser"),
            ("crayon", "/ˈkreɪən/", "n. 蜡笔", "A box of crayons.", "一盒蜡笔。", "用于涂色"),
            ("case", "/keɪs/", "n. 盒子；文具盒", "Pencil case 文具盒", "Pencil case。", "pencil case 文具盒"),
            ("desk", "/desk/", "n. 书桌", "Put it on the desk.", "把它放在书桌上。", "在书桌旁 at the desk"),
            ("chair", "/tʃeə/", "n. 椅子", "Sit on the chair.", "坐在椅子上。", "chairs 复数"),
            ("this", "/ðɪs/", "pron. 这；这个", "This is a pen.", "这是一支钢笔。", "指近处"),
            ("that", "/ðæt/", "pron. 那；那个", "That is a book.", "那是一本书。", "指远处"),
            ("have", "/hæv/", "v. 有", "I have a ruler.", "我有一把尺子。", "have got 也有"),
            ("new", "/njuː/", "adj. 新的", "A new bag.", "一个新书包。", "反义 old"),
            ("old", "/əʊld/", "adj. 旧的；年老的", "An old book.", "一本旧书。", "反义 new"),
            ("open", "/ˈəʊpən/", "v. 打开", "Open the bag.", "打开书包。", "反义 close"),
            ("close", "/kləʊz/", "v. 关上", "Close your book.", "合上书。", "反义 open"),
            ("put", "/pʊt/", "v. 放", "Put the pen here.", "把钢笔放这里。", "put-put-put 不规则"),
            ("box", "/bɒks/", "n. 盒子", "A box of pencils.", "一盒铅笔。", "boxes 复数"),
            ("where", "/weə/", "adv. 在哪里", "Where is my pen?", "我的钢笔在哪儿？", "询问地点"),
        ],
    },
    {
        "key": "xqh1a_u5",
        "title": "新启航一上 · Unit 5 My classroom",
        "desc": "教室与课堂用语：门、窗、黑板和指令句。",
        "items": [
            ("classroom", "/ˈklɑːsruːm/", "n. 教室", "This is our classroom.", "这是我们的教室。", "class + room 合成"),
            ("class", "/klɑːs/", "n. 班级；课", "We have an English class.", "我们有一节英语课。", "in class 在课上"),
            ("door", "/dɔː/", "n. 门", "Open the door, please.", "请开门。", "关门 close the door"),
            ("window", "/ˈwɪndəʊ/", "n. 窗户", "Look out of the window.", "往窗外看。", "windows 复数"),
            ("blackboard", "/ˈblækbɔːd/", "n. 黑板", "Look at the blackboard.", "看黑板。", "black + board 合成"),
            ("wall", "/wɔːl/", "n. 墙", "Pictures on the wall.", "墙上有画。", "on the wall 在墙上"),
            ("floor", "/flɔː/", "n. 地板", "Sit on the floor.", "坐在地板上。", "on the floor"),
            ("light", "/laɪt/", "n. 灯", "Turn on the light.", "开灯。", "turn on 打开"),
            ("sit", "/sɪt/", "v. 坐", "Sit down, please.", "请坐下。", "sit-sat-sat"),
            ("stand", "/stænd/", "v. 站", "Stand up, please.", "请起立。", "stand up 起立"),
            ("down", "/daʊn/", "adv. 向下", "Sit down.", "坐下。", "反义 up"),
            ("up", "/ʌp/", "adv. 向上", "Stand up.", "起立。", "反义 down"),
            ("listen", "/ˈlɪsn/", "v. 听", "Listen to me.", "听我说。", "listen to 听…"),
            ("read", "/riːd/", "v. 读", "Read after me.", "跟我读。", "read-read-read"),
            ("write", "/raɪt/", "v. 写", "Write your name.", "写下你的名字。", "write-wrote-written"),
            ("clean", "/kliːn/", "v. 打扫；adj. 干净的", "Clean the blackboard.", "擦黑板。", "keep clean 保持干净"),
            ("quiet", "/ˈkwaɪət/", "adj. 安静的", "Be quiet, please.", "请安静。", "反义 noisy"),
            ("hello", "/həˈləʊ/", "int. 你好（课堂问候）", "Hello, everyone!", "大家好！", "课上打招呼"),
            ("everyone", "/ˈevriwʌn/", "pron. 每个人", "Hello, everyone!", "大家好！", "every + one 合成"),
            ("teacher", "/ˈtiːtʃə/", "n. 老师", "Miss Li is our teacher.", "李老师是我们的老师。", "男老师用 Mr"),
        ],
    },

    # ======================= 一年级下册 =======================
    {
        "key": "xqh1b_u1",
        "title": "新启航一下 · Unit 1 Feelings",
        "desc": "情绪与感受：happy / sad / hungry 等。",
        "items": [
            ("happy", "/ˈhæpi/", "adj. 高兴的", "I am happy today.", "我今天很高兴。", "反义 sad"),
            ("sad", "/sæd/", "adj. 伤心的", "Don't be sad.", "别伤心。", "反义 happy"),
            ("angry", "/ˈæŋɡri/", "adj. 生气的", "He is angry.", "他生气了。", "be angry 生气"),
            ("tired", "/ˈtaɪəd/", "adj. 疲倦的", "I am tired.", "我累了。", "be tired 累了"),
            ("hungry", "/ˈhʌŋɡri/", "adj. 饥饿的", "I am hungry now.", "我现在饿了。", "反义 full 饱的"),
            ("thirsty", "/ˈθɜːsti/", "adj. 口渴的", "I am thirsty.", "我口渴了。", "想喝水"),
            ("cold", "/kəʊld/", "adj. 冷的", "It is cold today.", "今天很冷。", "反义 hot"),
            ("hot", "/hɒt/", "adj. 热的", "The soup is hot.", "汤很热。", "反义 cold"),
            ("fine", "/faɪn/", "adj. 好的", "I'm fine, thank you.", "我很好，谢谢。", "回答 How are you?"),
            ("feel", "/fiːl/", "v. 感觉", "How do you feel?", "你感觉怎么样？", "feel happy 感到高兴"),
            ("smile", "/smaɪl/", "v. 微笑", "She smiles at me.", "她对我微笑。", "n. 微笑"),
            ("cry", "/kraɪ/", "v. 哭", "The baby is crying.", "宝宝在哭。", "cry-cried-cried"),
            ("laugh", "/lɑːf/", "v. 笑", "We laugh together.", "我们一起笑。", "反义 cry"),
            ("love", "/lʌv/", "v. 爱", "I love my mum.", "我爱我妈妈。", "I love you 我爱你"),
            ("nice", "/naɪs/", "adj. 好的；漂亮的", "You look nice.", "你看起来很好看。", "夸赞用语"),
            ("great", "/ɡreɪt/", "adj. 好极了", "That's great!", "太棒了！", "表扬用语"),
            ("sorry", "/ˈsɒri/", "adj. 抱歉的", "I'm sorry.", "对不起。", "道歉用语"),
            ("welcome", "/ˈwelkəm/", "adj. 受欢迎的", "You are welcome.", "不用谢。", "回应 thank you"),
            ("well", "/wel/", "adv. 好地", "I can sing well.", "我唱得好。", "good 的副词形式"),
            ("today", "/təˈdeɪ/", "n. 今天", "Today is Monday.", "今天是星期一。", "tomorrow 明天"),
        ],
    },
    {
        "key": "xqh1b_u2",
        "title": "新启航一下 · Unit 2 Family",
        "desc": "家庭成员称谓与介绍家人的句子。",
        "items": [
            ("family", "/ˈfæməli/", "n. 家庭", "This is my family.", "这是我的家庭。", "一家人"),
            ("mum", "/mʌm/", "n. 妈妈", "My mum is a teacher.", "我妈妈是老师。", "美式 mom"),
            ("dad", "/dæd/", "n. 爸爸", "My dad is tall.", "我爸爸很高。", "father 正式"),
            ("mother", "/ˈmʌðə/", "n. 母亲", "My mother loves me.", "我妈妈爱我。", "书面语"),
            ("father", "/ˈfɑːðə/", "n. 父亲", "My father works here.", "我爸爸在这里工作。", "书面语"),
            ("grandma", "/ˈɡrænmɑː/", "n. 奶奶；外婆", "Grandma tells stories.", "奶奶讲故事。", "＝ grandmother"),
            ("grandpa", "/ˈɡrænpɑː/", "n. 爷爷；外公", "Grandpa is kind.", "爷爷很和蔼。", "＝ grandfather"),
            ("sister", "/ˈsɪstə/", "n. 姐妹", "My sister is little.", "我妹妹很小。", "姐姐/妹妹"),
            ("brother", "/ˈbrʌðə/", "n. 兄弟", "My brother likes football.", "我哥哥喜欢足球。", "哥哥/弟弟"),
            ("baby", "/ˈbeɪbi/", "n. 婴儿", "The baby is sleeping.", "宝宝在睡觉。", "很可爱"),
            ("he", "/hiː/", "pron. 他", "He is my brother.", "他是我弟弟。", "男他"),
            ("she", "/ʃiː/", "pron. 她", "She is my sister.", "她是我妹妹。", "女她"),
            ("we", "/wiː/", "pron. 我们", "We are a happy family.", "我们是幸福的一家。", "我们"),
            ("tall", "/tɔːl/", "adj. 高的", "My dad is tall.", "我爸爸很高。", "反义 short"),
            ("short", "/ʃɔːt/", "adj. 矮的；短的", "I am short.", "我个子矮。", "反义 tall"),
            ("kind", "/kaɪnd/", "adj. 和蔼的", "Grandma is kind.", "奶奶很和蔼。", "对人好"),
            ("house", "/haʊs/", "n. 房子", "Our house is big.", "我们的房子很大。", "home 家"),
            ("home", "/həʊm/", "n. 家", "I go home at five.", "我五点回家。", "go home 回家"),
            ("birthday", "/ˈbɜːθdeɪ/", "n. 生日", "Happy birthday!", "生日快乐！", "birth + day 合成"),
            ("cake", "/keɪk/", "n. 蛋糕", "A birthday cake.", "一个生日蛋糕。", "生日必备"),
        ],
    },
    {
        "key": "xqh1b_u3",
        "title": "新启航一下 · Unit 3 Pets",
        "desc": "宠物动物词汇与描述宠物的句子。",
        "items": [
            ("pet", "/pet/", "n. 宠物", "I have a pet.", "我有一只宠物。", "pet 宠物"),
            ("cat", "/kæt/", "n. 猫", "The cat says meow.", "猫喵喵叫。", "meow 猫叫声"),
            ("dog", "/dɒɡ/", "n. 狗", "The dog says woof.", "狗汪汪叫。", "woof 狗叫声"),
            ("fish", "/fɪʃ/", "n. 鱼", "A goldfish swims.", "金鱼在游。", "单复数同形"),
            ("bird", "/bɜːd/", "n. 鸟", "A bird can fly.", "鸟会飞。", "bring 鸟"),
            ("rabbit", "/ˈræbɪt/", "n. 兔子", "The rabbit jumps.", "兔子在跳。", "长耳朵"),
            ("duck", "/dʌk/", "n. 鸭子", "Ducks swim in water.", "鸭子在水中游。", "quack 鸭叫声"),
            ("mouse", "/maʊs/", "n. 老鼠", "A little mouse.", "一只小老鼠。", "复数 mice"),
            ("cute", "/kjuːt/", "adj. 可爱的", "The cat is cute.", "这只猫很可爱。", "夸小动物"),
            ("small", "/smɔːl/", "adj. 小的", "A small dog.", "一只小狗。", "反义 big"),
            ("tail", "/teɪl/", "n. 尾巴", "A long tail.", "一条长尾巴。", "动物有 tail"),
            ("ear", "/ɪə/", "n. 耳朵", "Two big ears.", "两只大耳朵。", "ears 复数"),
            ("eye", "/aɪ/", "n. 眼睛", "Big eyes.", "大大的眼睛。", "复数 eyes"),
            ("nose", "/nəʊz/", "n. 鼻子", "A small nose.", "一个小鼻子。", "nose 鼻子"),
            ("mouth", "/maʊθ/", "n. 嘴", "Open your mouth.", "张开嘴。", "mouth 嘴巴"),
            ("leg", "/leɡ/", "n. 腿", "Four legs.", "四条腿。", "动物有四条腿"),
            ("run", "/rʌn/", "v. 跑", "The dog can run.", "狗会跑。", "run-ran-run"),
            ("jump", "/dʒʌmp/", "v. 跳", "The rabbit jumps.", "兔子跳。", "jump up 跳起来"),
            ("swim", "/swɪm/", "v. 游泳", "Fish swim.", "鱼会游泳。", "swim-swam-swum"),
            ("feed", "/fiːd/", "v. 喂养", "I feed my cat.", "我喂我的猫。", "feed-fed-fed"),
        ],
    },
    {
        "key": "xqh1b_u4",
        "title": "新启航一下 · Unit 4 At the farm",
        "desc": "农场动物与农作物词汇。",
        "items": [
            ("farm", "/fɑːm/", "n. 农场", "We visit a farm.", "我们去参观农场。", "at the farm 在农场"),
            ("cow", "/kaʊ/", "n. 奶牛", "The cow gives milk.", "奶牛产奶。", "moo 牛叫声"),
            ("pig", "/pɪɡ/", "n. 猪", "The pig is pink.", "猪是粉色的。", "oink 猪叫声"),
            ("sheep", "/ʃiːp/", "n. 绵羊", "Sheep are white.", "绵羊是白色的。", "单复数同形"),
            ("horse", "/hɔːs/", "n. 马", "A horse can run fast.", "马跑得快。", "ride a horse 骑马"),
            ("chicken", "/ˈtʃɪkɪn/", "n. 鸡；鸡肉", "The chicken is small.", "这只鸡很小。", "小鸡"),
            ("hen", "/hen/", "n. 母鸡", "A hen lays eggs.", "母鸡下蛋。", "lay eggs 下蛋"),
            ("goat", "/ɡəʊt/", "n. 山羊", "A white goat.", "一只白色的山羊。", "和 sheep 不同"),
            ("egg", "/eɡ/", "n. 蛋", "I eat an egg.", "我吃一个鸡蛋。", "eggs 复数"),
            ("milk", "/mɪlk/", "n. 牛奶", "Drink some milk.", "喝点牛奶。", "drink milk 喝奶"),
            ("rice", "/raɪs/", "n. 米饭", "We eat rice.", "我们吃米饭。", "不可数名词"),
            ("corn", "/kɔːn/", "n. 玉米", "Corn is yellow.", "玉米是黄色的。", "农场作物"),
            ("apple", "/ˈæpl/", "n. 苹果", "A red apple.", "一个红苹果。", "apples 复数"),
            ("banana", "/bəˈnɑːnə/", "n. 香蕉", "Bananas are yellow.", "香蕉是黄色的。", "bə 轻读"),
            ("pear", "/peə/", "n. 梨", "A sweet pear.", "一个甜梨。", "水果"),
            ("dog", "/dɒɡ/", "n. 狗（农场看门狗）", "The farm dog is friendly.", "农场的狗很友好。", "farm dog 看门狗"),
            ("big", "/bɪɡ/", "adj. 大的", "A big farm.", "一个大农场。", "反义 small"),
            ("many", "/ˈmeni/", "adj. 许多的", "Many animals here.", "这里有好多动物。", "How many animals?"),
            ("sound", "/saʊnd/", "n. 声音", "What sound is it?", "那是什么声音？", "动物叫声"),
            ("loud", "/laʊd/", "adj. 大声的", "The duck is loud.", "鸭子叫声很大。", "反义 quiet"),
        ],
    },
    {
        "key": "xqh1b_u5",
        "title": "新启航一下 · Unit 5 My room",
        "desc": "房间与家具词汇、方位介词与「在哪里」句型。",
        "items": [
            ("room", "/ruːm/", "n. 房间", "This is my room.", "这是我的房间。", "bedroom 卧室"),
            ("bed", "/bed/", "n. 床", "My bed is soft.", "我的床很软。", "go to bed 睡觉"),
            ("table", "/ˈteɪbl/", "n. 桌子", "Put it on the table.", "把它放在桌子上。", "dining table 餐桌"),
            ("door", "/dɔː/", "n. 门", "Close the door.", "关门。", "door 门"),
            ("window", "/ˈwɪndəʊ/", "n. 窗户", "Open the window.", "开窗。", "window 窗户"),
            ("toy", "/tɔɪ/", "n. 玩具", "My toys are here.", "我的玩具在这儿。", "toys 复数"),
            ("box", "/bɒks/", "n. 盒子", "A toy box.", "一个玩具箱。", "boxes 复数"),
            ("clock", "/klɒk/", "n. 钟", "The clock is on the wall.", "钟在墙上。", "o'clock 点钟"),
            ("lamp", "/læmp/", "n. 台灯", "Turn on the lamp.", "开台灯。", "light 也可指灯"),
            ("bookcase", "/ˈbʊkkeɪs/", "n. 书柜", "Books in the bookcase.", "书在书柜里。", "book + case 合成"),
            ("in", "/ɪn/", "prep. 在…里", "The ball is in the box.", "球在盒子里。", "方位介词"),
            ("on", "/ɒn/", "prep. 在…上", "The book is on the desk.", "书在书桌上。", "方位介词"),
            ("under", "/ˈʌndə/", "prep. 在…下", "The cat is under the bed.", "猫在床下。", "方位介词"),
            ("behind", "/bɪˈhaɪnd/", "prep. 在…后面", "Behind the door.", "在门后面。", "方位介词"),
            ("near", "/nɪə/", "prep. 在…附近", "Near the window.", "在窗户附近。", "方位介词"),
            ("tidy", "/ˈtaɪdi/", "v. 整理；adj. 整洁的", "Tidy your room.", "整理你的房间。", "keep tidy 保持整洁"),
            ("find", "/faɪnd/", "v. 找到", "I can't find my toy.", "我找不到我的玩具了。", "find-found-found"),
            ("sleep", "/sliːp/", "v. 睡觉", "I sleep at nine.", "我九点睡觉。", "go to sleep 入睡"),
            ("wake", "/weɪk/", "v. 醒来", "I wake up at seven.", "我七点醒来。", "wake up 醒来"),
            ("goodnight", "/ˌɡʊdˈnaɪt/", "int. 晚安", "Goodnight, Mum!", "晚安，妈妈！", "睡前用语"),
        ],
    },
]

WORD_COUNT = sum(len(g["items"]) for g in GROUPS)
