# -*- coding: utf-8 -*-
"""小学词汇·第 3 批：食物与饮品 / 服装与物品 / 家与地点。"""

GROUPS = [
    {
        "key": "food_drink",
        "title": "词汇 · 食物与饮品",
        "desc": "三餐、水果、蔬菜与常见饮品词汇。",
        "items": [
            ("food", "/fuːd/", "n. 食物", "Chinese food is delicious.", "中国菜很好吃。", "food 不可数；fast food 快餐"),
            ("rice", "/raɪs/", "n. 米饭", "We eat rice for dinner.", "我们晚饭吃米饭。", "不可数；rice noodles 米粉"),
            ("noodles", "/ˈnuːdlz/", "n. 面条", "Noodles are my favorite.", "面条是我的最爱。", "常作复数"),
            ("bread", "/bred/", "n. 面包", "I have bread and milk.", "我吃面包喝牛奶。", "不可数：a piece of bread"),
            ("cake", "/keɪk/", "n. 蛋糕", "The birthday cake is sweet.", "生日蛋糕很甜。", "make a cake"),
            ("milk", "/mɪlk/", "n. 牛奶", "Drink milk every day.", "每天喝牛奶。", "a glass of milk"),
            ("water", "/ˈwɔːtə/", "n. 水", "Drink more water.", "多喝水。", "也可作动词浇水"),
            ("tea", "/tiː/", "n. 茶", "Grandpa drinks green tea.", "爷爷喝绿茶。", "a cup of tea"),
            ("juice", "/dʒuːs/", "n. 果汁", "Orange juice, please.", "请来橙汁。", "不可数；juicy 多汁"),
            ("apple", "/ˈæpl/", "n. 苹果", "An apple a day keeps the doctor away.", "一天一苹果，医生远离我。", "用 an"),
            ("banana", "/bəˈnɑːnə/", "n. 香蕉", "Monkeys eat bananas.", "猴子吃香蕉。", "重音在后"),
            ("pear", "/peə/", "n. 梨", "This pear is juicy.", "这个梨很多汁。", "与 pair 同音"),
            ("grape", "/ɡreɪp/", "n. 葡萄", "Grapes can make wine.", "葡萄能酿酒。", "a bunch of grapes"),
            ("peach", "/piːtʃ/", "n. 桃子", "The peach is sweet.", "桃子很甜。", "复数 peaches"),
            ("watermelon", "/ˈwɔːtəmelən/", "n. 西瓜", "Watermelon is cool in summer.", "西瓜解暑。", "合成词"),
            ("mango", "/ˈmæŋɡəʊ/", "n. 芒果", "Mango smoothies are yummy.", "芒果奶昔很好喝。", "复数 mangoes"),
            ("tomato", "/təˈmɑːtəʊ/", "n. 西红柿", "I like tomato soup.", "我喜欢西红柿汤。", "复数 tomatoes"),
            ("potato", "/pəˈteɪtəʊ/", "n. 土豆", "Baked potatoes are tasty.", "烤土豆很好吃。", "复数 potatoes"),
            ("carrot", "/ˈkærət/", "n. 胡萝卜", "Rabbits love carrots.", "兔子爱胡萝卜。", "双 r"),
            ("meat", "/miːt/", "n. 肉", "Don't eat too much meat.", "别吃太多肉。", "不可数；与 meet 同音"),
            ("beef", "/biːf/", "n. 牛肉", "Beef noodles, please.", "请来牛肉面。", "不可数"),
            ("pork", "/pɔːk/", "n. 猪肉", "Mum cooks pork dumplings.", "妈妈包猪肉猪肉饺子。", "不可数"),
            ("hamburger", "/ˈhæmbɜːɡə/", "n. 汉堡", "Hamburgers are fast food.", "汉堡是快餐。", "口语说 burger"),
            ("sandwich", "/ˈsænwɪdʒ/", "n. 三明治", "I make a sandwich for lunch.", "我午餐做三明治。", "复数 sandwiches"),
            ("chips", "/tʃɪps/", "n. 薯条", "Fish and chips, please.", "请来炸鱼薯条。", "美式 fries"),
            ("ice cream", "/ˌaɪs ˈkriːm/", "n. 冰淇淋", "Two ice creams, please.", "请来两份冰淇淋。", "ice + cream"),
            ("sweet", "/swiːt/", "n. 糖果", "Sweets are bad for teeth.", "糖果伤牙。", "英式 sweet / 美式 candy"),
            ("candy", "/ˈkændi/", "n. 糖果", "Don't eat too much candy.", "别吃太多糖。", "美式常用"),
            ("chocolate", "/ˈtʃɒklət/", "n. 巧克力", "Chocolate makes me happy.", "巧克力让我开心。", "三个音节"),
            ("biscuit", "/ˈbɪskɪt/", "n. 饼干", "I have a biscuit with tea.", "我配茶吃饼干。", "美式 cookie"),
            ("hungry", "/ˈhʌŋɡri/", "adj. 饿的", "I am hungry.", "我饿了。", "be hungry"),
            ("thirsty", "/ˈθɜːsti/", "adj. 渴的", "Are you thirsty?", "你渴吗？", "th 咬舌"),
            ("eat", "/iːt/", "v. 吃", "Eat more vegetables.", "多吃蔬菜。", "eat-ate-eaten"),
            ("drink", "/drɪŋk/", "v. 喝", "Drink water after sports.", "运动后喝水。", "drink-drank-drunk"),
            ("taste", "/teɪst/", "v. 尝", "Taste the soup first.", "先尝尝汤。", "taste good"),
            ("breakfast", "/ˈbrekfəst/", "n. 早餐", "Breakfast is ready.", "早餐好了。", "have breakfast"),
            ("lunch", "/lʌntʃ/", "n. 午餐", "Lunch is at twelve.", "十二点吃午饭。", "have lunch"),
            ("dinner", "/ˈdɪnə/", "n. 晚餐", "Dinner is on the table.", "晚饭摆桌上了。", "have dinner"),
            ("supper", "/ˈsʌpə/", "n. 晚饭", "After supper we walk.", "晚饭后我们散步。", "与 dinner 近义"),
            ("menu", "/ˈmenjuː/", "n. 菜单", "Read the menu, please.", "请看菜单。", "on the menu"),
            ("delicious", "/dɪˈlɪʃəs/", "adj. 美味的", "The cake is delicious.", "蛋糕很美味。", "用 really 修饰"),
            ("cook", "/kʊk/", "v. 烹饪", "Dad cooks on Sunday.", "周日爸爸做饭。", "cooker 是炉具"),
            ("sour", "/ˈsaʊə/", "adj. 酸的", "Lemons are sour.", "柠檬很酸。", "our 读 /aʊə/"),
            ("hot", "/hɒt/", "adj. 热的；辣的", "The soup is too hot.", "汤太烫了。", "烫与辣同词"),
            ("fresh", "/freʃ/", "adj. 新鲜的", "Fresh fish tastes better.", "新鲜的鱼更好吃。", "fresh air"),
        ],
    },
    {
        "key": "cloth_things",
        "title": "词汇 · 服装与物品",
        "desc": "衣服穿戴与日常物品词汇。",
        "items": [
            ("clothes", "/kləʊðz/", "n. 衣服", "Wash your clothes on Sunday.", "周日洗衣服。", "永远复数形式"),
            ("shirt", "/ʃɜːt/", "n. 衬衫", "The white shirt is clean.", "白衬衫是干净的。", "sh 读 /ʃ/"),
            ("T-shirt", "/ˈtiːʃɜːt/", "n. T恤", "I wear a T-shirt in summer.", "夏天我穿T恤。", "T 形命名"),
            ("dress", "/dres/", "n. 连衣裙", "She has a red dress.", "她有条红裙子。", "也作动词穿衣"),
            ("skirt", "/skɜːt/", "n. 裙子", "The skirt is short.", "这条裙子很短。", "skirt 短裙"),
            ("coat", "/kəʊt/", "n. 外套", "Put on your coat.", "穿上外套。", "put on 动作"),
            ("jacket", "/ˈdʒækɪt/", "n. 夹克", "A jacket keeps you warm.", "夹克保暖。", "比 coat 短"),
            ("sweater", "/ˈswetə/", "n. 毛衣", "This sweater is wool.", "这件毛衣是羊毛的。", "英式 jumper"),
            ("trousers", "/ˈtraʊzəz/", "n. 长裤", "My trousers are blue.", "我的裤子是蓝的。", "复数：a pair of"),
            ("pants", "/pænts/", "n. 裤子（美式）", "These pants fit me.", "这条裤子合身。", "英式指内裤"),
            ("shorts", "/ʃɔːts/", "n. 短裤", "Wear shorts in summer.", "夏天穿短裤。", "永远复数"),
            ("shoes", "/ʃuːz/", "n. 鞋子", "Take off your shoes.", "脱鞋。", "a pair of shoes"),
            ("socks", "/sɒks/", "n. 袜子", "I have warm socks.", "我有暖和的袜子。", "a pair of socks"),
            ("hat", "/hæt/", "n. 帽子", "The sun is hot, wear a hat.", "太阳晒，戴帽子。", "有檐帽"),
            ("cap", "/kæp/", "n. 鸭舌帽", "Baseball players wear caps.", "棒球运动员戴帽。", "cap 遮阳帽"),
            ("glasses", "/ˈɡlɑːsɪz/", "n. 眼镜", "Grandpa wears glasses.", "爷爷戴眼镜。", "永远复数"),
            ("wear", "/weə/", "v. 穿着", "She wears a smile.", "她面带微笑。", "wear 状态"),
            ("umbrella", "/ʌmˈbrelə/", "n. 雨伞", "Take an umbrella, it may rain.", "带把伞，可能下雨。", "用 an"),
            ("watch", "/wɒtʃ/", "n. 手表", "My watch is fast.", "我的手表快了。", "双义：观看"),
            ("key", "/kiː/", "n. 钥匙", "I lost my key.", "我把钥匙丢了。", "the key to the door"),
            ("money", "/ˈmʌni/", "n. 钱", "Money is in my pocket.", "钱在我口袋里。", "不可数"),
            ("pocket", "/ˈpɒkɪt/", "n. 口袋", "My hands are in pockets.", "我手插口袋。", "in one's pocket"),
            ("toy", "/tɔɪ/", "n. 玩具", "Toy trains are fun.", "玩具火车很好玩。", "复数 toys"),
            ("ball", "/bɔːl/", "n. 球", "Bounce the ball, please.", "请拍球。", "all 读 /ɔːl/"),
            ("kite", "/kaɪt/", "n. 风筝", "Fly a kite in spring.", "春天放风筝。", "fly a kite"),
            ("doll", "/dɒl/", "n. 玩偶", "The doll has curly hair.", "玩偶有卷发。", "复数 dolls"),
            ("present", "/ˈpreznt/", "n. 礼物", "This present is for you.", "这份礼物给你。", "双义：出席的"),
            ("gift", "/ɡɪft/", "n. 礼物", "A birthday gift!", "一份生日礼物！", "比 present 正式"),
            ("photo", "/ˈfəʊtəʊ/", "n. 照片", "Look at this photo.", "看这张照片。", "take photos"),
            ("picture", "/ˈpɪktʃə/", "n. 图片", "Draw a picture of your home.", "画一张你家的图。", "双义：描绘"),
            ("card", "/kɑːd/", "n. 卡片", "Make a card for Mum.", "给妈妈做张卡。", "birthday card"),
            ("box", "/bɒks/", "n. 盒子", "The box is under the bed.", "盒子在床下。", "复数 boxes"),
            ("bottle", "/ˈbɒtl/", "n. 瓶子", "A bottle of water, please.", "请来一瓶水。", "a bottle of"),
            ("cup", "/kʌp/", "n. 杯子", "This cup is hot.", "杯子很烫。", "a cup of tea"),
            ("basket", "/ˈbɑːskɪt/", "n. 篮子", "Put apples in the basket.", "把苹果放进篮子。", "basketball 篮球"),
            ("mirror", "/ˈmɪrə/", "n. 镜子", "Look in the mirror.", "照镜子。", "双 r"),
            ("clock", "/klɒk/", "n. 时钟", "The clock is on the wall.", "钟在墙上。", "挂钟座钟"),
            ("lamp", "/læmp/", "n. 台灯", "Turn on the lamp.", "打开台灯。", "turn on/off"),
            ("light", "/laɪt/", "n. 灯", "The light is too bright.", "灯太亮了。", "traffic lights 红绿灯"),
            ("phone", "/fəʊn/", "n. 电话", "My phone is ringing.", "我的电话响了。", "answer the phone"),
            ("wallet", "/ˈwɒlɪt/", "n. 钱包", "My wallet is empty!", "我的钱包空了！", "男用；purse 女用"),
        ],
    },
    {
        "key": "home_place",
        "title": "词汇 · 家与地点",
        "desc": "房屋房间、社区场所与自然景观词汇。",
        "items": [
            ("house", "/haʊs/", "n. 房子", "Their house has a garden.", "他们家有个花园。", "house 建筑 home 家"),
            ("room", "/ruːm/", "n. 房间", "My room is upstairs.", "我的房间在楼上。", "make room 让空间"),
            ("bedroom", "/ˈbedruːm/", "n. 卧室", "The bedroom is tidy.", "卧室很整洁。", "合成词"),
            ("living room", "/ˈlɪvɪŋ ruːm/", "n. 客厅", "We watch TV in the living room.", "我们在客厅看电视。", "英式 sitting room"),
            ("kitchen", "/ˈkɪtʃɪn/", "n. 厨房", "Mum is in the kitchen.", "妈妈在厨房。", "tch 读 /tʃ/"),
            ("bathroom", "/ˈbɑːθruːm/", "n. 浴室", "The bathroom is free now.", "浴室现在空了。", "也指厕所"),
            ("door", "/dɔː/", "n. 门", "Close the door, please.", "请关门。", "next door 隔壁"),
            ("window", "/ˈwɪndəʊ/", "n. 窗户", "Open the window for fresh air.", "开窗透新鲜空气。", "out of the window"),
            ("wall", "/wɔːl/", "n. 墙", "The wall is white.", "墙是白色的。", "on the wall"),
            ("floor", "/flɔː/", "n. 地板；楼层", "The cat sits on the floor.", "猫坐在地板上。", "英式一楼 ground floor"),
            ("table", "/ˈteɪbl/", "n. 桌子", "Four people sit at the table.", "四个人坐在桌边。", "at the table"),
            ("bed", "/bed/", "n. 床", "Make the bed after you get up.", "起床后整理床铺。", "go to bed"),
            ("sofa", "/ˈsəʊfə/", "n. 沙发", "The cat sleeps on the sofa.", "猫睡在沙发上。", "音译词"),
            ("garden", "/ˈɡɑːdn/", "n. 花园", "Flowers grow in the garden.", "花园里长花。", "in the garden"),
            ("yard", "/jɑːd/", "n. 院子", "The kids play in the yard.", "孩子们在院子玩。", "美式常用"),
            ("park", "/pɑːk/", "n. 公园", "We walk in the park.", "我们在公园散步。", "in the park"),
            ("shop", "/ʃɒp/", "n. 商店", "The shop opens at nine.", "商店九点开门。", "go shopping"),
            ("store", "/stɔː/", "n. 商店", "This store sells toys.", "这家店卖玩具。", "美式常用"),
            ("supermarket", "/ˈsuːpəmɑːkɪt/", "n. 超市", "Buy fruit at the supermarket.", "在超市买水果。", "合成词"),
            ("cinema", "/ˈsɪnəmə/", "n. 电影院", "We go to the cinema on Friday.", "我们周五去电影院。", "at the cinema"),
            ("museum", "/mjuˈziːəm/", "n. 博物馆", "The museum is free on Monday.", "博物馆周一免费。", "重音在后"),
            ("restaurant", "/ˈrestrɒnt/", "n. 餐馆", "This restaurant serves noodles.", "这家餐馆卖面条。", "au 读 /ɒ/"),
            ("hotel", "/həʊˈtel/", "n. 旅馆", "We stay at a hotel.", "我们住旅馆。", "stay at a hotel"),
            ("city", "/ˈsɪti/", "n. 城市", "Shanghai is a big city.", "上海是大城市。", "复数 cities"),
            ("country", "/ˈkʌntri/", "n. 国家；乡村", "China is a great country.", "中国是伟大的国家。", "双义"),
            ("street", "/striːt/", "n. 街道", "Our street is quiet.", "我们的街道很安静。", "str- 连读"),
            ("road", "/rəʊd/", "n. 路", "Cross the road carefully.", "小心过马路。", "on the road"),
            ("bridge", "/brɪdʒ/", "n. 桥", "The bridge crosses the river.", "桥横跨河流。", "dge 读 /dʒ/"),
            ("station", "/ˈsteɪʃn/", "n. 车站", "Meet me at the station.", "车站见。", "train station"),
            ("airport", "/ˈeəpɔːt/", "n. 机场", "We arrive at the airport at six.", "我们六点到机场。", "at the airport"),
            ("beach", "/biːtʃ/", "n. 海滩", "We play on the beach.", "我们在沙滩玩。", "复数 beaches"),
            ("river", "/ˈrɪvə/", "n. 河", "The river runs fast.", "河水流得急。", "on the river"),
            ("lake", "/leɪk/", "n. 湖", "The lake is calm.", "湖面平静。", "by the lake"),
            ("mountain", "/ˈmaʊntən/", "n. 山", "We climb mountains in autumn.", "我们秋天爬山。", "复数表泛指"),
            ("tree", "/triː/", "n. 树", "Birds sing in the tree.", "鸟在树上唱歌。", "in/on the tree"),
            ("flower", "/ˈflaʊə/", "n. 花", "Roses are beautiful flowers.", "玫瑰是美丽的花。", "复数 flowers"),
            ("grass", "/ɡrɑːs/", "n. 草", "Don't walk on the grass.", "别踩草地。", "不可数"),
            ("sea", "/siː/", "n. 海", "The sea is blue.", "海是蓝的。", "by the sea"),
            ("world", "/wɜːld/", "n. 世界", "The world is big.", "世界很大。", "all over the world"),
        ],
    },
]
