# -*- coding: utf-8 -*-
"""小学词汇·第 2 批：学校与学习 / 身体与健康 / 动物。"""

GROUPS = [
    {
        "key": "school",
        "title": "词汇 · 学校与学习",
        "desc": "文具、学科、课堂与校园场所，小学生最高频词汇。",
        "items": [
            ("school", "n. 学校", "I go to school by bus.", "我坐公交上学。", "go to school 上学（不加 the）；primary school 小学"),
            ("class", "n. 班级，课", "We are in Class Two.", "我们在二班。", "have a class 上课；class 作全班同学也可"),
            ("classroom", "n. 教室", "Our classroom is clean.", "我们的教室很干净。", "classroom = class + room 合成词"),
            ("teacher", "n. 老师", "My teacher is very kind.", "我的老师很和蔼。", "teach 教 → teacher 教的人"),
            ("student", "n. 学生", "She is a good student.", "她是个好学生。", "student 与 pupil 同义，pupil 更英式"),
            ("desk", "n. 书桌", "Put your book on the desk.", "把书放到桌上。", "desk 指书桌，table 指餐桌"),
            ("chair", "n. 椅子", "This chair is broken.", "这把椅子坏了。", "sit on a chair 坐在椅子上"),
            ("blackboard", "n. 黑板", "Look at the blackboard.", "看黑板。", "black + board 合成；别忘 the"),
            ("book", "n. 书", "This book is interesting.", "这本书很有趣。", "storybook 故事书；notebook 笔记本"),
            ("pen", "n. 钢笔", "May I borrow your pen?", "能借你的钢笔吗？", "a pen 一支笔；pen friend 笔友"),
            ("pencil", "n. 铅笔", "I draw with a pencil.", "我用铅笔画图。", "pencil box 铅笔盒；pencil case 笔袋"),
            ("ruler", "n. 尺子", "Draw a line with your ruler.", "用尺子画条线。", "ruler 也指统治者，小学阶段只要记住尺子"),
            ("eraser", "n. 橡皮", "My eraser is missing.", "我的橡皮不见了。", "英式叫 rubber；eraser 美式"),
            ("bag", "n. 包，书包", "My bag is heavy.", "我的书包很重。", "schoolbag 书包；plastic bag 塑料袋"),
            ("homework", "n. 作业", "I do my homework after dinner.", "我晚饭后写作业。", "homework 不可数：a lot of homework"),
            ("lesson", "n. 功课，一节课", "Today's lesson is fun.", "今天的课很有趣。", "do one's lessons 做功课；first lesson 第一节"),
            ("subject", "n. 科目", "Maths is my favorite subject.", "数学是我最喜欢的科目。", "favorite subject 最喜欢的科目"),
            ("English", "n. 英语", "We speak English in class.", "课上我们说英语。", "语言名首字母大写：English, Chinese"),
            ("Chinese", "n. 语文；中文", "I like Chinese best.", "我最喜欢语文。", "既指中文也指中国人"),
            ("maths", "n. 数学", "I am good at maths.", "我数学很好。", "英式 maths；美式 math"),
            ("science", "n. 科学", "We do experiments in science.", "科学课我们做实验。", "science fiction 科幻"),
            ("music", "n. 音乐", "Music makes me happy.", "音乐让我快乐。", "listen to music 听音乐（加 to）"),
            ("art", "n. 美术", "We paint in art class.", "美术课我们画画。", "art 不可数；work of art 艺术品"),
            ("computer", "n. 电脑", "The computer is on the desk.", "电脑在桌上。", "play on the computer 玩电脑"),
            ("library", "n. 图书馆", "We read in the library.", "我们在图书馆看书。", "in the library；复数 libraries"),
            ("playground", "n. 操场", "The children are on the playground.", "孩子们在操场上。", "on the playground 用 on"),
            ("read", "v. 读", "I read a book every night.", "我每晚读一本书。", "read 过去式同形 read /red/"),
            ("write", "v. 写", "Write your name here.", "在这里写你的名字。", "write→wrote→written；write down 写下"),
            ("draw", "v. 画", "Can you draw a cat?", "你会画猫吗？", "draw 线条画；paint 上色画"),
            ("learn", "v. 学习", "We learn English at school.", "我们在学校学英语。", "learn from 向…学习"),
            ("spell", "v. 拼写", "How do you spell 'banana'?", "banana 怎么拼？", "spell out 逐字母拼出"),
            ("study", "v. 学习", "I study hard for the test.", "我为考试努力学习。", "study 指系统学习；复数 studies"),
            ("answer", "n. 答案", "The answer is right.", "答案是对的。", "know the answer 知道答案"),
            ("question", "n. 问题", "Ask questions if you don't know.", "不懂就提问。", "ask a question 提问"),
            ("test", "n. 测验", "We have a test today.", "我们今天有测验。", "have a test 有测验；test paper 试卷"),
            ("exam", "n. 考试", "The final exam is in June.", "期末考试在六月。", "exam 是 examination 缩写"),
            ("pupil", "n. 小学生", "The pupils line up.", "小学生们排队。", "pupil 英式常用；class pupil"),
            ("flag", "n. 旗子", "We raise the flag on Monday.", "我们周一升旗。", "national flag 国旗"),
            ("duty", "n. 值日", "It's my duty today.", "今天我值日。", "on duty 值日/值班"),
            ("bell", "n. 铃", "The bell is ringing.", "铃在响。", "ring the bell 敲铃"),
            ("exercise", "n. 练习，运动", "Eye exercises are good for you.", "眼保健操对你有好处。", "do exercises 做练习；exercise 也可指锻炼"),
            ("word", "n. 单词", "Learn five new words a day.", "一天学五个新单词。", "in other words 换句话说"),
            ("sentence", "n. 句子", "Make a sentence with this word.", "用这个词造个句子。", "make sentences 造句"),
            ("letter", "n. 字母；信", "A comes before B in letters.", "字母表里 A 在 B 前。", "letter 双义：字母/信件"),
            ("page", "n. 页", "Open your book to page ten.", "打开书第十页。", "on page ten 用 on"),
        ],
    },
    {
        "key": "body_health",
        "title": "词汇 · 身体与健康",
        "desc": "身体部位、健康与就医词汇，学会描述自己。",
        "items": [
            ("head", "n. 头", "Shake your head.", "摇摇头。", "headache 头疼 = head + ache"),
            ("face", "n. 脸", "Wash your face, please.", "请洗脸。", "face to face 面对面"),
            ("eye", "n. 眼睛", "Her eyes are big.", "她的眼睛很大。", "通常用复数 eyes；eyebrow 眉毛"),
            ("ear", "n. 耳朵", "I hear with my ears.", "我用耳朵听。", "earache 耳朵疼"),
            ("nose", "n. 鼻子", "The clown has a red nose.", "小丑有个红鼻子。", "nose 与 rose 押韵"),
            ("mouth", "n. 嘴", "Open your mouth.", "张开嘴。", "读 /maʊθ/，与 month /mʌnθ/ 区分"),
            ("hair", "n. 头发", "She has long hair.", "她留长发。", "hair 不可数：long hair"),
            ("arm", "n. 手臂", "Raise your arm.", "举起手臂。", "arm in arm 手挽手"),
            ("hand", "n. 手", "Give me your hand.", "把你的手给我。", "hand in hand 手牵手"),
            ("finger", "n. 手指", "I have ten fingers.", "我有十根手指。", "thumb 是大拇指，不算 finger"),
            ("leg", "n. 腿", "My legs are tired.", "我的腿累了。", "legs 双腿用复数"),
            ("foot", "n. 脚", "My left foot hurts.", "我左脚疼。", "复数 feet；on foot 步行"),
            ("feet", "n. 双脚", "Wash your feet before bed.", "睡前洗脚。", "foot 的复数形式"),
            ("knee", "n. 膝盖", "I hurt my knee.", "我伤了膝盖。", "k 的发音 /niː/ 不读"),
            ("tooth", "n. 牙齿", "Brush your tooth carefully.", "仔细刷牙。", "复数 teeth；toothache 牙疼"),
            ("teeth", "n. 牙齿（复数）", "The baby has no teeth yet.", "宝宝还没长牙。", "tooth 的复数，oo→ee"),
            ("body", "n. 身体", "Exercise is good for the body.", "锻炼对身体好。", "复数 bodies"),
            ("healthy", "adj. 健康的", "Vegetables are healthy.", "蔬菜有益健康。", "stay healthy 保持健康"),
            ("ill", "adj. 生病的", "He is ill today.", "他今天生病了。", "be ill 生病；illness 疾病名词"),
            ("sick", "adj. 恶心的，生病的", "I feel sick.", "我感到恶心。", "be sick 英式常指呕吐"),
            ("hurt", "v. 疼；受伤", "Does it hurt?", "疼吗？", "hurt 过去式同形"),
            ("doctor", "n. 医生", "The doctor helps people.", "医生帮助人。", "see a doctor 看医生"),
            ("nurse", "n. 护士", "The nurse is gentle.", "护士很温柔。", "nurse 读 /nɜːs/"),
            ("hospital", "n. 医院", "Grandpa is in hospital.", "爷爷住院了。", "in hospital 住院（不加 the）"),
            ("medicine", "n. 药", "Take the medicine three times a day.", "一天吃三次药。", "medicine 不可数；take medicine 吃药"),
            ("cold", "n. 感冒", "I have a cold.", "我感冒了。", "have a cold / catch a cold"),
            ("fever", "n. 发烧", "The boy has a fever.", "这个男孩发烧了。", "have a fever 发烧"),
            ("headache", "n. 头疼", "I have a headache.", "我头疼。", "ache 表示持续疼痛"),
            ("toothache", "n. 牙疼", "Too much candy gives you toothache.", "糖吃多了牙疼。", "tooth + ache 合成"),
            ("fine", "adj. 很好的", "I'm fine, thank you.", "我很好，谢谢。", "fine 问候回复常用"),
            ("better", "adj. 更好的", "I feel better now.", "我现在好多了。", "well 的比较级；feel better"),
            ("rest", "n. 休息", "You need a good rest.", "你需要好好休息。", "have a rest 休息一下"),
            ("sleep", "v. 睡觉", "Children need ten hours' sleep.", "孩子需要十小时睡眠。", "go to sleep 入睡"),
            ("wash", "v. 洗", "Wash your hands before eating.", "饭前洗手。", "wash hands 洗手；wash away 洗掉"),
            ("brush", "v. 刷", "Brush your teeth twice a day.", "一天刷两次牙。", "brush teeth 刷牙"),
            ("tired", "adj. 累的", "I am tired after running.", "跑步后我累了。", "be tired of 厌倦"),
            ("strong", "adj. 强壮的", "Milk makes you strong.", "牛奶让你强壮。", "as strong as a horse 壮如马"),
            ("clean", "v. 打扫", "We clean the classroom after school.", "放学后我们打扫教室。", "clean up 清理干净"),
            ("smile", "v. 微笑", "The teacher smiles at us.", "老师朝我们微笑。", "smile at sb 对某人微笑"),
        ],
    },
    {
        "key": "animal",
        "title": "词汇 · 动物",
        "desc": "常见动物名称与特征描述，动物园主题词汇。",
        "items": [
            ("animal", "n. 动物", "Pandas are my favorite animals.", "熊猫是我最喜欢的动物。", "animal 音节重音在首：AN-i-mal"),
            ("cat", "n. 猫", "The cat is on the sofa.", "猫在沙发上。", "copy cat 好模仿的人；rain cats and dogs 倾盆大雨"),
            ("dog", "n. 狗", "My dog can fetch.", "我的狗会捡东西。", "lucky dog 幸运儿"),
            ("bird", "n. 鸟", "Birds fly in the sky.", "鸟在天上飞。", "early bird 早起的人"),
            ("fish", "n. 鱼", "Fish swim in water.", "鱼在水里游。", "单复数同形 fish；fishes 指多种鱼"),
            ("rabbit", "n. 兔子", "The rabbit has long ears.", "兔子有长耳朵。", "as quick as a rabbit"),
            ("duck", "n. 鸭子", "Ducks swim in the pond.", "鸭子在池塘游泳。", "duck 双义：躲闪"),
            ("chicken", "n. 小鸡；鸡肉", "We had chicken for lunch.", "我们午饭吃鸡肉。", "活的小鸡可数，鸡肉不可数"),
            ("hen", "n. 母鸡", "The hen lays eggs.", "母鸡下蛋。", "hen 只指母鸡"),
            ("pig", "n. 猪", "Pigs are pink.", "猪是粉色的。", "as fat as a pig"),
            ("cow", "n. 奶牛", "Cows give us milk.", "奶牛给我们牛奶。", "milk a cow 挤奶"),
            ("sheep", "n. 绵羊", "The sheep eat grass.", "绵羊吃草。", "单复数同形 sheep！"),
            ("horse", "n. 马", "I can ride a horse.", "我会骑马。", "ride a horse 骑马"),
            ("monkey", "n. 猴子", "Monkeys love bananas.", "猴子爱香蕉。", "复数 monkeys（y 变 ies）"),
            ("tiger", "n. 老虎", "The tiger has stripes.", "老虎有条纹。", "tiger 重音在前 /ˈtaɪɡə/"),
            ("lion", "n. 狮子", "The lion is the king.", "狮子是百兽之王。", "lion 重音在后 /laɪˈən/"),
            ("elephant", "n. 大象", "An elephant is very big.", "大象非常大。", "an elephant 用 an！"),
            ("bear", "n. 熊", "The bear sleeps in winter.", "熊冬天冬眠。", "bear 双义：忍受"),
            ("panda", "n. 熊猫", "Pandas live in China.", "熊猫生活在中国。", "giant panda 大熊猫"),
            ("zebra", "n. 斑马", "Zebras have black and white stripes.", "斑马有黑白条纹。", "zebra crossing 斑马线"),
            ("giraffe", "n. 长颈鹿", "The giraffe has a long neck.", "长颈鹿脖子长。", "读 /dʒəˈrɑːf/ 重音在后"),
            ("snake", "n. 蛇", "A snake has no legs.", "蛇没有腿。", "snake 读 /sneɪk/"),
            ("mouse", "n. 老鼠", "The mouse is afraid of cats.", "老鼠怕猫。", "复数 mice；也指鼠标"),
            ("frog", "n. 青蛙", "Frogs can jump far.", "青蛙跳得远。", "frog 读 /frɒɡ/"),
            ("bee", "n. 蜜蜂", "Bees make honey.", "蜜蜂酿蜜。", "as busy as a bee"),
            ("butterfly", "n. 蝴蝶", "The butterfly has pretty wings.", "蝴蝶有漂亮的翅膀。", "复数 butterflies"),
            ("egg", "n. 蛋", "The hen lays an egg.", "母鸡下了一个蛋。", "an egg 用 an；egg 蛋形物体"),
            ("tail", "n. 尾巴", "The dog wags its tail.", "狗摇尾巴。", "tail 读 /teɪl/"),
            ("wing", "n. 翅膀", "Birds have two wings.", "鸟有两只翅膀。", "wing 与 win 押韵"),
            ("zoo", "n. 动物园", "We see lions at the zoo.", "我们在动物园看狮子。", "at the zoo；zoo 复数 zoos"),
            ("farm", "n. 农场", "There are many animals on the farm.", "农场有很多动物。", "on the farm 用 on"),
            ("forest", "n. 森林", "Bears live in the forest.", "熊住在森林里。", "in the forest"),
            ("feed", "v. 喂", "Don't feed the animals.", "不要投喂动物。", "feed on 以…为食"),
            ("pet", "n. 宠物", "My pet is a rabbit.", "我的宠物是兔子。", "keep a pet 养宠物"),
            ("cage", "n. 笼子", "The bird is in a cage.", "鸟在笼子里。", "cage 读 /keɪdʒ/"),
            ("hunt", "v. 捕猎", "Lions hunt at night.", "狮子夜间捕猎。", "hunt for 寻找"),
            ("wild", "adj. 野生的", "Wild animals need care.", "野生动物需要保护。", "wild animal 野生动物"),
            ("fast", "adj. 快的", "The cheetah runs fast.", "猎豹跑得快。", "fast 既作形容词也作副词"),
            ("slow", "adj. 慢的", "The turtle is slow.", "乌龟很慢。", "slow down 减速"),
            ("cute", "adj. 可爱的", "What a cute puppy!", "多可爱的小狗！", "cute 口语高频"),
            ("dangerous", "adj. 危险的", "Some snakes are dangerous.", "有些蛇很危险。", "be dangerous；danger 名词"),
            ("safe", "adj. 安全的", "The cage keeps us safe.", "笼子保证我们安全。", "safe and sound 安然无恙"),
        ],
    },
]
