# -*- coding: utf-8 -*-
"""小学词汇·第 1 批：数字与时间 / 颜色与形状 / 家人与朋友。

词条格式：(单词, 音标, 词性+词义, 例句, 例句中文, 讲解)
由 vocab_primary 合并进课程库，以"单词模式"练习。
"""

GROUPS = [
    {
        "key": "num_time",
        "title": "词汇 · 数字与时间",
        "desc": "数字 1-100、星期、月份与时间表达，小学数学英语双启蒙。",
        "items": [
            ("one", "/wʌn/", "num. 一", "I have one brother.", "我有一个哥哥。", "one 前可用 a：a one-way road 单行道；one of + 复数"),
            ("two", "/tuː/", "num. 二", "Two apples, please.", "请给我两个苹果。", "two 后接复数名词：two books 两本书"),
            ("three", "/θriː/", "num. 三", "The book has three pictures.", "这本书有三张图画。", "th 咬舌音 /θ/；three boys"),
            ("four", "/fɔː/", "num. 四", "There are four seasons.", "一年有四个季节。", "fourteen 14 是 forty 40 少个 u：forty"),
            ("five", "/faɪv/", "num. 五", "Give me five!", "击个掌！", "fifth 第五：ve 变 f 再加 th"),
            ("six", "/sɪks/", "num. 六", "School starts at six.", "学校六点开始。", "SIXteen 16 与 SIXty 60 重音不同"),
            ("seven", "/ˈsevn/", "num. 七", "I get up at seven.", "我七点起床。", "重音在前：SEV-en"),
            ("eight", "/eɪt/", "num. 八", "It is eight o'clock.", "现在是八点钟。", "gh 不发音；eighth 第八"),
            ("nine", "/naɪn/", "num. 九", "Nine cats are sleeping.", "九只猫在睡觉。", "ninth 第九去 e"),
            ("ten", "/ten/", "num. 十", "I can count to ten.", "我能数到十。", "tenth 第十"),
            ("eleven", "/ɪˈlevn/", "num. 十一", "There are eleven players.", "有十一名队员。", "重音在后：e-LEV-en"),
            ("twelve", "/twelv/", "num. 十二", "A year has twelve months.", "一年有十二个月。", "twelfth 第十二 ve→f"),
            ("thirteen", "/ˌθɜːˈtiːn/", "num. 十三", "Thirteen is unlucky for some.", "十三对有些人来说不吉利。", "thir- 不是 three-"),
            ("fourteen", "/ˌfɔːˈtiːn/", "num. 十四", "She is fourteen years old.", "她十四岁。", "重音在 -teen"),
            ("fifteen", "/ˌfɪfˈtiːn/", "num. 十五", "The bus is fifteen minutes late.", "公交车晚了十五分钟。", "fif- 不是 five-"),
            ("twenty", "/ˈtwenti/", "num. 二十", "My grandma is seventy, not twenty!", "我奶奶七十岁，不是二十岁！", "21 是 twenty-one"),
            ("thirty", "/ˈθɜːti/", "num. 三十", "Thirty days has September.", "九月有三十天。", "与 thirteen 13 重音位置不同"),
            ("forty", "/ˈfɔːti/", "num. 四十", "Forty students are here.", "四十名学生都到了。", "40 没有 u：forty"),
            ("fifty", "/ˈfɪfti/", "num. 五十", "The book has fifty pages.", "这本书有五十页。", "50 fifty / 15 fifteen"),
            ("hundred", "/ˈhʌndrəd/", "num. 百", "The school has five hundred pupils.", "学校有五百名学生。", "不加 s：five hundred"),
            ("first", "/fɜːst/", "num. 第一", "Today is the first day of school.", "今天是开学第一天。", "序数词前加 the"),
            ("second", "/ˈsekənd/", "num. 第二", "This is my second try.", "这是我的第二次尝试。", "second 也是秒"),
            ("third", "/θɜːd/", "num. 第三", "He came third in the race.", "他赛跑了第三名。", "three→third 不规则"),
            ("Monday", "/ˈmʌndeɪ/", "n. 星期一", "We start school on Monday.", "我们星期一开学。", "首字母大写；on Monday"),
            ("Tuesday", "/ˈtjuːzdeɪ/", "n. 星期二", "I have music on Tuesday.", "我星期二有音乐课。", "Tue 读 /tjuː/"),
            ("Wednesday", "/ˈwenzdeɪ/", "n. 星期三", "Wednesday is my busy day.", "星期三是我忙的一天。", "首字母 W 不发音！"),
            ("Thursday", "/ˈθɜːzdeɪ/", "n. 星期四", "The test is on Thursday.", "考试在星期四。", "th 咬舌音"),
            ("Friday", "/ˈfraɪdeɪ/", "n. 星期五", "We play games on Friday.", "我们星期五做游戏。", "Fri- 读 /fraɪ/"),
            ("Saturday", "/ˈsætədeɪ/", "n. 星期六", "No school on Saturday.", "星期六不上学。", "weekend=Saturday+Sunday"),
            ("Sunday", "/ˈsʌndeɪ/", "n. 星期日", "I visit grandma on Sunday.", "我周日去看奶奶。", "on Sundays 每个周日"),
            ("week", "/wiːk/", "n. 星期，周", "A week has seven days.", "一周有七天。", "this/last/week 不加介词"),
            ("month", "/mʌnθ/", "n. 月份", "June is my favorite month.", "六月是我最喜欢的月份。", "th 读 /θ/"),
            ("year", "/jɪə/", "n. 年", "Happy New Year!", "新年快乐！", "this year 不加介词"),
            ("morning", "/ˈmɔːnɪŋ/", "n. 早晨", "Good morning, class!", "同学们早上好！", "in the morning"),
            ("afternoon", "/ˌɑːftəˈnuːn/", "n. 下午", "See you in the afternoon.", "下午见。", "重音在 noon"),
            ("evening", "/ˈiːvnɪŋ/", "n. 傍晚", "We watch TV in the evening.", "我们晚上看电视。", "even- 读 /iːvn/"),
            ("day", "/deɪ/", "n. 天，日子", "What a nice day!", "多好的一天！", "every day 分开写"),
            ("night", "/naɪt/", "n. 夜晚", "Good night, Mum.", "晚安，妈妈。", "at night；gh 不发音"),
            ("today", "/təˈdeɪ/", "adv. 今天", "Today is Monday.", "今天是星期一。", "前不加介词"),
            ("tomorrow", "/təˈmɒrəʊ/", "adv. 明天", "Tomorrow is my birthday.", "明天是我生日。", "tomor-row 双 r"),
            ("yesterday", "/ˈjestədeɪ/", "adv. 昨天", "It rained yesterday.", "昨天下雨了。", "常配过去时"),
            ("time", "/taɪm/", "n. 时间", "What time is it?", "现在几点了？", "It's time to + 动词"),
            ("o'clock", "/əˈklɒk/", "adv. …点钟", "It is seven o'clock.", "现在七点整。", "只用于整点"),
            ("half", "/hɑːf/", "n. 一半", "It is half past six.", "现在六点半。", "half past + 小时"),
            ("birthday", "/ˈbɜːθdeɪ/", "n. 生日", "Happy birthday to you!", "祝你生日快乐！", "birth 读 /bɜːθ/"),
            ("hour", "/ˈaʊə/", "n. 小时", "We play for one hour.", "我们玩一个小时。", "h 不发音：an hour"),
            ("minute", "/ˈmɪnɪt/", "n. 分钟", "Wait a minute, please.", "请等一分钟。", "just a minute 稍等"),
        ],
    },
    {
        "key": "color_shape",
        "title": "词汇 · 颜色与形状",
        "desc": "颜色、形状与外观描述词汇，美术与美术课英语。",
        "items": [
            ("red", "/red/", "adj. 红色的", "The apple is red.", "这个苹果是红色的。", "in red 穿红衣"),
            ("blue", "/bluː/", "adj. 蓝色的", "The sky is blue today.", "今天天空是蓝色的。", "blue 也指忧伤 feel blue"),
            ("yellow", "/ˈjeləʊ/", "adj. 黄色的", "The sun looks yellow.", "太阳看起来是黄色的。", "yellow light 黄灯"),
            ("green", "/ɡriːn/", "adj. 绿色的", "The leaves are green in summer.", "夏天树叶是绿色的。", "green tea 绿茶"),
            ("black", "/blæk/", "adj. 黑色的", "I have a black pen.", "我有一支黑色的钢笔。", "black tea 红茶"),
            ("white", "/waɪt/", "adj. 白色的", "The snow is white.", "雪是白色的。", "wh- 读 /w/"),
            ("brown", "/braʊn/", "adj. 棕色的", "The bear is brown.", "这只熊是棕色的。", "brown bread 黑面包"),
            ("pink", "/pɪŋk/", "adj. 粉色的", "Her dress is pink.", "她的裙子是粉色的。", "in the pink 气色好"),
            ("purple", "/ˈpɜːpl/", "adj. 紫色的", "I like purple flowers.", "我喜欢紫色的花。", "与 people 押韵"),
            ("orange", "/ˈɒrɪndʒ/", "adj. 橙色的", "The juice is orange.", "这果汁是橙色的。", "也指橙子"),
            ("grey", "/ɡreɪ/", "adj. 灰色的", "The cat is grey and white.", "这只猫是灰白相间的。", "美式 gray"),
            ("colour", "/ˈkʌlə/", "n. 颜色", "What colour is your bag?", "你的书包是什么颜色的？", "美式 color"),
            ("light", "/laɪt/", "adj. 浅色的", "This is light blue.", "这是浅蓝色。", "light blue 浅蓝"),
            ("dark", "/dɑːk/", "adj. 深色的，黑暗的", "It gets dark at night.", "夜里天变黑。", "get dark 天变黑"),
            ("circle", "/ˈsɜːkl/", "n. 圆形", "Draw a circle, please.", "请画一个圆。", "a circle"),
            ("square", "/skweə/", "n. 正方形", "A square has four sides.", "正方形有四条边。", "也指广场"),
            ("triangle", "/ˈtraɪæŋɡl/", "n. 三角形", "A triangle has three sides.", "三角形有三条边。", "tri- 表示三"),
            ("star", "/stɑː/", "n. 星形，星星", "The flag has five stars.", "这面旗有五颗星。", "r 不卷舌读 /ɑː/"),
            ("heart", "/hɑːt/", "n. 心形，心脏", "She drew a red heart.", "她画了一个红心。", "learn by heart 背熟"),
            ("shape", "/ʃeɪp/", "n. 形状", "What shape is the ball?", "球是什么形状的？", "sh- 读 /ʃ/"),
            ("same", "/seɪm/", "adj. 相同的", "We are in the same class.", "我们在同一个班。", "必须 the same"),
            ("different", "/ˈdɪfrənt/", "adj. 不同的", "We have different ideas.", "我们有不同的想法。", "be different from"),
            ("new", "/njuː/", "adj. 新的", "This is my new schoolbag.", "这是我的新书包。", "news 新闻不可数"),
            ("old", "/əʊld/", "adj. 旧的，老的", "My bike is old but fast.", "我的自行车旧但快。", "old 双义"),
            ("long", "/lɒŋ/", "adj. 长的", "The river is very long.", "这条河很长。", "how long 问长度"),
            ("short", "/ʃɔːt/", "adj. 短的，矮的", "The pencil is short now.", "这支铅笔现在很短了。", "short 双义"),
            ("big", "/bɪɡ/", "adj. 大的", "The elephant is big.", "大象很大。", "big-little 反义"),
            ("small", "/smɔːl/", "adj. 小的", "A small mouse ran by.", "一只小老鼠跑过。", "small-big 反义"),
            ("tall", "/tɔːl/", "adj. 高的", "My father is tall.", "我爸爸个子高。", "how tall 问身高"),
            ("beautiful", "/ˈbjuːtɪfl/", "adj. 美丽的", "What a beautiful garden!", "多美的花园啊！", "重音在 beau-"),
            ("pretty", "/ˈprɪti/", "adj. 漂亮的", "The flower is pretty.", "这朵花很漂亮。", "也作副词 pretty good"),
            ("clean", "/kliːn/", "adj. 干净的", "Keep the room clean.", "保持房间干净。", "也可作动词"),
            ("dirty", "/ˈdɜːti/", "adj. 脏的", "My hands are dirty.", "我的手脏了。", "ir 读 /ɜː/"),
            ("round", "/raʊnd/", "adj. 圆的", "The ball is round.", "球是圆的。", "all year round 全年"),
        ],
    },
    {
        "key": "family",
        "title": "词汇 · 家人与朋友",
        "desc": "家庭成员、称呼与人际交往词汇。",
        "items": [
            ("family", "/ˈfæməli/", "n. 家庭", "My family is big.", "我的家庭很大。", "作整体单数动词"),
            ("father", "/ˈfɑːðə/", "n. 爸爸", "My father is a doctor.", "我爸爸是医生。", "th 读 /ð/"),
            ("mother", "/ˈmʌðə/", "n. 妈妈", "Mother cooks well.", "妈妈做饭好吃。", "th 读 /ð/"),
            ("parent", "/ˈpeərənt/", "n. 父母", "My parents love me.", "我的父母爱我。", "parents 复数双亲"),
            ("grandfather", "/ˈɡrænfɑːðə/", "n. 爷爷；外公", "Grandfather tells stories.", "爷爷讲故事。", "grand- 隔代"),
            ("grandmother", "/ˈɡrænmʌðə/", "n. 奶奶；外婆", "Grandmother makes cakes.", "奶奶做蛋糕。", "grandma 口语"),
            ("grandparent", "/ˈɡrænpeərənt/", "n. 祖父母", "We visit our grandparents.", "我们去看望祖父母。", "grandparents 统称"),
            ("brother", "/ˈbrʌðə/", "n. 兄弟", "My brother is younger.", "我弟弟年纪更小。", "th 读 /ð/"),
            ("sister", "/ˈsɪstə/", "n. 姐妹", "My sister is six.", "我妹妹六岁。", "不分姐姐妹妹"),
            ("uncle", "/ˈʌŋkl/", "n. 叔叔；舅舅", "Uncle Wang lives nearby.", "王叔叔住在附近。", "c 不发音读 /ŋk/"),
            ("aunt", "/ɑːnt/", "n. 姑姑；阿姨", "Aunt Li is a nurse.", "李阿姨是护士。", "读 /ɑːnt/"),
            ("cousin", "/ˈkʌzn/", "n. 堂/表兄弟姐妹", "My cousin is my best friend.", "我表哥是我最好的朋友。", "不分男女"),
            ("friend", "/frend/", "n. 朋友", "She is my good friend.", "她是我的好朋友。", "ie 在 i 前：friend"),
            ("boy", "/bɔɪ/", "n. 男孩", "The boy runs fast.", "这个男孩跑得快。", "oy 双元音"),
            ("girl", "/ɡɜːl/", "n. 女孩", "The girl sings well.", "这个女孩唱歌好听。", "ir 读 /ɜː/"),
            ("baby", "/ˈbeɪbi/", "n. 婴儿", "The baby is sleeping.", "婴儿在睡觉。", "复数 babies"),
            ("child", "/tʃaɪld/", "n. 孩子", "The child is playing.", "孩子在玩。", "复数 children"),
            ("children", "/ˈtʃɪldrən/", "n. 孩子们", "Children like games.", "孩子们喜欢游戏。", "child 的复数"),
            ("people", "/ˈpiːpl/", "n. 人们", "Many people are here.", "很多人在这里。", "本身是复数"),
            ("man", "/mæn/", "n. 男人", "That man is my teacher.", "那个男人是我的老师。", "复数 men"),
            ("woman", "/ˈwʊmən/", "n. 女人", "The woman is kind.", "这位女士很善良。", "复数 women /ˈwɪmɪn/"),
            ("name", "/neɪm/", "n. 名字", "My name is Li Hua.", "我的名字叫李华。", "first name 名"),
            ("Mr", "/ˈmɪstə/", "n. 先生", "This is Mr Brown.", "这是布朗先生。", "Mr+姓"),
            ("Mrs", "/ˈmɪsɪz/", "n. 夫人", "Mrs Green teaches us.", "格林夫人教我们。", "已婚女性"),
            ("love", "/lʌv/", "v. 爱", "I love my family.", "我爱我的家人。", "love doing 喜欢"),
            ("help", "/help/", "v. 帮助", "Can you help me?", "你能帮我吗？", "help sb do sth"),
            ("visit", "/ˈvɪzɪt/", "v. 拜访", "We visit grandma on Sunday.", "我们周日去看奶奶。", "直接接宾语"),
            ("call", "/kɔːl/", "v. 叫，打电话", "Call me at six.", "六点给我打电话。", "all 读 /ɔːl/"),
            ("meet", "/miːt/", "v. 见面", "Nice to meet you.", "很高兴认识你。", "ee 长音"),
            ("welcome", "/ˈwelkəm/", "int. 欢迎", "Welcome to our school!", "欢迎来我们学校！", "welcome to + 地点"),
            ("together", "/təˈɡeðə/", "adv. 一起", "Let's play together.", "我们一起玩吧。", "th 读 /ð/"),
            ("neighbour", "/ˈneɪbə/", "n. 邻居", "Our neighbour has a dog.", "我们的邻居养了只狗。", "美式 neighbor"),
            ("classmate", "/ˈklɑːsmeɪt/", "n. 同学", "He is my classmate.", "他是我的同学。", "合成词"),
            ("twin", "/twɪn/", "n. 双胞胎", "They are twins.", "他们是双胞胎。", "twins 复数"),
            ("home", "/həʊm/", "n. 家", "I go home at four.", "我四点回家。", "go home 不加 to"),
            ("live", "/lɪv/", "v. 居住", "I live in Beijing.", "我住在北京。", "live in + 城市"),
            ("share", "/ʃeə/", "v. 分享", "We share an umbrella.", "我们合用一把伞。", "share with sb"),
            ("care", "/keə/", "v. 关心", "Mum cares for us.", "妈妈照顾我们。", "care about 在乎"),
            ("like", "/laɪk/", "v. 喜欢", "I like my school.", "我喜欢我的学校。", "like doing/to do"),
        ],
    },
]
