# -*- coding: utf-8 -*-
"""小学词汇·第 3 批：食物与饮品 / 服装与物品 / 家与地点。"""

GROUPS = [
    {
        "key": "food_drink",
        "title": "词汇 · 食物与饮品",
        "desc": "三餐、水果、蔬菜与常见饮品词汇。",
        "items": [
            ("food", "n. 食物", "Chinese food is delicious.", "中国菜很好吃。", "food 不可数；fast food 快餐"),
            ("rice", "n. 米饭", "We eat rice for dinner.", "我们晚饭吃米饭。", "rice 不可数；rice noodles 米粉"),
            ("noodles", "n. 面条", "Noodles are my favorite.", "面条是我的最爱。", "常作复数：eat noodles"),
            ("bread", "n. 面包", "I have bread and milk.", "我吃面包喝牛奶。", "bread 不可数：a piece of bread"),
            ("cake", "n. 蛋糕", "The birthday cake is sweet.", "生日蛋糕很甜。", "make a cake 做蛋糕"),
            ("milk", "n. 牛奶", "Drink milk every day.", "每天喝牛奶。", "milk 不可数；a glass of milk"),
            ("water", "n. 水", "Drink more water.", "多喝水。", "water 也可作动词浇水"),
            ("tea", "n. 茶", "Grandpa drinks green tea.", "爷爷喝绿茶。", "a cup of tea 一杯茶"),
            ("juice", "n. 果汁", "Orange juice, please.", "请来橙汁。", "juice 不可数；juicy 多汁的"),
            ("apple", "n. 苹果", "An apple a day keeps the doctor away.", "一天一苹果，医生远离我。", "an apple 用 an；复数 apples"),
            ("banana", "n. 香蕉", "Monkeys eat bananas.", "猴子吃香蕉。", "a bunch of bananas 一串香蕉"),
            ("pear", "n. 梨", "This pear is juicy.", "这个梨很多汁。", "pear 与 pair 同音！"),
            ("grape", "n. 葡萄", "Grapes can make wine.", "葡萄能酿酒。", "a bunch of grapes 一串葡萄"),
            ("peach", "n. 桃子", "The peach is sweet.", "桃子很甜。", "复数 peaches 加 es"),
            ("watermelon", "n. 西瓜", "Watermelon is cool in summer.", "西瓜解暑。", "water + melon 合成"),
            ("mango", "n. 芒果", "Mango smoothies are yummy.", "芒果奶昔很好喝。", "复数 mangoes 或 mangos"),
            ("tomato", "n. 西红柿", "I like tomato soup.", "我喜欢西红柿汤。", "复数 tomatoes 加 es！"),
            ("potato", "n. 土豆", "Baked potatoes are tasty.", "烤土豆很好吃。", "复数 potatoes 加 es！"),
            ("carrot", "n. 胡萝卜", "Rabbits love carrots.", "兔子爱胡萝卜。", "carrots 复数；carrot top 红发人"),
            ("meat", "n. 肉", "Don't eat too much meat.", "别吃太多肉。", "meat 不可数"),
            ("beef", "n. 牛肉", "Beef noodles, please.", "请来牛肉面。", "beef 不可数"),
            ("pork", "n. 猪肉", "Mum cooks pork dumplings.", "妈妈包猪肉饺子。", "pork 不可数"),
            ("hamburger", "n. 汉堡", "Hamburgers are fast food.", "汉堡是快餐。", "口语可说 burger"),
            ("sandwich", "n. 三明治", "I make a sandwich for lunch.", "我午餐做三明治。", "复数 sandwiches 加 es"),
            ("chips", "n. 薯条", "Fish and chips, please.", "请来炸鱼薯条。", "美式 fries；英式 chips"),
            ("ice cream", "n. 冰淇淋", "Two ice creams, please.", "请来两份冰淇淋。", "ice cream 可数或不可数均可"),
            ("sweet", "n. 糖果", "Sweets are bad for teeth.", "糖果伤牙。", "英式 sweet / 美式 candy"),
            ("candy", "n. 糖果", "Don't eat too much candy.", "别吃太多糖。", "美式 candy 不可数"),
            ("chocolate", "n. 巧克力", "Chocolate makes me happy.", "巧克力让我开心。", "a box of chocolates 一盒巧克力"),
            ("biscuit", "n. 饼干", "I have a biscuit with tea.", "我配茶吃饼干。", "美式 cookie"),
            ("hungry", "adj. 饿的", "I am hungry.", "我饿了。", "be hungry；hunger 名词饥饿"),
            ("thirsty", "adj. 渴的", "Are you thirsty?", "你渴吗？", "thirsty 的 th 咬舌"),
            ("eat", "v. 吃", "Eat more vegetables.", "多吃蔬菜。", "eat→ate→eaten"),
            ("drink", "v. 喝", "Drink water after sports.", "运动后喝水。", "drink→drank→drunk"),
            ("taste", "v. 尝", "Taste the soup first.", "先尝尝汤。", "taste good 尝起来好"),
            ("breakfast", "n. 早餐", "Breakfast is ready.", "早餐好了。", "have breakfast 吃早餐（不加 the）"),
            ("lunch", "n. 午餐", "Lunch is at twelve.", "十二点吃午饭。", "have lunch；lunchbox 饭盒"),
            ("dinner", "n. 晚餐", "Dinner is on the table.", "晚饭摆桌上了。", "have dinner；dinner 也可指正餐"),
            ("supper", "n. 晚饭", "After supper we walk.", "晚饭后我们散步。", "supper 与 dinner 近义"),
            ("menu", "n. 菜单", "Read the menu, please.", "请看菜单。", "on the menu 在菜单上"),
            ("delicious", "adj. 美味的", "The cake is delicious.", "蛋糕很美味。", "delicious 不用 very 修饰，用 really"),
            ("cook", "v. 烹饪", "Dad cooks on Sunday.", "周日爸爸做饭。", "cooker 是炉具不是厨师！"),
            ("sweet", "adj. 甜的", "The mango is sweet.", "芒果很甜。", "sweet 双义：糖果/甜的"),
            ("sour", "adj. 酸的", "Lemons are sour.", "柠檬很酸。", "sour milk 酸了的奶"),
            ("hot", "adj. 热的；辣的", "The soup is too hot.", "汤太烫了。", "hot 既指烫也指辣"),
            ("fresh", "adj. 新鲜的", "Fresh fish tastes better.", "新鲜的鱼更好吃。", "fresh air 新鲜空气"),
        ],
    },
    {
        "key": "cloth_things",
        "title": "词汇 · 服装与物品",
        "desc": "衣服穿戴与日常物品词汇。",
        "items": [
            ("clothes", "n. 衣服", "Wash your clothes on Sunday.", "周日洗衣服。", "clothes 永远复数形式，不加 s"),
            ("shirt", "n. 衬衫", "The white shirt is clean.", "白衬衫是干净的。", "shirt 男式衬衫；blouse 女式"),
            ("T-shirt", "n. T恤", "I wear a T-shirt in summer.", "夏天我穿T恤。", "T 形状命名"),
            ("dress", "n. 连衣裙", "She has a red dress.", "她有条红裙子。", "dress 也作动词穿衣"),
            ("skirt", "n. 裙子", "The skirt is short.", "这条裙子很短。", "skirt 短裙，dress 连身裙"),
            ("coat", "n. 外套", "Put on your coat.", "穿上外套。", "put on 穿上动作；wear 穿着状态"),
            ("jacket", "n. 夹克", "A jacket keeps you warm.", "夹克保暖。", "jacket 比 coat 短"),
            ("sweater", "n. 毛衣", "This sweater is wool.", "这件毛衣是羊毛的。", "英式 jumper 也指毛衣"),
            ("trousers", "n. 长裤", "My trousers are blue.", "我的裤子是蓝的。", "复数形式：a pair of trousers"),
            ("pants", "n. 裤子（美式）", "These pants fit me.", "这条裤子合身。", "美式 pants=裤子；英式=内裤！"),
            ("shorts", "n. 短裤", "Wear shorts in summer.", "夏天穿短裤。", "永远复数：a pair of shorts"),
            ("shoes", "n. 鞋子", "Take off your shoes.", "脱鞋。", "一双鞋 a pair of shoes"),
            ("socks", "n. 袜子", "I have warm socks.", "我有暖和的袜子。", "a pair of socks"),
            ("hat", "n. 帽子", "The sun is hot, wear a hat.", "太阳晒，戴帽子。", "hat 有檐帽；cap 鸭舌帽"),
            ("cap", "n. 鸭舌帽", "Baseball players wear caps.", "棒球运动员戴帽。", "cap 遮阳帽"),
            ("glasses", "n. 眼镜", "Grandpa wears glasses.", "爷爷戴眼镜。", "永远复数：wear glasses"),
            ("wear", "v. 穿着", "She wears a smile.", "她面带微笑。", "wear 状态；put on 动作"),
            ("umbrella", "n. 雨伞", "Take an umbrella, it may rain.", "带把伞，可能下雨。", "an umbrella 用 an"),
            ("watch", "n. 手表", "My watch is fast.", "我的手表快了。", "watch 双义：观看"),
            ("key", "n. 钥匙", "I lost my key.", "我把钥匙丢了。", "the key to the door 门钥匙（用 to）"),
            ("money", "n. 钱", "Money is in my pocket.", "钱在我口袋里。", "money 不可数；pocket money 零花钱"),
            ("pocket", "n. 口袋", "My hands are in pockets.", "我手插口袋。", "in one's pocket"),
            ("toy", "n. 玩具", "Toy trains are fun.", "玩具火车很好玩。", "复数 toys；toy shop 玩具店"),
            ("ball", "n. 球", "Bounce the ball, please.", "请拍球。", "play ball 玩球；basketball 篮球"),
            ("kite", "n. 风筝", "Fly a kite in spring.", "春天放风筝。", "fly a kite 放风筝"),
            ("doll", "n. 玩偶", "The doll has curly hair.", "玩偶有卷发。", "doll 复数 dolls"),
            ("present", "n. 礼物", "This present is for you.", "这份礼物给你。", "present 双义：出席的"),
            ("gift", "n. 礼物", "A birthday gift!", "一份生日礼物！", "gift 与 present 近义，gift 更正式"),
            ("photo", "n. 照片", "Look at this photo.", "看这张照片。", "take photos 拍照；photograph 全称"),
            ("picture", "n. 图片", "Draw a picture of your home.", "画一张你家的图。", "picture 双义：描绘"),
            ("card", "n. 卡片", "Make a card for Mum.", "给妈妈做张卡。", "birthday card 生日卡"),
            ("box", "n. 盒子", "The box is under the bed.", "盒子在床下。", "复数 boxes 加 es"),
            ("bottle", "n. 瓶子", "A bottle of water, please.", "请来一瓶水。", "a bottle of 一瓶"),
            ("cup", "n. 杯子", "This cup is hot.", "杯子很烫。", "a cup of tea"),
            ("basket", "n. 篮子", "Put apples in the basket.", "把苹果放进篮子。", "basketball 篮球"),
            ("mirror", "n. 镜子", "Look in the mirror.", "照镜子。", "mirror 读 /ˈmɪrə/"),
            ("clock", "n. 时钟", "The clock is on the wall.", "钟在墙上。", "clock 挂钟/座钟；watch 手表"),
            ("lamp", "n. 台灯", "Turn on the lamp.", "打开台灯。", "turn on/off 开关"),
            ("light", "n. 灯", "The light is too bright.", "灯太亮了。", "traffic lights 红绿灯"),
            ("phone", "n. 电话", "My phone is ringing.", "我的电话响了。", "telephone 全称；answer the phone 接电话"),
            ("wallet", "n. 钱包", "My wallet is empty!", "我的钱包空了！", "wallet 男用；purse 女用"),
        ],
    },
    {
        "key": "home_place",
        "title": "词汇 · 家与地点",
        "desc": "房屋房间、社区场所与自然景观词汇。",
        "items": [
            ("house", "n. 房子", "Their house has a garden.", "他们家有个花园。", "house 建筑；home 家的感觉"),
            ("room", "n. 房间", "My room is upstairs.", "我的房间在楼上。", "make room 让空间"),
            ("bedroom", "n. 卧室", "The bedroom is tidy.", "卧室很整洁。", "bed + room 合成"),
            ("living room", "n. 客厅", "We watch TV in the living room.", "我们在客厅看电视。", "英式 sitting room 同义"),
            ("kitchen", "n. 厨房", "Mum is in the kitchen.", "妈妈在厨房。", "kitchen 读 /ˈkɪtʃɪn/"),
            ("bathroom", "n. 浴室", "The bathroom is free now.", "浴室现在空了。", "go to the bathroom 上厕所委婉说法"),
            ("door", "n. 门", "Close the door, please.", "请关门。", "next door 隔壁"),
            ("window", "n. 窗户", "Open the window for fresh air.", "开窗透新鲜空气。", "out of the window 窗外"),
            ("wall", "n. 墙", "The wall is white.", "墙是白色的。", "on the wall 挂在墙上"),
            ("floor", "n. 地板；楼层", "The cat sits on the floor.", "猫坐在地板上。", "英式一楼 ground floor"),
            ("table", "n. 桌子", "Four people sit at the table.", "四个人坐在桌边。", "at the table 坐桌边"),
            ("bed", "n. 床", "Make the bed after you get up.", "起床后整理床铺。", "go to bed 上床睡觉"),
            ("sofa", "n. 沙发", "The cat sleeps on the sofa.", "猫睡在沙发上。", "sofa 音译词"),
            ("garden", "n. 花园", "Flowers grow in the garden.", "花园里长花。", "in the garden"),
            ("yard", "n. 院子", "The kids play in the yard.", "孩子们在院子玩。", "yard 美式常用"),
            ("park", "n. 公园", "We walk in the park.", "我们在公园散步。", "in the park"),
            ("shop", "n. 商店", "The shop opens at nine.", "商店九点开门。", "go shopping 去购物"),
            ("store", "n. 商店", "This store sells toys.", "这家店卖玩具。", "store 美式常用"),
            ("supermarket", "n. 超市", "Buy fruit at the supermarket.", "在超市买水果。", "super + market 合成"),
            ("cinema", "n. 电影院", "We go to the cinema on Friday.", "我们周五去电影院。", "at the cinema；movie theater 美式"),
            ("museum", "n. 博物馆", "The museum is free on Monday.", "博物馆周一免费。", "复数 museums"),
            ("restaurant", "n. 餐馆", "This restaurant serves noodles.", "这家餐馆卖面条。", "restaurant 读 /ˈrestrɒnt/"),
            ("hotel", "n. 旅馆", "We stay at a hotel.", "我们住旅馆。", "stay at a hotel 用 at"),
            ("city", "n. 城市", "Shanghai is a big city.", "上海是大城市。", "复数 cities（y 变 ies）"),
            ("country", "n. 国家；乡村", "China is a great country.", "中国是伟大的国家。", "country 双义：国家/乡下"),
            ("street", "n. 街道", "Our street is quiet.", "我们的街道很安静。", "in the street 英式；on the street 美式"),
            ("road", "n. 路", "Cross the road carefully.", "小心过马路。", "on the road 在路上"),
            ("bridge", "n. 桥", "The bridge crosses the river.", "桥横跨河流。", "on the bridge 在桥上"),
            ("station", "n. 车站", "Meet me at the station.", "车站见。", "train station 火车站"),
            ("airport", "n. 机场", "We arrive at the airport at six.", "我们六点到机场。", "at the airport"),
            ("beach", "n. 海滩", "We play on the beach.", "我们在沙滩玩。", "on the beach；复数 beaches"),
            ("river", "n. 河", "The river runs fast.", "河水流得急。", "on the river 在河上"),
            ("lake", "n. 湖", "The lake is calm.", "湖面平静。", "by the lake 在湖边"),
            ("mountain", "n. 山", "We climb mountains in autumn.", "我们秋天爬山。", "climb mountains 用复数表泛指"),
            ("tree", "n. 树", "Birds sing in the tree.", "鸟在树上唱歌。", "in the tree 外来物；on the tree 长在树上"),
            ("flower", "n. 花", "Roses are beautiful flowers.", "玫瑰是美丽的花。", "in flower 开花中"),
            ("grass", "n. 草", "Don't walk on the grass.", "别踩草地。", "grass 不可数"),
            ("forest", "n. 森林", "The forest is green in summer.", "森林夏天是绿的。", "in the forest"),
            ("sea", "n. 海", "The sea is blue.", "海是蓝的。", "by the sea 在海边"),
            ("world", "n. 世界", "The world is big.", "世界很大。", "all over the world 全世界"),
        ],
    },
]
