# -*- coding: utf-8 -*-
"""小学词汇·第 4 批：出行与交通 / 天气与季节 / 动词与日常用语。"""

GROUPS = [
    {
        "key": "transport",
        "title": "词汇 · 出行与交通",
        "desc": "交通工具、方向与出行方式词汇。",
        "items": [
            ("car", "n. 小汽车", "Dad drives a car.", "爸爸开小汽车。", "by car 坐车（不加 the）"),
            ("bus", "n. 公交车", "The bus is coming.", "公交车来了。", "by bus / on the bus 两种说法"),
            ("bike", "n. 自行车", "I ride my bike to school.", "我骑车上学。", "by bike；bicycle 全称"),
            ("train", "n. 火车", "The train leaves at eight.", "火车八点出发。", "by train；catch a train 赶火车"),
            ("plane", "n. 飞机", "The plane flies high.", "飞机飞得很高。", "by plane / by air；airplane 全称"),
            ("ship", "n. 轮船", "The ship sails today.", "轮船今天起航。", "by ship；on the ship"),
            ("boat", "n. 小船", "We row a boat on the lake.", "我们在湖上划船。", "boat 小船，ship 大船"),
            ("taxi", "n. 出租车", "Take a taxi, it's late.", "晚了，打车吧。", "by taxi / take a taxi"),
            ("subway", "n. 地铁", "The subway is fast.", "地铁很快。", "美式 subway；英式 underground"),
            ("walk", "v. 步行", "I walk to school.", "我走路去学校。", "walk to + 地点；on foot 同义"),
            ("run", "v. 跑", "He runs faster than me.", "他跑得比我快。", "run→ran→run；run away 逃走"),
            ("jump", "v. 跳", "The rabbit can jump high.", "兔子跳得高。", "jump into 跳进"),
            ("ride", "v. 骑", "Can you ride a bike?", "你会骑车吗？", "ride→rode→ridden"),
            ("fly", "v. 飞", "Birds fly south in winter.", "鸟冬天飞往南方。", "fly→flew→flown"),
            ("drive", "v. 开车", "Drive slowly near school.", "学校附近开慢点。", "drive→drove→driven"),
            ("go", "v. 去", "Let's go home.", "我们回家吧。", "go→went→gone；go to school"),
            ("come", "v. 来", "Come here, please.", "请过来。", "come→came→come；come back 回来"),
            ("travel", "v. 旅行", "We travel by train.", "我们坐火车旅行。", "travel 不可数作名词旅行总称"),
            ("ticket", "n. 票", "Two tickets, please.", "请来两张票。", "a ticket for/to the show"),
            ("driver", "n. 司机", "The driver is kind.", "司机很友善。", "drive + r = 开车的人"),
            ("passenger", "n. 乘客", "Passengers wait here.", "乘客在这里等。", "passenger 音节多，重音在前"),
            ("left", "adj. 左边的", "Turn left at the shop.", "在商店左转。", "on the left 在左边"),
            ("right", "adj. 右边的", "The bank is on your right.", "银行在你右边。", "right 双义：右边/正确"),
            ("straight", "adv. 直地", "Go straight on.", "直走。", "go straight 直走"),
            ("turn", "v. 转向", "Turn right after the bridge.", "过桥后右转。", "turn left/right/left 变得"),
            ("near", "adj. 近的", "The park is near my home.", "公园在我家附近。", "near here 附近；nearby 附近的"),
            ("far", "adj. 远的", "Is it far from here?", "离这里远吗？", "far from 远离；how far 问距离"),
            ("map", "n. 地图", "Read the map first.", "先看地图。", "on the map"),
            ("way", "n. 路线；方法", "This is the way to school.", "这是去学校的路。", "on the way 在路上；by the way 顺便说"),
            ("stop", "v. 停止", "The car stops at the light.", "车在红灯停下。", "stop to do 停下来去做 / stop doing 停止做"),
            ("wait", "v. 等待", "Wait for me!", "等等我！", "wait for sb 等某人"),
            ("arrive", "v. 到达", "We arrive in Beijing today.", "我们今天到北京。", "arrive in 大地方 / at 小地方"),
            ("leave", "v. 离开", "The bus leaves soon.", "车很快就开。", "leave for 出发去某地"),
            ("carry", "v. 携带", "I carry a heavy bag.", "我背着个重包。", "carry 搬运无方向；bring 带来"),
            ("speed", "n. 速度", "The train has high speed.", "火车高速运行。", "high-speed rail 高铁"),
        ],
    },
    {
        "key": "weather",
        "title": "词汇 · 天气与季节",
        "desc": "天气现象与四季词汇，学会描述天气。",
        "items": [
            ("weather", "n. 天气", "The weather is nice today.", "今天天气很好。", "weather 不可数；What's the weather like?"),
            ("sun", "n. 太阳", "The sun is bright.", "太阳很明亮。", "in the sun 在阳光下"),
            ("sunny", "adj. 晴朗的", "It is sunny today.", "今天晴天。", "名词+ny 构形容词：sun→sunny"),
            ("rain", "n. 雨", "The rain is heavy.", "雨很大。", "rain cats and dogs 倾盆大雨"),
            ("rainy", "adj. 下雨的", "A rainy day again!", "又下雨了！", "rain→rainy"),
            ("cloud", "n. 云", "Look at the white clouds.", "看那些白云。", "复数 clouds"),
            ("cloudy", "adj. 多云的", "It is cloudy outside.", "外面多云。", "cloud→cloudy"),
            ("wind", "n. 风", "The wind blows hard.", "风很大。", "in the wind 在风中"),
            ("windy", "adj. 有风的", "A windy day is good for kites.", "有风的日子适合放风筝。", "wind→windy"),
            ("snow", "n. 雪", "The snow is white and soft.", "雪又白又软。", "snow 可作动词下雪"),
            ("snowy", "adj. 下雪的", "A snowy winter!", "一个多雪的冬天！", "snow→snowy"),
            ("hot", "adj. 热的", "Summer is hot here.", "这里夏天很热。", "天气热用 hot 不是 warm"),
            ("cold", "adj. 冷的", "It is cold in December.", "十二月很冷。", "have a cold 感冒；cold 冷"),
            ("warm", "adj. 温暖的", "Spring is warm.", "春天温暖。", "keep warm 保暖"),
            ("cool", "adj. 凉爽的", "Autumn is cool.", "秋天凉爽。", "cool 双义：凉爽/酷"),
            ("ice", "n. 冰", "The ice is cold.", "冰很冷。", "ice cream 冰淇淋；iceberg 冰山"),
            ("sky", "n. 天空", "The sky is clear tonight.", "今晚天空晴朗。", "in the sky"),
            ("spring", "n. 春天", "Flowers come out in spring.", "春天开花。", "in spring（不加 the）"),
            ("summer", "n. 夏天", "We swim in summer.", "我们夏天游泳。", "in the summer holidays 暑假"),
            ("autumn", "n. 秋天", "Leaves fall in autumn.", "秋天落叶。", "英式 autumn / 美式 fall"),
            ("winter", "n. 冬天", "It snows in winter.", "冬天下雪。", "in winter"),
            ("season", "n. 季节", "Spring is my favorite season.", "春天是我最喜欢的季节。", "four seasons 四季"),
            ("storm", "n. 暴风雨", "The storm is coming.", "暴风雨来了。", "thunderstorm 雷雨"),
            ("rainbow", "n. 彩虹", "A rainbow after rain!", "雨后有彩虹！", "rain + bow 合成"),
            ("blow", "v. 吹", "The wind blows the leaves.", "风吹动树叶。", "blow→blew→blown"),
        ],
    },
    {
        "key": "verbs",
        "title": "词汇 · 动词与日常用语",
        "desc": "小学核心动词与高频日常表达，句子的发动机。",
        "items": [
            ("be", "v. 是", "I am a pupil.", "我是小学生。", "am/is/are 随人称变化：I am, you are, he is"),
            ("have", "v. 有", "I have two books.", "我有两本书。", "he/she 用 has；have to 不得不"),
            ("do", "v. 做", "What do you do on Sunday?", "你周日做什么？", "助动词构成问句：Do you like it?"),
            ("can", "aux. 能", "I can swim.", "我会游泳。", "can+动词原形；否定 can't"),
            ("will", "aux. 将要", "It will rain tomorrow.", "明天要下雨。", "will+动词原形表将来"),
            ("want", "v. 想要", "I want an ice cream.", "我想要冰淇淋。", "want to do 想做某事"),
            ("need", "v. 需要", "We need more time.", "我们需要更多时间。", "need to do 需要做"),
            ("make", "v. 制作", "Let's make a cake.", "我们做蛋糕吧。", "make→made→made；make friends"),
            ("take", "v. 拿，带走", "Take this book home.", "把这本书带回家。", "take 与 bring 相反方向"),
            ("give", "v. 给", "Give me the ball, please.", "请把球给我。", "give sb sth / give sth to sb"),
            ("get", "v. 得到", "I get a letter.", "我收到一封信。", "get→got→got；get up 起床"),
            ("put", "v. 放", "Put the toys away.", "把玩具收好。", "put→put→put；put on 穿上"),
            ("find", "v. 找到", "I can't find my pen.", "我找不到钢笔。", "find→found→found；find out 查明"),
            ("know", "v. 知道", "I know the answer.", "我知道答案。", "know→knew→known；k 不发音"),
            ("think", "v. 想，认为", "I think you are right.", "我认为你是对的。", "think→thought；think of 想起"),
            ("say", "v. 说", "Say it again, please.", "请再说一遍。", "say→said；say 后接内容"),
            ("speak", "v. 说（语言）", "We speak Chinese.", "我们说中文。", "speak to sb 对某人说"),
            ("tell", "v. 告诉", "Tell me a story.", "给我讲个故事。", "tell sb sth 双宾语"),
            ("ask", "v. 问", "Ask the teacher.", "问老师。", "ask sb a question"),
            ("look", "v. 看", "Look at the blackboard.", "看黑板。", "look at 强调看的过程"),
            ("see", "v. 看见", "I see a bird.", "我看见一只鸟。", "see 强调结果；see you 再见"),
            ("watch", "v. 观看", "We watch TV at night.", "我们晚上看电视。", "watch TV；watch 观察活动的东西"),
            ("hear", "v. 听见", "I can hear music.", "我能听到音乐。", "hear 结果；listen 过程"),
            ("listen", "v. 听", "Listen to me, please.", "请听我说。", "listen to 必须加 to！"),
            ("play", "v. 玩，打（球）", "We play football.", "我们踢足球。", "play + 球类不加 the；play the piano 加 the"),
            ("work", "v. 工作", "Dad works in a bank.", "爸爸在银行工作。", "work 不可数作名词工作"),
            ("open", "v. 打开", "Open your books.", "打开书。", "open the door；open 反义 close"),
            ("close", "v. 关闭", "Close the window.", "关窗。", "close 与 near 同音异义"),
            ("buy", "v. 买", "I buy fruit every week.", "我每周买水果。", "buy→bought；buy sth for sb"),
            ("sell", "v. 卖", "The shop sells bread.", "这家店卖面包。", "sell→sold；buy 与 sell 相对"),
            ("send", "v. 发送", "Send me a message.", "给我发消息。", "send→sent；send for 派人去请"),
            ("bring", "v. 带来", "Bring your book tomorrow.", "明天带书来。", "bring 来的方向 / take 去的方向"),
            ("wait", "v. 等", "Wait a moment.", "等一下。", "wait for 等待某人"),
            ("wash", "v. 洗", "Wash your hands.", "洗手。", "wash away 冲走"),
            ("cook", "v. 做饭", "Who cooks dinner tonight?", "今晚谁做饭？", "cook 双义：厨师"),
            ("eat", "v. 吃", "Eat an apple a day.", "每天吃个苹果。", "eat→ate→eaten"),
            ("drink", "v. 喝", "What do you drink?", "你喝什么？", "drink→drank→drunk"),
            ("sing", "v. 唱歌", "She sings well.", "她唱歌好听。", "sing→sang→sung"),
            ("dance", "v. 跳舞", "They dance to music.", "他们随音乐起舞。", "dance to + 音乐"),
            ("swim", "v. 游泳", "Fish can swim.", "鱼会游泳。", "swim→swam→swum"),
            ("climb", "v. 爬", "Climb the mountain carefully.", "小心爬山。", "climb 的 b 不发音"),
            ("thank", "v. 感谢", "Thank you very much.", "非常感谢。", "thanks 更口语；Thank you for…"),
            ("please", "int. 请", "Please sit down.", "请坐。", "please 位置灵活：Please…/…, please"),
            ("sorry", "adj. 抱歉的", "I'm sorry I'm late.", "对不起我迟到了。", "be sorry for/to do；I'm sorry 道歉"),
            ("excuse", "int. 打扰一下", "Excuse me, where's the toilet?", "请问厕所在哪？", "Excuse me 打扰前 / sorry 之后"),
            ("hello", "int. 你好", "Hello, everyone!", "大家好！", "hello/hi 通用；hi 更随意"),
            ("goodbye", "int. 再见", "Goodbye, class!", "同学们再见！", "bye 更口语；goodby 拼写变体"),
            ("yes", "int. 是的", "Yes, I can.", "是的，我会。", "yes 与 no 相对；Of course 当然"),
            ("no", "int. 不", "No, thank you.", "不用了，谢谢。", "No problem 没问题"),
            ("great", "adj. 太好了", "That's a great idea!", "这个主意太棒了！", "great 更口语 than good"),
            ("OK", "int. 好的", "OK, let's go!", "好的，走吧！", "okay 全拼；OK 万能回应"),
            ("again", "adv. 再一次", "Try again!", "再试一次！", "again and again 反复地"),
            ("now", "adv. 现在", "It's time to go now.", "现在该走了。", "right now 立刻"),
            ("here", "adv. 这里", "Come here.", "过来。", "here/there 方向相对"),
            ("there", "adv. 那里", "The book is over there.", "书在那边。", "there be 有：There is a book"),
            ("very", "adv. 很", "This is very good.", "这非常好。", "very 修饰形容词/副词，不修饰动词"),
            ("too", "adv. 也；太", "Me too!", "我也是！", "too much 太多；too…to… 太…而不能"),
            ("and", "conj. 和", "Tom and Jerry are friends.", "汤姆和杰瑞是朋友。", "and 连接并列成分"),
            ("but", "conj. 但是", "He is small but strong.", "他个子小但强壮。", "but 表转折"),
            ("or", "conj. 或者", "Tea or coffee?", "茶还是咖啡？", "or 选择；otherwise 否则"),
            ("because", "conj. 因为", "I smile because I am happy.", "我笑因为我开心。", "because 与 so 不能同时用！"),
            ("if", "conj. 如果", "If it rains, we stay home.", "如果下雨，我们就待在家。", "if 条件句主将从现"),
            ("not", "adv. 不", "This is not my bag.", "这不是我的书包。", "n't 是 not 缩写：isn't, don't"),
            ("all", "det. 全部", "All the best!", "一切顺利！", "all of us 我们所有人"),
            ("some", "det. 一些", "I have some questions.", "我有一些问题。", "some 肯定句；any 否定疑问"),
            ("many", "det. 许多", "How many apples?", "多少苹果？", "many+可数；much+不可数"),
            ("more", "det. 更多", "I want more ice cream.", "我想要更多冰淇淋。", "more than 比…多"),
        ],
    },
]
